package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/diamond_golem_f04.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class DiamondGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "diamond_golem_f04";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "diamond_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "diamond_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.DIAMOND;

    public DiamondGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-4F, -6.5F, -3.5F, 8F, 6F, 7F)
                .texOffs(100, 0).addBox(-4.1F, -7F, -3F, 8.2F, 1F, 6F)
                .texOffs(157, 0).addBox(-3F, -8F, -3F, 6F, 1F, 6F)
                .texOffs(206, 0).addBox(-1.5F, -9F, -3F, 3F, 1F, 6F)
                .texOffs(243, 0).addBox(-3.5F, -5.5F, -4.1F, 7F, 2F, 0.6F)
                .texOffs(274, 0).addBox(1.2F, -4.75F, -4.25F, 1.8F, 0.5F, 0.15F)
                .texOffs(302, 0).addBox(2.45F, -3.5F, -4.75F, 1.1F, 2.5F, 0.85F)
                .texOffs(326, 0).addBox(-3F, -4.75F, -4.25F, 1.8F, 0.5F, 0.15F)
                .texOffs(354, 0).addBox(-3.55F, -3.5F, -4.75F, 1.1F, 2.5F, 0.85F)
                .texOffs(378, 0).addBox(-0.75F, -6.5F, -5.25F, 1.5F, 6F, 1F)
                .texOffs(389, 0).addBox(-0.5F, -1F, -5F, 1F, 1F, 1F)
                .texOffs(398, 0).addBox(-0.75F, -6.5F, 3.5F, 1.5F, 5F, 0.75F)
                .texOffs(409, 0).addBox(-4.2F, -1.5F, 3.6F, 8.4F, 1F, 0.9F), PartPose.offset(0F, -10F, 0F));
            PartDefinition left_brow_facet_r1 = head.addOrReplaceChild("left_brow_facet_r1", CubeListBuilder.create()
                    .texOffs(283, 0).addBox(-2F, -0.5F, -0.3F, 4F, 1F, 0.6F), PartPose.offsetAndRotation(2.1F, -5.55F, -4.7F, 0F, 0F, -0.4189F));
            PartDefinition left_cheek_rim_r1 = head.addOrReplaceChild("left_cheek_rim_r1", CubeListBuilder.create()
                    .texOffs(311, 0).addBox(-1.4F, -0.45F, -0.3F, 2.8F, 0.9F, 0.6F), PartPose.offsetAndRotation(2.1F, -2.7F, -4.6F, 0F, 0F, 0.3491F));
            PartDefinition right_brow_facet_r1 = head.addOrReplaceChild("right_brow_facet_r1", CubeListBuilder.create()
                    .texOffs(335, 0).addBox(-2F, -0.5F, -0.3F, 4F, 1F, 0.6F), PartPose.offsetAndRotation(-2.1F, -5.55F, -4.7F, 0F, 0F, 0.4189F));
            PartDefinition right_cheek_rim_r1 = head.addOrReplaceChild("right_cheek_rim_r1", CubeListBuilder.create()
                    .texOffs(363, 0).addBox(-1.4F, -0.45F, -0.3F, 2.8F, 0.9F, 0.6F), PartPose.offsetAndRotation(-2.1F, -2.7F, -4.6F, 0F, 0F, -0.3491F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.5F, -15.5F, -2F, 5F, 2.5F, 4.5F)
                .texOffs(0, 27).addBox(-6.5F, -13.4F, -3F, 13F, 12.9F, 6.5F)
                .texOffs(79, 27).addBox(4.1F, -13.5F, -5F, 3.9F, 12.5F, 9F)
                .texOffs(132, 27).addBox(-8F, -13.5F, -5F, 3.9F, 12.5F, 9F)
                .texOffs(185, 27).addBox(-8.4F, -13.9F, -5.5F, 16.8F, 2.9F, 2.5F)
                .texOffs(264, 27).addBox(-7.5F, -3F, -5.25F, 15F, 3F, 2.25F)
                .texOffs(333, 27).addBox(-4F, -11F, -4.5F, 8F, 8F, 1.5F)
                .texOffs(372, 27).addBox(-3F, -10F, -4.7F, 6F, 6F, 0.2F)
                .texOffs(397, 27).addBox(-2F, -9F, -4.9F, 4F, 4F, 0.2F)
                .texOffs(414, 27).addBox(-1F, -8F, -5.1F, 2F, 2F, 0.2F)
                .texOffs(423, 27).addBox(4F, -11.5F, -6F, 1.5F, 9F, 1.5F)
                .texOffs(436, 27).addBox(-5.5F, -11.5F, -6F, 1.5F, 9F, 1.5F)
                .texOffs(449, 27).addBox(-5.45F, -12F, -6.1F, 10.9F, 1.5F, 1.7F)
                .texOffs(0, 71).addBox(-5.45F, -4F, -6.1F, 10.9F, 2F, 1.7F)
                .texOffs(51, 71).addBox(6.5F, -14F, -6.25F, 2F, 10F, 1F)
                .texOffs(64, 71).addBox(6F, -10F, -7F, 3F, 2F, 1.5F)
                .texOffs(83, 71).addBox(7F, -9.5F, -7.3F, 1F, 1F, 0.3F)
                .texOffs(90, 71).addBox(6.25F, -3F, -6.5F, 2.5F, 2.5F, 1.25F)
                .texOffs(105, 71).addBox(-8.5F, -14F, -6.25F, 2F, 10F, 1F)
                .texOffs(118, 71).addBox(-9F, -10F, -7F, 3F, 2F, 1.5F)
                .texOffs(137, 71).addBox(-8F, -9.5F, -7.3F, 1F, 1F, 0.3F)
                .texOffs(144, 71).addBox(-8.75F, -3F, -6.5F, 2.5F, 2.5F, 1.25F)
                .texOffs(159, 71).addBox(-4.5F, -0.5F, -2.5F, 9F, 3F, 5.5F)
                .texOffs(218, 71).addBox(-6.5F, 0.5F, -3.5F, 13F, 1.5F, 7.5F)
                .texOffs(331, 71).addBox(-7.5F, -13F, 3.5F, 15F, 11.5F, 2F)
                .texOffs(400, 71).addBox(5.75F, -13.5F, 5.6F, 1.5F, 12F, 0.9F)
                .texOffs(411, 71).addBox(-7.25F, -13.5F, 5.6F, 1.5F, 12F, 0.9F)
                .texOffs(422, 71).addBox(-7.25F, -3F, 6.55F, 14.5F, 1.5F, 0.95F)
                .texOffs(0, 99).addBox(-7.25F, -13F, 6.55F, 14.5F, 1.5F, 0.95F), PartPose.offset(0F, 4.5F, 0F));
            PartDefinition waist_diamond_frame_r1 = body.addOrReplaceChild("waist_diamond_frame_r1", CubeListBuilder.create()
                    .texOffs(301, 71).addBox(-1.8F, -1.8F, -0.5F, 3.6F, 3.6F, 1F), PartPose.offsetAndRotation(0F, 1.7F, -5F, 0F, 0F, 0.7854F));
            PartDefinition waist_diamond_inlay_r1 = body.addOrReplaceChild("waist_diamond_inlay_r1", CubeListBuilder.create()
                    .texOffs(320, 71).addBox(-1.3F, -1.3F, -0.1F, 2.6F, 2.6F, 0.2F), PartPose.offsetAndRotation(0F, 1.7F, -5.6F, 0F, 0F, 0.7854F));
            PartDefinition rear_diamond_frame_r1 = body.addOrReplaceChild("rear_diamond_frame_r1", CubeListBuilder.create()
                    .texOffs(63, 99).addBox(-2F, -2F, -0.45F, 4F, 4F, 0.9F), PartPose.offsetAndRotation(0F, -7.5F, 6.05F, 0F, 0F, 0.7854F));
            PartDefinition rear_diamond_inlay_r1 = body.addOrReplaceChild("rear_diamond_inlay_r1", CubeListBuilder.create()
                    .texOffs(84, 99).addBox(-1.5F, -1.5F, -0.175F, 3F, 3F, 0.35F), PartPose.offsetAndRotation(0F, -7.5F, 6.675F, 0F, 0F, 0.7854F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(99, 99).addBox(-1.5F, -1.5F, -2F, 4F, 5F, 5F)
                .texOffs(136, 99).addBox(-2.5F, -2.5F, -4F, 6F, 9.5F, 8.5F)
                .texOffs(195, 99).addBox(-2F, -2F, -5F, 5F, 7F, 1F)
                .texOffs(220, 99).addBox(-2F, -4.5F, -2.5F, 5F, 2F, 5.5F)
                .texOffs(263, 99).addBox(-1.5F, -6F, -1.5F, 4F, 1.5F, 3.5F)
                .texOffs(294, 99).addBox(-0.5F, -7.5F, -1.5F, 3F, 1.5F, 3.5F)
                .texOffs(321, 99).addBox(0.75F, -9F, -1.5F, 1.5F, 1.5F, 3.5F)
                .texOffs(342, 99).addBox(-2.8F, 6F, -4.5F, 6.6F, 1.5F, 9.5F)
                .texOffs(407, 99).addBox(-1F, 7F, -2F, 3F, 4F, 4.5F)
                .texOffs(438, 99).addBox(-0.25F, 7.5F, -2.5F, 1.5F, 3.5F, 0.5F)
                .texOffs(447, 99).addBox(-1.75F, 11F, -3.5F, 5.5F, 9.9F, 8F)
                .texOffs(0, 136).addBox(-1.25F, 12F, -4.5F, 4.5F, 7F, 1F)
                .texOffs(23, 136).addBox(-2F, 10.5F, -5F, 6F, 1.5F, 10F)
                .texOffs(88, 136).addBox(-2F, 19.5F, -5F, 6F, 1.5F, 10F)
                .texOffs(153, 136).addBox(-0.5F, 20.5F, -2F, 3F, 2F, 4.5F)
                .texOffs(184, 136).addBox(-1.25F, 22F, -3F, 4.5F, 3.5F, 6F)
                .texOffs(227, 136).addBox(1.85F, 24.5F, -3.25F, 1.15F, 2F, 4.75F)
                .texOffs(252, 136).addBox(0.35F, 24.5F, -3.25F, 1.15F, 2F, 4.75F)
                .texOffs(277, 136).addBox(-1.15F, 24.5F, -3.25F, 1.15F, 2F, 4.75F), PartPose.offset(12.5F, -6.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(209, 166).addBox(-2.5F, -1.5F, -2F, 4F, 5F, 5F)
                .texOffs(246, 166).addBox(-3.5F, -2.5F, -4F, 6F, 9.5F, 8.5F)
                .texOffs(305, 166).addBox(-3F, -2F, -5F, 5F, 7F, 1F)
                .texOffs(330, 166).addBox(-3F, -4.5F, -2.5F, 5F, 2F, 5.5F)
                .texOffs(373, 166).addBox(-2.5F, -6F, -1.5F, 4F, 1.5F, 3.5F)
                .texOffs(404, 166).addBox(-2.5F, -7.5F, -1.5F, 3F, 1.5F, 3.5F)
                .texOffs(431, 166).addBox(-2.25F, -9F, -1.5F, 1.5F, 1.5F, 3.5F)
                .texOffs(0, 203).addBox(-3.8F, 6F, -4.5F, 6.6F, 1.5F, 9.5F)
                .texOffs(65, 203).addBox(-2F, 7F, -2F, 3F, 4F, 4.5F)
                .texOffs(96, 203).addBox(-1.25F, 7.5F, -2.5F, 1.5F, 3.5F, 0.5F)
                .texOffs(105, 203).addBox(-3.75F, 11F, -3.5F, 5.5F, 9.9F, 8F)
                .texOffs(160, 203).addBox(-3.25F, 12F, -4.5F, 4.5F, 7F, 1F)
                .texOffs(183, 203).addBox(-4F, 10.5F, -5F, 6F, 1.5F, 10F)
                .texOffs(248, 203).addBox(-4F, 19.5F, -5F, 6F, 1.5F, 10F)
                .texOffs(313, 203).addBox(-2.5F, 20.5F, -2F, 3F, 2F, 4.5F)
                .texOffs(344, 203).addBox(-3.25F, 22F, -3F, 4.5F, 3.5F, 6F)
                .texOffs(387, 203).addBox(-0.15F, 24.5F, -3.25F, 1.15F, 2F, 4.75F)
                .texOffs(412, 203).addBox(-1.65F, 24.5F, -3.25F, 1.15F, 2F, 4.75F)
                .texOffs(437, 203).addBox(-3.15F, 24.5F, -3.25F, 1.15F, 2F, 4.75F), PartPose.offset(-12.5F, -6.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(302, 136).addBox(-1.4F, -1F, -2F, 2.8F, 3.5F, 4.5F)
                .texOffs(333, 136).addBox(-2.75F, 0F, -3F, 5.5F, 8F, 6.5F)
                .texOffs(382, 136).addBox(-2.25F, 0.5F, -4F, 4.5F, 5.5F, 1F)
                .texOffs(405, 136).addBox(-3F, 7F, -4.25F, 6F, 2F, 8.25F)
                .texOffs(462, 136).addBox(-1.25F, 6.5F, -5F, 2.5F, 3F, 1F)
                .texOffs(0, 166).addBox(-2.25F, 8.5F, -3F, 4.5F, 6.4F, 6.5F)
                .texOffs(45, 166).addBox(-1.75F, 9.5F, -3.75F, 3.5F, 4.5F, 0.75F)
                .texOffs(64, 166).addBox(-2.75F, 13.5F, -4F, 5.5F, 1.5F, 8F)
                .texOffs(119, 166).addBox(-3F, 15F, -6F, 6F, 2.5F, 10.5F)
                .texOffs(186, 166).addBox(-2.5F, 15.5F, -6.5F, 5F, 1.5F, 0.5F), PartPose.offset(5F, 6.5F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(462, 203).addBox(-1.4F, -1F, -2F, 2.8F, 3.5F, 4.5F)
                .texOffs(0, 240).addBox(-2.75F, 0F, -3F, 5.5F, 8F, 6.5F)
                .texOffs(49, 240).addBox(-2.25F, 0.5F, -4F, 4.5F, 5.5F, 1F)
                .texOffs(72, 240).addBox(-3F, 7F, -4.25F, 6F, 2F, 8.25F)
                .texOffs(129, 240).addBox(-1.25F, 6.5F, -5F, 2.5F, 3F, 1F)
                .texOffs(144, 240).addBox(-2.25F, 8.5F, -3F, 4.5F, 6.4F, 6.5F)
                .texOffs(189, 240).addBox(-1.75F, 9.5F, -3.75F, 3.5F, 4.5F, 0.75F)
                .texOffs(208, 240).addBox(-2.75F, 13.5F, -4F, 5.5F, 1.5F, 8F)
                .texOffs(263, 240).addBox(-3F, 15F, -6F, 6F, 2.5F, 10.5F)
                .texOffs(330, 240).addBox(-2.5F, 15.5F, -6.5F, 5F, 1.5F, 0.5F), PartPose.offset(-5F, 6.5F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                DiamondGolemModel::createLayer, DiamondGolemModel::new);
    }
}
