package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/diamond_golem_f04.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class DiamondGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "diamond_golem_f04";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "diamond_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "diamond_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.DIAMOND;

    public DiamondGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-8F, -13F, -7F, 16F, 12F, 14F)
                .texOffs(100, 0).addBox(-8.2F, -14F, -6F, 16.4F, 2F, 12F)
                .texOffs(157, 0).addBox(-6F, -16F, -6F, 12F, 2F, 12F)
                .texOffs(206, 0).addBox(-3F, -18F, -6F, 6F, 2F, 12F)
                .texOffs(243, 0).addBox(-7F, -11F, -8.2F, 14F, 4F, 1.2F)
                .texOffs(274, 0).addBox(2.4F, -9.5F, -8.5F, 3.6F, 1F, 0.3F)
                .texOffs(302, 0).addBox(4.9F, -7F, -9.5F, 2.2F, 5F, 1.7F)
                .texOffs(326, 0).addBox(-6F, -9.5F, -8.5F, 3.6F, 1F, 0.3F)
                .texOffs(354, 0).addBox(-7.1F, -7F, -9.5F, 2.2F, 5F, 1.7F)
                .texOffs(378, 0).addBox(-1.5F, -13F, -10.5F, 3F, 12F, 2F)
                .texOffs(389, 0).addBox(-1F, -2F, -10F, 2F, 2F, 2F)
                .texOffs(398, 0).addBox(-1.5F, -13F, 7F, 3F, 10F, 1.5F)
                .texOffs(409, 0).addBox(-8.4F, -3F, 7.2F, 16.8F, 2F, 1.8F), PartPose.offset(0F, -44F, 0F));
            PartDefinition left_brow_facet_r1 = head.addOrReplaceChild("left_brow_facet_r1", CubeListBuilder.create()
                    .texOffs(283, 0).addBox(-4F, -1F, -0.6F, 8F, 2F, 1.2F), PartPose.offsetAndRotation(4.2F, -11.1F, -9.4F, 0F, 0F, -0.4189F));
            PartDefinition left_cheek_rim_r1 = head.addOrReplaceChild("left_cheek_rim_r1", CubeListBuilder.create()
                    .texOffs(311, 0).addBox(-2.8F, -0.9F, -0.6F, 5.6F, 1.8F, 1.2F), PartPose.offsetAndRotation(4.2F, -5.4F, -9.2F, 0F, 0F, 0.3491F));
            PartDefinition right_brow_facet_r1 = head.addOrReplaceChild("right_brow_facet_r1", CubeListBuilder.create()
                    .texOffs(335, 0).addBox(-4F, -1F, -0.6F, 8F, 2F, 1.2F), PartPose.offsetAndRotation(-4.2F, -11.1F, -9.4F, 0F, 0F, 0.4189F));
            PartDefinition right_cheek_rim_r1 = head.addOrReplaceChild("right_cheek_rim_r1", CubeListBuilder.create()
                    .texOffs(363, 0).addBox(-2.8F, -0.9F, -0.6F, 5.6F, 1.8F, 1.2F), PartPose.offsetAndRotation(-4.2F, -5.4F, -9.2F, 0F, 0F, -0.3491F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-5F, -31F, -4F, 10F, 5F, 9F)
                .texOffs(0, 27).addBox(-13F, -26.8F, -6F, 26F, 25.8F, 13F)
                .texOffs(79, 27).addBox(8.2F, -27F, -10F, 7.8F, 25F, 18F)
                .texOffs(132, 27).addBox(-16F, -27F, -10F, 7.8F, 25F, 18F)
                .texOffs(185, 27).addBox(-16.8F, -27.8F, -11F, 33.6F, 5.8F, 5F)
                .texOffs(264, 27).addBox(-15F, -6F, -10.5F, 30F, 6F, 4.5F)
                .texOffs(333, 27).addBox(-8F, -22F, -9F, 16F, 16F, 3F)
                .texOffs(372, 27).addBox(-6F, -20F, -9.4F, 12F, 12F, 0.4F)
                .texOffs(397, 27).addBox(-4F, -18F, -9.8F, 8F, 8F, 0.4F)
                .texOffs(414, 27).addBox(-2F, -16F, -10.2F, 4F, 4F, 0.4F)
                .texOffs(423, 27).addBox(8F, -23F, -12F, 3F, 18F, 3F)
                .texOffs(436, 27).addBox(-11F, -23F, -12F, 3F, 18F, 3F)
                .texOffs(449, 27).addBox(-10.9F, -24F, -12.2F, 21.8F, 3F, 3.4F)
                .texOffs(0, 71).addBox(-10.9F, -8F, -12.2F, 21.8F, 4F, 3.4F)
                .texOffs(51, 71).addBox(13F, -28F, -12.5F, 4F, 20F, 2F)
                .texOffs(64, 71).addBox(12F, -20F, -14F, 6F, 4F, 3F)
                .texOffs(83, 71).addBox(14F, -19F, -14.6F, 2F, 2F, 0.6F)
                .texOffs(90, 71).addBox(12.5F, -6F, -13F, 5F, 5F, 2.5F)
                .texOffs(105, 71).addBox(-17F, -28F, -12.5F, 4F, 20F, 2F)
                .texOffs(118, 71).addBox(-18F, -20F, -14F, 6F, 4F, 3F)
                .texOffs(137, 71).addBox(-16F, -19F, -14.6F, 2F, 2F, 0.6F)
                .texOffs(144, 71).addBox(-17.5F, -6F, -13F, 5F, 5F, 2.5F)
                .texOffs(159, 71).addBox(-9F, -1F, -5F, 18F, 6F, 11F)
                .texOffs(218, 71).addBox(-13F, 1F, -7F, 26F, 3F, 15F)
                .texOffs(331, 71).addBox(-15F, -26F, 7F, 30F, 23F, 4F)
                .texOffs(400, 71).addBox(11.5F, -27F, 11.2F, 3F, 24F, 1.8F)
                .texOffs(411, 71).addBox(-14.5F, -27F, 11.2F, 3F, 24F, 1.8F)
                .texOffs(422, 71).addBox(-14.5F, -6F, 13.1F, 29F, 3F, 1.9F)
                .texOffs(0, 99).addBox(-14.5F, -26F, 13.1F, 29F, 3F, 1.9F), PartPose.offset(0F, -15F, 0F));
            PartDefinition waist_diamond_frame_r1 = body.addOrReplaceChild("waist_diamond_frame_r1", CubeListBuilder.create()
                    .texOffs(301, 71).addBox(-3.6F, -3.6F, -1F, 7.2F, 7.2F, 2F), PartPose.offsetAndRotation(0F, 3.4F, -10F, 0F, 0F, 0.7854F));
            PartDefinition waist_diamond_inlay_r1 = body.addOrReplaceChild("waist_diamond_inlay_r1", CubeListBuilder.create()
                    .texOffs(320, 71).addBox(-2.6F, -2.6F, -0.2F, 5.2F, 5.2F, 0.4F), PartPose.offsetAndRotation(0F, 3.4F, -11.2F, 0F, 0F, 0.7854F));
            PartDefinition rear_diamond_frame_r1 = body.addOrReplaceChild("rear_diamond_frame_r1", CubeListBuilder.create()
                    .texOffs(63, 99).addBox(-4F, -4F, -0.9F, 8F, 8F, 1.8F), PartPose.offsetAndRotation(0F, -15F, 12.1F, 0F, 0F, 0.7854F));
            PartDefinition rear_diamond_inlay_r1 = body.addOrReplaceChild("rear_diamond_inlay_r1", CubeListBuilder.create()
                    .texOffs(84, 99).addBox(-3F, -3F, -0.35F, 6F, 6F, 0.7F), PartPose.offsetAndRotation(0F, -15F, 13.35F, 0F, 0F, 0.7854F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(99, 99).addBox(-3F, -3F, -4F, 8F, 10F, 10F)
                .texOffs(136, 99).addBox(-5F, -5F, -8F, 12F, 19F, 17F)
                .texOffs(195, 99).addBox(-4F, -4F, -10F, 10F, 14F, 2F)
                .texOffs(220, 99).addBox(-4F, -9F, -5F, 10F, 4F, 11F)
                .texOffs(263, 99).addBox(-3F, -12F, -3F, 8F, 3F, 7F)
                .texOffs(294, 99).addBox(-1F, -15F, -3F, 6F, 3F, 7F)
                .texOffs(321, 99).addBox(1.5F, -18F, -3F, 3F, 3F, 7F)
                .texOffs(342, 99).addBox(-5.6F, 12F, -9F, 13.2F, 3F, 19F)
                .texOffs(407, 99).addBox(-2F, 14F, -4F, 6F, 8F, 9F)
                .texOffs(438, 99).addBox(-0.5F, 15F, -5F, 3F, 7F, 1F)
                .texOffs(447, 99).addBox(-3.5F, 22F, -7F, 11F, 19.8F, 16F)
                .texOffs(0, 136).addBox(-2.5F, 24F, -9F, 9F, 14F, 2F)
                .texOffs(23, 136).addBox(-4F, 21F, -10F, 12F, 3F, 20F)
                .texOffs(88, 136).addBox(-4F, 39F, -10F, 12F, 3F, 20F)
                .texOffs(153, 136).addBox(-1F, 41F, -4F, 6F, 4F, 9F)
                .texOffs(184, 136).addBox(-2.5F, 44F, -6F, 9F, 7F, 12F)
                .texOffs(227, 136).addBox(3.7F, 49F, -6.5F, 2.3F, 4F, 9.5F)
                .texOffs(252, 136).addBox(0.7F, 49F, -6.5F, 2.3F, 4F, 9.5F)
                .texOffs(277, 136).addBox(-2.3F, 49F, -6.5F, 2.3F, 4F, 9.5F), PartPose.offset(25F, -37F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(209, 166).addBox(-5F, -3F, -4F, 8F, 10F, 10F)
                .texOffs(246, 166).addBox(-7F, -5F, -8F, 12F, 19F, 17F)
                .texOffs(305, 166).addBox(-6F, -4F, -10F, 10F, 14F, 2F)
                .texOffs(330, 166).addBox(-6F, -9F, -5F, 10F, 4F, 11F)
                .texOffs(373, 166).addBox(-5F, -12F, -3F, 8F, 3F, 7F)
                .texOffs(404, 166).addBox(-5F, -15F, -3F, 6F, 3F, 7F)
                .texOffs(431, 166).addBox(-4.5F, -18F, -3F, 3F, 3F, 7F)
                .texOffs(0, 203).addBox(-7.6F, 12F, -9F, 13.2F, 3F, 19F)
                .texOffs(65, 203).addBox(-4F, 14F, -4F, 6F, 8F, 9F)
                .texOffs(96, 203).addBox(-2.5F, 15F, -5F, 3F, 7F, 1F)
                .texOffs(105, 203).addBox(-7.5F, 22F, -7F, 11F, 19.8F, 16F)
                .texOffs(160, 203).addBox(-6.5F, 24F, -9F, 9F, 14F, 2F)
                .texOffs(183, 203).addBox(-8F, 21F, -10F, 12F, 3F, 20F)
                .texOffs(248, 203).addBox(-8F, 39F, -10F, 12F, 3F, 20F)
                .texOffs(313, 203).addBox(-5F, 41F, -4F, 6F, 4F, 9F)
                .texOffs(344, 203).addBox(-6.5F, 44F, -6F, 9F, 7F, 12F)
                .texOffs(387, 203).addBox(-0.3F, 49F, -6.5F, 2.3F, 4F, 9.5F)
                .texOffs(412, 203).addBox(-3.3F, 49F, -6.5F, 2.3F, 4F, 9.5F)
                .texOffs(437, 203).addBox(-6.3F, 49F, -6.5F, 2.3F, 4F, 9.5F), PartPose.offset(-25F, -37F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(302, 136).addBox(-2.8F, -2F, -4F, 5.6F, 7F, 9F)
                .texOffs(333, 136).addBox(-5.5F, 0F, -6F, 11F, 16F, 13F)
                .texOffs(382, 136).addBox(-4.5F, 1F, -8F, 9F, 11F, 2F)
                .texOffs(405, 136).addBox(-6F, 14F, -8.5F, 12F, 4F, 16.5F)
                .texOffs(462, 136).addBox(-2.5F, 13F, -10F, 5F, 6F, 2F)
                .texOffs(0, 166).addBox(-4.5F, 17F, -6F, 9F, 12.8F, 13F)
                .texOffs(45, 166).addBox(-3.5F, 19F, -7.5F, 7F, 9F, 1.5F)
                .texOffs(64, 166).addBox(-5.5F, 27F, -8F, 11F, 3F, 16F)
                .texOffs(119, 166).addBox(-6F, 30F, -12F, 12F, 5F, 21F)
                .texOffs(186, 166).addBox(-5F, 31F, -13F, 10F, 3F, 1F), PartPose.offset(10F, -11F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(462, 203).addBox(-2.8F, -2F, -4F, 5.6F, 7F, 9F)
                .texOffs(0, 240).addBox(-5.5F, 0F, -6F, 11F, 16F, 13F)
                .texOffs(49, 240).addBox(-4.5F, 1F, -8F, 9F, 11F, 2F)
                .texOffs(72, 240).addBox(-6F, 14F, -8.5F, 12F, 4F, 16.5F)
                .texOffs(129, 240).addBox(-2.5F, 13F, -10F, 5F, 6F, 2F)
                .texOffs(144, 240).addBox(-4.5F, 17F, -6F, 9F, 12.8F, 13F)
                .texOffs(189, 240).addBox(-3.5F, 19F, -7.5F, 7F, 9F, 1.5F)
                .texOffs(208, 240).addBox(-5.5F, 27F, -8F, 11F, 3F, 16F)
                .texOffs(263, 240).addBox(-6F, 30F, -12F, 12F, 5F, 21F)
                .texOffs(330, 240).addBox(-5F, 31F, -13F, 10F, 3F, 1F), PartPose.offset(-10F, -11F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                DiamondGolemModel::createLayer, DiamondGolemModel::new);
    }
}
