package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_farmer_male_p01.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinFarmerMaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_farmer_male_p01";

    public GoblinFarmerMaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-3.975F, -6.475F, -2.975F, 7.95F, 4.95F, 5.95F)
                .texOffs(57, 0).addBox(-3.5F, -6.5F, -3.5F, 7F, 1.5F, 1F)
                .texOffs(90, 0).addBox(3F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(117, 0).addBox(-4.5F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(144, 0).addBox(-2.975F, -1.975F, -2.975F, 5.95F, 1.95F, 5.45F)
                .texOffs(191, 0).addBox(-2.5F, -2.5F, -4F, 5F, 2F, 1.5F)
                .texOffs(218, 0).addBox(-1F, -4.5F, -4.5F, 2F, 2F, 1.5F)
                .texOffs(233, 0).addBox(-1.5F, -3.5F, -5.5F, 3F, 1F, 1.5F)
                .texOffs(0, 23).addBox(1F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(15, 23).addBox(-3.5F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(30, 23).addBox(1F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(43, 23).addBox(-3.5F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(56, 23).addBox(1F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(69, 23).addBox(-3.5F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(82, 23).addBox(-1.5F, -0.5F, -4F, 3F, 1F, 1F)
                .texOffs(99, 23).addBox(-1F, 0F, -4F, 2F, 1F, 1F)
                .texOffs(112, 23).addBox(4F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(133, 23).addBox(5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(152, 23).addBox(7F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(165, 23).addBox(5F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(176, 23).addBox(5.5F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(195, 23).addBox(5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(210, 23).addBox(-5.5F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(231, 23).addBox(-7.5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(0, 36).addBox(-8.5F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(13, 36).addBox(-7F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(24, 36).addBox(-7.5F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(43, 36).addBox(-6.5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(58, 36).addBox(-4F, -7.5F, -3F, 8F, 1.5F, 6.5F)
                .texOffs(117, 36).addBox(-4F, -7F, 2.5F, 8F, 3.5F, 1.5F)
                .texOffs(156, 36).addBox(2.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(167, 36).addBox(1F, -7.5F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(178, 36).addBox(-0.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(189, 36).addBox(-2F, -7.5F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(200, 36).addBox(-3.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(211, 36).addBox(3F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(224, 36).addBox(2F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(239, 36).addBox(0.5F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(0, 53).addBox(-1F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(15, 53).addBox(-2.5F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(28, 53).addBox(-4F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(169, 53).addBox(4F, -7F, -3.025F, 1F, 4.5F, 2.025F)
                .texOffs(182, 53).addBox(4F, -5.5F, -2.025F, 1.5F, 4F, 2.525F)
                .texOffs(199, 53).addBox(4F, -6.5F, 0.975F, 1F, 3.5F, 2.025F)
                .texOffs(212, 53).addBox(-5F, -7F, -3.025F, 1F, 4.5F, 2.025F)
                .texOffs(225, 53).addBox(-5.5F, -5.5F, -2.025F, 1.5F, 4F, 2.525F)
                .texOffs(242, 53).addBox(-5F, -6.5F, 0.975F, 1F, 3.5F, 2.025F)
                .texOffs(0, 256).addBox(-7F, -8.2F, -5.5F, 14F, 0.6F, 11F)
                .texOffs(101, 256).addBox(-4.75F, -10F, -3.75F, 9.5F, 1.95F, 8.25F)
                .texOffs(172, 256).addBox(-3.75F, -11.25F, -3F, 7.5F, 1.35F, 7F)
                .texOffs(0, 280).addBox(-2.75F, -11.75F, -2.25F, 5.5F, 0.6F, 5.5F)
                .texOffs(45, 280).addBox(-4.85F, -9.15F, -4.15F, 9.7F, 0.75F, 0.4F)
                .texOffs(86, 280).addBox(4.65F, -9.15F, -3.7F, 0.4F, 0.75F, 8.25F)
                .texOffs(121, 280).addBox(-5.05F, -9.15F, -3.7F, 0.4F, 0.75F, 8.25F)
                .texOffs(156, 280).addBox(-4.8F, -9.15F, 4.5F, 9.6F, 0.75F, 0.35F)
                .texOffs(197, 280).addBox(-5F, -9.25F, 4.85F, 1.5F, 0.9F, 0.5F), PartPose.offset(0F, 9.5F, 0F));
            PartDefinition top_lock_0_r1 = head.addOrReplaceChild("top_lock_0_r1", CubeListBuilder.create()
                    .texOffs(43, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(3.25F, -7.75F, -1.5F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_1_r1 = head.addOrReplaceChild("top_lock_1_r1", CubeListBuilder.create()
                    .texOffs(58, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(1.75F, -8.25F, -2F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_2_r1 = head.addOrReplaceChild("top_lock_2_r1", CubeListBuilder.create()
                    .texOffs(73, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(0.25F, -7.75F, -2F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_3_r1 = head.addOrReplaceChild("top_lock_3_r1", CubeListBuilder.create()
                    .texOffs(88, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(-1.25F, -8.25F, -1.5F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_4_r1 = head.addOrReplaceChild("top_lock_4_r1", CubeListBuilder.create()
                    .texOffs(103, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(-2.75F, -7.75F, -1.5F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_5_r1 = head.addOrReplaceChild("top_lock_5_r1", CubeListBuilder.create()
                    .texOffs(118, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(2.5F, -7.75F, 2F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_6_r1 = head.addOrReplaceChild("top_lock_6_r1", CubeListBuilder.create()
                    .texOffs(135, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(0F, -8.25F, 2F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_7_r1 = head.addOrReplaceChild("top_lock_7_r1", CubeListBuilder.create()
                    .texOffs(152, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(-2.5F, -7.75F, 1.5F, 0F, 0F, -0.2094F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 67).addBox(-4.475F, -6.975F, -1.975F, 8.95F, 6.45F, 4.45F)
                .texOffs(55, 67).addBox(-4.5F, -7F, 2F, 9F, 6F, 1F)
                .texOffs(114, 67).addBox(1.5F, -7F, -3F, 3F, 6F, 5F)
                .texOffs(147, 67).addBox(-4.5F, -7F, -3F, 3F, 6F, 5F)
                .texOffs(180, 67).addBox(-4.5F, -1.5F, -3F, 9F, 1F, 5.5F)
                .texOffs(239, 67).addBox(-1.5F, -6.5F, -2.5F, 3F, 5F, 0.5F)
                .texOffs(0, 91).addBox(0.5F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(15, 91).addBox(-3F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(30, 91).addBox(-1.475F, -7.975F, -0.975F, 2.95F, 1.45F, 1.95F)
                .texOffs(84, 91).addBox(-4.5F, -1.5F, -3.5F, 9F, 1.5F, 6.5F)
                .texOffs(182, 91).addBox(-4F, -1.5F, 3F, 8F, 1F, 1F)
                .texOffs(0, 115).addBox(4F, -1.5F, -2F, 2F, 2.5F, 3F)
                .texOffs(21, 115).addBox(4F, -2F, -2.5F, 2.5F, 1F, 4F)
                .texOffs(48, 115).addBox(-6.5F, -1.5F, -2F, 2.5F, 2.5F, 3.5F)
                .texOffs(73, 115).addBox(-6.5F, -2F, -2.5F, 2.5F, 1F, 4F)
                .texOffs(100, 115).addBox(-5.5F, -1.5F, -3F, 0.5F, 1.5F, 0.5F)
                .texOffs(105, 115).addBox(-6.5F, 0F, -2.5F, 1F, 2F, 1F)
                .texOffs(114, 115).addBox(-6.5F, -0.5F, -3F, 1F, 1.5F, 0.5F)
                .texOffs(121, 115).addBox(-3F, -1F, 1.5F, 6F, 1.5F, 1.5F)
                .texOffs(206, 280).addBox(-3.25F, -5.75F, -4.7F, 6.5F, 4F, 0.65F)
                .texOffs(235, 280).addBox(2F, -7.5F, -4.85F, 1F, 2.25F, 0.65F)
                .texOffs(0, 299).addBox(2F, -7.65F, -4.15F, 1F, 0.5F, 7.55F)
                .texOffs(35, 299).addBox(2F, -7.1F, 3.8F, 1F, 3.6F, 0.6F)
                .texOffs(42, 299).addBox(1.9F, -6F, -5.1F, 1.2F, 1.25F, 0.25F)
                .texOffs(47, 299).addBox(2.225F, -5.75F, -5.2F, 0.55F, 0.75F, 0.1F)
                .texOffs(50, 299).addBox(-3F, -7.5F, -4.85F, 1F, 2.25F, 0.65F)
                .texOffs(57, 299).addBox(-3F, -7.65F, -4.15F, 1F, 0.5F, 7.55F)
                .texOffs(92, 299).addBox(-3F, -7.1F, 3.8F, 1F, 3.6F, 0.6F)
                .texOffs(99, 299).addBox(-3.1F, -6F, -5.1F, 1.2F, 1.25F, 0.25F)
                .texOffs(104, 299).addBox(-2.775F, -5.75F, -5.2F, 0.55F, 0.75F, 0.1F)
                .texOffs(107, 299).addBox(-4F, -1.65F, -5.25F, 8F, 1.05F, 0.75F)
                .texOffs(144, 299).addBox(-4.5F, -1.75F, 4.45F, 9F, 1F, 0.6F)
                .texOffs(183, 299).addBox(-0.75F, -2F, 5.05F, 1.5F, 1.5F, 0.55F)
                .texOffs(192, 299).addBox(-1F, -1F, 5.05F, 0.75F, 2.5F, 0.45F)
                .texOffs(15, 316).addBox(-1.75F, -3.85F, -5.2F, 3.5F, 1.75F, 0.5F)
                .texOffs(32, 316).addBox(-1.8F, -4.1F, -5.4F, 3.6F, 0.5F, 0.2F), PartPose.offset(0F, 16F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(152, 115).addBox(-0.5F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(177, 115).addBox(-0.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(208, 115).addBox(-0.5F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(229, 115).addBox(-0.475F, 6.025F, -1.475F, 2.95F, 1.95F, 3.45F)
                .texOffs(0, 130).addBox(-1F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(9, 130).addBox(-0.5F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(5F, 9.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(39, 152).addBox(-2F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(64, 152).addBox(-2.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(95, 152).addBox(-2F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(116, 152).addBox(-2.475F, 6.025F, -1.475F, 2.95F, 1.95F, 3.45F)
                .texOffs(143, 152).addBox(0.5F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(152, 152).addBox(-2F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(-5F, 9.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(22, 130).addBox(-1.5F, -0.5F, -2F, 3.5F, 6F, 4.5F)
                .texOffs(55, 130).addBox(-1F, 1.5F, -2.5F, 2.5F, 2F, 0.5F)
                .texOffs(68, 130).addBox(-2F, 4F, -2.5F, 4.5F, 1F, 5F)
                .texOffs(107, 130).addBox(-1.5F, 5F, -2F, 3.5F, 2F, 4.5F)
                .texOffs(140, 130).addBox(-2F, 6F, -4F, 4.5F, 2F, 6F)
                .texOffs(183, 130).addBox(-2F, 7.5F, -4.5F, 4.5F, 0.5F, 7F)
                .texOffs(0, 152).addBox(-2F, 5.5F, -2.5F, 4.5F, 0.5F, 5F)
                .texOffs(199, 299).addBox(-1.9F, -0.55F, -4.25F, 3.65F, 4.05F, 0.6F)
                .texOffs(216, 299).addBox(-1.9F, 3F, -4.4F, 3.65F, 0.5F, 0.15F), PartPose.offset(2F, 16F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(165, 152).addBox(-2F, -0.5F, -2F, 3.5F, 6F, 4.5F)
                .texOffs(198, 152).addBox(-1.5F, 1.5F, -2.5F, 2.5F, 2F, 0.5F)
                .texOffs(211, 152).addBox(-2.5F, 4F, -2.5F, 4.5F, 1F, 5F)
                .texOffs(0, 174).addBox(-2F, 5F, -2F, 3.5F, 2F, 4.5F)
                .texOffs(33, 174).addBox(-2.5F, 6F, -4F, 4.5F, 2F, 6F)
                .texOffs(76, 174).addBox(-2.5F, 7.5F, -4.5F, 4.5F, 0.5F, 7F)
                .texOffs(123, 174).addBox(-2.5F, 5.5F, -2.5F, 4.5F, 0.5F, 5F)
                .texOffs(231, 299).addBox(-1.75F, -0.55F, -4.25F, 3.65F, 4.05F, 0.6F)
                .texOffs(0, 316).addBox(-1.75F, 3F, -4.4F, 3.65F, 0.5F, 0.15F), PartPose.offset(-2F, 16F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry.
     */
    public static GoblinBodies.Body body(boolean female, Optional<Profession> profession, String texture) {
        return new GoblinBodies.Body(female, profession, CROP, texture,
                GoblinFarmerMaleModel::createLayer, GoblinFarmerMaleModel::new);
    }
}
