package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_forester_female_p02.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinForesterFemaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_forester_female_p02";
    /** The texture this body samples. Rows in GoblinBodies name the class instead of retyping it. */
    public static final String TEXTURE = "goblin_forester_female";

    public GoblinForesterFemaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-8F, -13F, -6F, 16F, 10F, 12F)
                .texOffs(57, 0).addBox(-7F, -13F, -7F, 14F, 3F, 2F)
                .texOffs(90, 0).addBox(6F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(117, 0).addBox(-9F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(144, 0).addBox(-5F, -4F, -6F, 10F, 3F, 11F)
                .texOffs(187, 0).addBox(-4F, -5F, -8F, 8F, 3F, 3F)
                .texOffs(210, 0).addBox(-1F, -8F, -9F, 2F, 3F, 3F)
                .texOffs(221, 0).addBox(-2F, -7F, -10F, 4F, 2F, 2F)
                .texOffs(234, 0).addBox(2F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(0, 23).addBox(2F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(13, 23).addBox(2F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(28, 23).addBox(8F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(49, 23).addBox(10F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(68, 23).addBox(14F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(81, 23).addBox(10F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(92, 23).addBox(10F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(111, 23).addBox(10F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(126, 23).addBox(-7F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(139, 23).addBox(-7F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(152, 23).addBox(-7F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(167, 23).addBox(-11F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(188, 23).addBox(-15F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(207, 23).addBox(-17F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(220, 23).addBox(-14F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(231, 23).addBox(-14F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(0, 36).addBox(-13F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(15, 36).addBox(-8F, -15F, -6F, 16F, 3F, 13F)
                .texOffs(74, 36).addBox(-9F, -14F, 6F, 18F, 11F, 4F)
                .texOffs(119, 36).addBox(6F, -13F, 9F, 3F, 10F, 2F)
                .texOffs(130, 36).addBox(3F, -13F, 9F, 3F, 11F, 2F)
                .texOffs(141, 36).addBox(0F, -13F, 9F, 3F, 10F, 2F)
                .texOffs(152, 36).addBox(-3F, -13F, 9F, 3F, 11F, 2F)
                .texOffs(163, 36).addBox(-6F, -13F, 9F, 3F, 10F, 2F)
                .texOffs(174, 36).addBox(-9F, -13F, 9F, 3F, 9F, 2F)
                .texOffs(185, 36).addBox(5F, -15F, -9F, 3F, 5F, 3F)
                .texOffs(198, 36).addBox(3F, -14F, -10F, 3F, 5F, 4F)
                .texOffs(213, 36).addBox(0F, -15F, -9F, 3F, 4F, 3F)
                .texOffs(226, 36).addBox(-3F, -15F, -10F, 3F, 5F, 4F)
                .texOffs(241, 36).addBox(-6F, -14F, -9F, 3F, 5F, 3F)
                .texOffs(0, 53).addBox(-9F, -15F, -10F, 3F, 5F, 4F)
                .texOffs(15, 53).addBox(7F, -11F, -8F, 2F, 7F, 3F)
                .texOffs(26, 53).addBox(6F, -13F, -8F, 2F, 6F, 3F)
                .texOffs(37, 53).addBox(5F, -6F, -10F, 3F, 4F, 3F)
                .texOffs(50, 53).addBox(5F, -3F, -11F, 3F, 4F, 3F)
                .texOffs(63, 53).addBox(5F, 0F, -11F, 2F, 3F, 2F)
                .texOffs(72, 53).addBox(5F, -1F, -11F, 3F, 1F, 3F)
                .texOffs(85, 53).addBox(-9F, -11F, -8F, 2F, 7F, 3F)
                .texOffs(96, 53).addBox(-8F, -13F, -8F, 2F, 6F, 3F)
                .texOffs(107, 53).addBox(-8F, -6F, -10F, 3F, 4F, 3F)
                .texOffs(120, 53).addBox(-8F, -3F, -11F, 3F, 4F, 3F)
                .texOffs(133, 53).addBox(-7F, 0F, -11F, 2F, 3F, 2F)
                .texOffs(142, 53).addBox(-8F, -1F, -11F, 3F, 1F, 3F)
                .texOffs(155, 53).addBox(-6F, -17F, 7F, 12F, 6F, 5F)
                .texOffs(190, 53).addBox(-4F, -18F, 7F, 8F, 3F, 4F)
                .texOffs(215, 53).addBox(3F, -16F, 8F, 4F, 4F, 4F)
                .texOffs(232, 53).addBox(-7F, -16F, 8F, 4F, 4F, 4F)
                .texOffs(0, 65).addBox(-8F, -14F, -9F, 16F, 1F, 2F)
                .texOffs(37, 65).addBox(7F, -15F, -7F, 2F, 2F, 14F)
                .texOffs(70, 65).addBox(-9F, -15F, -7F, 2F, 2F, 14F)
                .texOffs(103, 65).addBox(-6F, -14F, 11F, 12F, 2F, 2F)
                .texOffs(132, 65).addBox(3F, -13F, 11F, 2F, 7F, 2F)
                .texOffs(141, 65).addBox(-5F, -13F, 11F, 2F, 8F, 2F), PartPose.offset(0F, -5F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(150, 65).addBox(-3F, -16F, -2F, 6F, 3F, 4F)
                .texOffs(171, 65).addBox(-8F, -14F, -4F, 16F, 12F, 9F)
                .texOffs(222, 65).addBox(1F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(237, 65).addBox(-6F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(0, 87).addBox(-8F, -11F, -6F, 16F, 9F, 12F)
                .texOffs(57, 87).addBox(-7F, -11F, -7F, 14F, 7F, 1F)
                .texOffs(88, 87).addBox(-7F, -11F, 6F, 14F, 7F, 1F)
                .texOffs(167, 87).addBox(-8F, -4F, -5F, 16F, 4F, 11F)
                .texOffs(0, 109).addBox(-9F, -3F, -7F, 18F, 3F, 14F)
                .texOffs(65, 109).addBox(-8F, -3F, -8F, 16F, 2F, 1F)
                .texOffs(100, 109).addBox(-2F, -4F, -9F, 4F, 4F, 1F)
                .texOffs(111, 109).addBox(-1F, -3F, -10F, 2F, 2F, 1F)
                .texOffs(118, 109).addBox(-7F, -1F, -4F, 14F, 11F, 9F)
                .texOffs(165, 109).addBox(-8F, 7F, -5F, 16F, 4F, 1F)
                .texOffs(200, 109).addBox(-8F, 7F, 5F, 16F, 4F, 1F)
                .texOffs(0, 130).addBox(9F, -3F, -6F, 4F, 6F, 7F)
                .texOffs(23, 130).addBox(9F, -4F, -7F, 5F, 3F, 9F)
                .texOffs(52, 130).addBox(11F, -2F, -8F, 2F, 2F, 1F)
                .texOffs(59, 130).addBox(5F, -2F, -9F, 3F, 3F, 1F)
                .texOffs(14, 256).addBox(2.5F, -14.6F, -8F, 3F, 1.1F, 17F)
                .texOffs(69, 256).addBox(-5.5F, -14.6F, -8F, 3F, 1.1F, 17F), PartPose.offset(0F, 8F, 0F));
            PartDefinition forester_front_strap_left_r1 = body.addOrReplaceChild("forester_front_strap_left_r1", CubeListBuilder.create()
                    .texOffs(0, 256).addBox(-1.25F, -7.5F, -0.5F, 2.5F, 15F, 1F), PartPose.offsetAndRotation(0F, -7.5F, -8.8F, 0F, 0F, -0.5585F));
            PartDefinition forester_back_strap_left_r1 = body.addOrReplaceChild("forester_back_strap_left_r1", CubeListBuilder.create()
                    .texOffs(7, 256).addBox(-1.25F, -7.5F, -0.55F, 2.5F, 15F, 1.1F), PartPose.offsetAndRotation(0F, -7.5F, 8.75F, 0F, 0F, 0.5585F));
            PartDefinition forester_front_strap_right_r1 = body.addOrReplaceChild("forester_front_strap_right_r1", CubeListBuilder.create()
                    .texOffs(55, 256).addBox(-1.25F, -7.5F, -0.5F, 2.5F, 15F, 1F), PartPose.offsetAndRotation(0F, -7.5F, -7.7F, 0F, 0F, 0.5585F));
            PartDefinition forester_back_strap_right_r1 = body.addOrReplaceChild("forester_back_strap_right_r1", CubeListBuilder.create()
                    .texOffs(62, 256).addBox(-1.25F, -7.5F, -0.55F, 2.5F, 15F, 1.1F), PartPose.offsetAndRotation(0F, -7.5F, 8.95F, 0F, 0F, -0.5585F));
            PartDefinition forester_chest_buckle_r1 = body.addOrReplaceChild("forester_chest_buckle_r1", CubeListBuilder.create()
                    .texOffs(110, 256).addBox(-2F, -2F, -0.4F, 4F, 4F, 0.8F), PartPose.offsetAndRotation(0F, -8F, -9.7F, 0F, 0F, -0.5585F));
            PartDefinition forester_chest_buckle_inset_r1 = body.addOrReplaceChild("forester_chest_buckle_inset_r1", CubeListBuilder.create()
                    .texOffs(121, 256).addBox(-1F, -1F, -0.2F, 2F, 2F, 0.4F), PartPose.offsetAndRotation(0F, -8F, -10.3F, 0F, 0F, -0.5585F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(68, 130).addBox(-1F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(93, 130).addBox(-1F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(124, 130).addBox(-1F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(145, 130).addBox(-1F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(172, 130).addBox(-2F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(181, 130).addBox(-1F, 4F, -5F, 5F, 1F, 1F)
                .texOffs(126, 256).addBox(-0.9F, 6F, -3.1F, 5.5F, 3F, 7.2F)
                .texOffs(153, 256).addBox(-1F, 8F, -3.3F, 5.7F, 1F, 7.6F)
                .texOffs(182, 256).addBox(0.85F, 6F, -3.9F, 2F, 2F, 0.6F)
                .texOffs(189, 256).addBox(1.45F, 6.5F, -4.2F, 0.8F, 1F, 0.3F), PartPose.offset(10F, -5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(129, 167).addBox(-4F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(154, 167).addBox(-5F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(185, 167).addBox(-4F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(206, 167).addBox(-5F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(233, 167).addBox(1F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(242, 167).addBox(-4F, 4F, -5F, 5F, 1F, 1F)
                .texOffs(192, 256).addBox(-4.6F, 6F, -3.1F, 5.5F, 3F, 7.2F)
                .texOffs(219, 256).addBox(-4.7F, 8F, -3.3F, 5.7F, 1F, 7.6F)
                .texOffs(248, 256).addBox(-2.85F, 6F, -3.9F, 2F, 2F, 0.6F)
                .texOffs(0, 275).addBox(-2.25F, 6.5F, -4.2F, 0.8F, 1F, 0.3F), PartPose.offset(-10F, -5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(194, 130).addBox(-3F, 0F, -3F, 6F, 12F, 7F)
                .texOffs(221, 130).addBox(-3F, 9F, -4F, 6F, 3F, 9F)
                .texOffs(0, 150).addBox(-4F, 10F, -4F, 8F, 4F, 9F)
                .texOffs(35, 150).addBox(-4F, 12F, -8F, 8F, 4F, 12F)
                .texOffs(76, 150).addBox(-4F, 15F, -9F, 8F, 1F, 14F)
                .texOffs(121, 150).addBox(-4F, 11F, -5F, 8F, 1F, 10F)
                .texOffs(158, 150).addBox(-4F, -1F, -7F, 10F, 6F, 2F)
                .texOffs(183, 150).addBox(-4F, 4F, -8F, 11F, 6F, 2F)
                .texOffs(210, 150).addBox(-4F, -1F, 5F, 10F, 6F, 2F)
                .texOffs(0, 167).addBox(-4F, 4F, 6F, 11F, 6F, 2F)
                .texOffs(27, 167).addBox(5F, 1F, -6F, 2F, 8F, 13F)
                .texOffs(58, 167).addBox(-4F, 9F, -6F, 10F, 3F, 1F)
                .texOffs(81, 167).addBox(-4F, 9F, 5F, 10F, 3F, 1F)
                .texOffs(104, 167).addBox(-4F, 9F, -9F, 11F, 1F, 1F)
                .texOffs(181, 209).addBox(2F, 0F, -10F, 2F, 9F, 1F)
                .texOffs(188, 209).addBox(2F, 7F, -11F, 2F, 2F, 1F), PartPose.offset(4F, 8F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 189).addBox(-3F, 0F, -3F, 6F, 12F, 7F)
                .texOffs(27, 189).addBox(-3F, 9F, -4F, 6F, 3F, 9F)
                .texOffs(58, 189).addBox(-4F, 10F, -4F, 8F, 4F, 9F)
                .texOffs(93, 189).addBox(-4F, 12F, -8F, 8F, 4F, 12F)
                .texOffs(134, 189).addBox(-4F, 15F, -9F, 8F, 1F, 14F)
                .texOffs(179, 189).addBox(-4F, 11F, -5F, 8F, 1F, 10F)
                .texOffs(216, 189).addBox(-6F, -1F, -7F, 10F, 6F, 2F)
                .texOffs(0, 209).addBox(-7F, 4F, -8F, 11F, 6F, 2F)
                .texOffs(27, 209).addBox(-6F, -1F, 5F, 10F, 6F, 2F)
                .texOffs(52, 209).addBox(-7F, 4F, 6F, 11F, 6F, 2F)
                .texOffs(79, 209).addBox(-7F, 1F, -6F, 2F, 8F, 13F)
                .texOffs(110, 209).addBox(-6F, 9F, -6F, 10F, 3F, 1F)
                .texOffs(133, 209).addBox(-6F, 9F, 5F, 10F, 3F, 1F)
                .texOffs(156, 209).addBox(-7F, 9F, -9F, 11F, 1F, 1F)
                .texOffs(195, 209).addBox(-4F, 4F, -9F, 5F, 4F, 1F)
                .texOffs(208, 209).addBox(-3F, 3F, -9F, 2F, 1F, 1F), PartPose.offset(-4F, 8F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry. The texture
     * comes from the class's own TEXTURE constant too, so a row cannot retype a wrong skin either. The
     * two flags are the row's, not the class's: ArtModelCheck holds each one against the crop's name.
     */
    public static GoblinBodies.Body body(boolean child, boolean female, Optional<Profession> profession) {
        return new GoblinBodies.Body(child, female, profession, CROP, TEXTURE,
                GoblinForesterFemaleModel::createLayer, GoblinForesterFemaleModel::new);
    }
}
