package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_child_girl_a.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinChildGirlModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_child_girl_a";
    /** The texture this body samples. Rows in GoblinBodies name the class instead of retyping it. */
    public static final String TEXTURE = "goblin_child_girl";

    public GoblinChildGirlModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-3.5F, -4F, -2.5F, 7F, 4.5F, 5F)
                .texOffs(49, 0).addBox(-3F, -4F, -3F, 6F, 1.5F, 0.5F)
                .texOffs(76, 0).addBox(2.5F, -1.5F, -2.5F, 1.5F, 2F, 4.5F)
                .texOffs(101, 0).addBox(-4F, -1.5F, -2.5F, 1.5F, 2F, 4.5F)
                .texOffs(126, 0).addBox(-2.5F, 0F, -2.5F, 5F, 1.5F, 4.5F)
                .texOffs(165, 0).addBox(-2F, -0.5F, -3.5F, 4F, 1.5F, 1F)
                .texOffs(186, 0).addBox(-1F, -1.5F, -4F, 2F, 1F, 1F)
                .texOffs(199, 0).addBox(0.5F, -3F, -3F, 2.5F, 2F, 0.5F)
                .texOffs(212, 0).addBox(0.5F, -3F, -3.5F, 2.5F, 0.5F, 0.5F)
                .texOffs(225, 0).addBox(0.5F, -3.5F, -4F, 2.5F, 0.5F, 1F)
                .texOffs(240, 0).addBox(3.5F, -2.5F, -1F, 1.5F, 2F, 2.5F)
                .texOffs(0, 20).addBox(4.5F, -2.5F, -1F, 2.5F, 2F, 2F)
                .texOffs(19, 20).addBox(6.5F, -2F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(32, 20).addBox(4.5F, -2F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(43, 20).addBox(4.5F, -2.5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(62, 20).addBox(-3F, -3F, -3F, 2.5F, 2F, 0.5F)
                .texOffs(75, 20).addBox(-3F, -3F, -3.5F, 2.5F, 0.5F, 0.5F)
                .texOffs(88, 20).addBox(-3F, -3.5F, -4F, 2.5F, 0.5F, 1F)
                .texOffs(103, 20).addBox(-5F, -2.5F, -1F, 1.5F, 2F, 2.5F)
                .texOffs(120, 20).addBox(-7F, -2.5F, -1F, 2.5F, 2F, 2F)
                .texOffs(139, 20).addBox(-8F, -2F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(152, 20).addBox(-6.5F, -2F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(163, 20).addBox(-6.5F, -2.5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(0, 63).addBox(-4F, -5F, -2.5F, 8F, 1.5F, 5.5F)
                .texOffs(55, 63).addBox(-4F, -4.5F, 2.5F, 8F, 4.5F, 1.5F)
                .texOffs(94, 63).addBox(2.5F, -5F, -4F, 1.5F, 2.5F, 1.5F)
                .texOffs(107, 63).addBox(1F, -5F, -4F, 1.5F, 2F, 1.5F)
                .texOffs(120, 63).addBox(-0.5F, -5F, -4F, 1.5F, 1.5F, 1.5F)
                .texOffs(133, 63).addBox(-2F, -5F, -4F, 1.5F, 2F, 1.5F)
                .texOffs(146, 63).addBox(-4F, -5F, -4F, 2F, 2.5F, 1.5F)
                .texOffs(161, 63).addBox(-2F, -5.5F, 3F, 4F, 1.5F, 2F)
                .texOffs(186, 63).addBox(-2.5F, -4.5F, 4.5F, 5F, 1F, 1F)
                .texOffs(211, 63).addBox(-4F, -4.5F, -4F, 8F, 0.5F, 1F)
                .texOffs(0, 78).addBox(3.5F, -5F, -2.5F, 1F, 1F, 5.5F)
                .texOffs(27, 78).addBox(-4.5F, -5F, -2.5F, 1F, 1F, 5.5F)
                .texOffs(54, 78).addBox(1F, -4F, 4.5F, 1F, 3.5F, 1F)
                .texOffs(63, 78).addBox(-2F, -4F, 4.5F, 1F, 4F, 1F)
                .texOffs(72, 78).addBox(3F, -3.5F, -3.5F, 1F, 3.5F, 1F)
                .texOffs(81, 78).addBox(2.5F, -1.5F, -4F, 1F, 3F, 1F)
                .texOffs(90, 78).addBox(2.5F, 0.5F, -4.5F, 1F, 0.5F, 1F)
                .texOffs(99, 78).addBox(2.5F, 1F, -4F, 1F, 1F, 1F)
                .texOffs(108, 78).addBox(-4F, -3.5F, -3.5F, 1F, 3.5F, 1F)
                .texOffs(117, 78).addBox(-3.5F, -1.5F, -4F, 1F, 3F, 1F)
                .texOffs(126, 78).addBox(-3.5F, 0.5F, -4.5F, 1F, 0.5F, 1F)
                .texOffs(135, 78).addBox(-3.5F, 1F, -4F, 1F, 1F, 1F), PartPose.offset(0F, 14F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(182, 20).addBox(-1.5F, -5.5F, -1F, 3F, 1.5F, 2F)
                .texOffs(203, 20).addBox(-2.5F, -4.5F, -1.5F, 5F, 4.5F, 3.5F)
                .texOffs(238, 20).addBox(0.5F, -5F, -2F, 2F, 1F, 1F)
                .texOffs(0, 37).addBox(-2.5F, -5F, -2F, 2F, 1F, 1F)
                .texOffs(144, 78).addBox(-3F, -3.5F, -2.5F, 6F, 3.5F, 5F)
                .texOffs(189, 78).addBox(-2.5F, -3.5F, -3F, 5F, 3F, 0.5F)
                .texOffs(212, 78).addBox(-2.5F, -3.5F, 2.5F, 5F, 3F, 0.5F)
                .texOffs(235, 78).addBox(2F, -5F, -3F, 1F, 2.5F, 1.5F)
                .texOffs(246, 78).addBox(-3F, -5F, -3F, 1F, 2.5F, 1.5F)
                .texOffs(0, 96).addBox(-3F, -0.5F, -2.5F, 6F, 1F, 5F)
                .texOffs(45, 96).addBox(-3.5F, -1F, -3F, 7F, 1F, 6F)
                .texOffs(98, 96).addBox(-1F, -1.5F, -3.5F, 2F, 2F, 0.5F)
                .texOffs(109, 96).addBox(-0.5F, -1F, -4F, 1F, 1F, 0.5F)
                .texOffs(116, 96).addBox(-3F, 0F, -2F, 6F, 2.5F, 4F), PartPose.offset(0F, 19F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(13, 37).addBox(-0.5F, -0.5F, -1.5F, 1.5F, 2.5F, 3F)
                .texOffs(32, 37).addBox(-0.5F, 1.5F, -2F, 1.5F, 0.5F, 4F)
                .texOffs(55, 37).addBox(-0.5F, 2F, -1F, 1.5F, 3F, 2F)
                .texOffs(70, 37).addBox(-1F, 4.5F, -1.5F, 2.5F, 1.5F, 3F)
                .texOffs(93, 37).addBox(-1F, 4.5F, -2F, 1F, 1F, 1F), PartPose.offset(4F, 14.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(0, 50).addBox(-1F, -0.5F, -1.5F, 1.5F, 2.5F, 3F)
                .texOffs(19, 50).addBox(-1F, 1.5F, -2F, 1.5F, 0.5F, 4F)
                .texOffs(42, 50).addBox(-1F, 2F, -1F, 1.5F, 3F, 2F)
                .texOffs(57, 50).addBox(-1.5F, 4.5F, -1.5F, 2.5F, 1.5F, 3F)
                .texOffs(80, 50).addBox(0.5F, 4.5F, -2F, 1F, 1F, 1F), PartPose.offset(-4F, 14.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(102, 37).addBox(-1F, 0F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(123, 37).addBox(-1.5F, 2.5F, -1.5F, 3.5F, 1.5F, 3.5F)
                .texOffs(152, 37).addBox(-1.5F, 3.5F, -3F, 3.5F, 1.5F, 4.5F)
                .texOffs(185, 37).addBox(-1.5F, 4.5F, -3.5F, 3.5F, 0.5F, 5.5F)
                .texOffs(222, 37).addBox(-1.5F, 2.5F, -2F, 3.5F, 0.5F, 4F)
                .texOffs(157, 96).addBox(-1.5F, -0.5F, -3F, 4F, 2.5F, 1F)
                .texOffs(178, 96).addBox(-1.5F, -0.5F, 2F, 4F, 2.5F, 1F)
                .texOffs(199, 96).addBox(-1.5F, 2F, -3.5F, 4F, 0.5F, 1F)
                .texOffs(220, 96).addBox(-1F, 2F, -2.5F, 3F, 1F, 0.5F)
                .texOffs(0, 111).addBox(2F, 0.5F, -2.5F, 1F, 2F, 5F)
                .texOffs(128, 111).addBox(0F, 0.5F, -3.5F, 2F, 1.5F, 0.5F), PartPose.offset(1.5F, 19F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(89, 50).addBox(-1.5F, 0F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(110, 50).addBox(-2F, 2.5F, -1.5F, 3.5F, 1.5F, 3.5F)
                .texOffs(139, 50).addBox(-2F, 3.5F, -3F, 3.5F, 1.5F, 4.5F)
                .texOffs(172, 50).addBox(-2F, 4.5F, -3.5F, 3.5F, 0.5F, 5.5F)
                .texOffs(209, 50).addBox(-2F, 2.5F, -2F, 3.5F, 0.5F, 4F)
                .texOffs(25, 111).addBox(-2.5F, -0.5F, -3F, 4F, 2.5F, 1F)
                .texOffs(46, 111).addBox(-2.5F, -0.5F, 2F, 4F, 2.5F, 1F)
                .texOffs(67, 111).addBox(-2.5F, 2F, -3.5F, 4F, 0.5F, 1F)
                .texOffs(88, 111).addBox(-2F, 2F, -2.5F, 3F, 1F, 0.5F)
                .texOffs(103, 111).addBox(-3F, 0.5F, -2.5F, 1F, 2F, 5F), PartPose.offset(-1.5F, 19F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry. The texture
     * comes from the class's own TEXTURE constant too, so a row cannot retype a wrong skin either. The
     * two flags are the row's, not the class's: ArtModelCheck holds each one against the crop's name.
     */
    public static GoblinBodies.Body body(boolean child, boolean female, Optional<Profession> profession) {
        return new GoblinBodies.Body(child, female, profession, CROP, TEXTURE,
                GoblinChildGirlModel::createLayer, GoblinChildGirlModel::new);
    }
}
