package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_artisan_male_p06.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinArtisanMaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_artisan_male_p06";
    /** The texture this body samples. Rows in GoblinBodies name the class instead of retyping it. */
    public static final String TEXTURE = "goblin_artisan_male";

    public GoblinArtisanMaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4F, -6.5F, -3F, 8F, 5F, 6F)
                .texOffs(57, 0).addBox(-3.5F, -6.5F, -3.5F, 7F, 1.5F, 1F)
                .texOffs(90, 0).addBox(3F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(117, 0).addBox(-4.5F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(144, 0).addBox(-3F, -2F, -3F, 6F, 2F, 5.5F)
                .texOffs(191, 0).addBox(-2.5F, -2.5F, -4F, 5F, 2F, 1.5F)
                .texOffs(218, 0).addBox(-1F, -4.5F, -4.5F, 2F, 2F, 1.5F)
                .texOffs(233, 0).addBox(-1.5F, -3.5F, -5.5F, 3F, 1F, 1.5F)
                .texOffs(0, 23).addBox(1F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(15, 23).addBox(-3.5F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(30, 23).addBox(1F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(43, 23).addBox(-3.5F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(56, 23).addBox(1F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(69, 23).addBox(-3.5F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(82, 23).addBox(-1.5F, -0.5F, -4F, 3F, 1F, 1F)
                .texOffs(99, 23).addBox(-1F, 0F, -4F, 2F, 1F, 1F)
                .texOffs(112, 23).addBox(4F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(133, 23).addBox(5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(152, 23).addBox(7F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(165, 23).addBox(5F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(176, 23).addBox(5.5F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(195, 23).addBox(5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(210, 23).addBox(-5.5F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(231, 23).addBox(-7.5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(0, 36).addBox(-8.5F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(13, 36).addBox(-7F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(24, 36).addBox(-7.5F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(43, 36).addBox(-6.5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(58, 36).addBox(-4F, -7.5F, -3F, 8F, 1.5F, 6.5F)
                .texOffs(117, 36).addBox(-4F, -7F, 2.5F, 8F, 3.5F, 1.5F)
                .texOffs(156, 36).addBox(2.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(167, 36).addBox(1F, -7.5F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(178, 36).addBox(-0.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(189, 36).addBox(-2F, -7.5F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(200, 36).addBox(-3.5F, -7F, 3.5F, 1.5F, 5F, 1F)
                .texOffs(211, 36).addBox(3F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(224, 36).addBox(2F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(239, 36).addBox(0.5F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(0, 53).addBox(-1F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(15, 53).addBox(-2.5F, -7.5F, -4.5F, 1.5F, 1.5F, 1.5F)
                .texOffs(28, 53).addBox(-4F, -7F, -5F, 1.5F, 1.5F, 2F)
                .texOffs(169, 53).addBox(4F, -7F, -3F, 1F, 4.5F, 2F)
                .texOffs(182, 53).addBox(4F, -5.5F, -2F, 1.5F, 4F, 2.5F)
                .texOffs(199, 53).addBox(4F, -6.5F, 1F, 1F, 3.5F, 2F)
                .texOffs(212, 53).addBox(-5F, -7F, -3F, 1F, 4.5F, 2F)
                .texOffs(225, 53).addBox(-5.5F, -5.5F, -2F, 1.5F, 4F, 2.5F)
                .texOffs(242, 53).addBox(-5F, -6.5F, 1F, 1F, 3.5F, 2F)
                .texOffs(0, 288).addBox(-4.75F, -7F, -5.1F, 9.5F, 1F, 0.5F)
                .texOffs(41, 288).addBox(4.75F, -7F, -4.6F, 0.5F, 1F, 9.1F)
                .texOffs(80, 288).addBox(-5.25F, -7F, -4.6F, 0.5F, 1F, 9.1F)
                .texOffs(119, 288).addBox(-4.75F, -7F, 4F, 9.5F, 1F, 0.5F)
                .texOffs(160, 288).addBox(1F, -7.85F, -5.7F, 2.7F, 2.25F, 0.6F)
                .texOffs(173, 288).addBox(1.5F, -7.4F, -6.2F, 1.7F, 1.4F, 0.5F)
                .texOffs(182, 288).addBox(-3.7F, -7.85F, -5.7F, 2.7F, 2.25F, 0.6F)
                .texOffs(195, 288).addBox(-3.2F, -7.4F, -6.2F, 1.7F, 1.4F, 0.5F)
                .texOffs(204, 288).addBox(-1F, -7F, -5.7F, 2F, 0.75F, 0.6F), PartPose.offset(0F, 9.5F, 0F));
            PartDefinition top_lock_0_r1 = head.addOrReplaceChild("top_lock_0_r1", CubeListBuilder.create()
                    .texOffs(43, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(3.25F, -7.75F, -1.5F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_1_r1 = head.addOrReplaceChild("top_lock_1_r1", CubeListBuilder.create()
                    .texOffs(58, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(1.75F, -8.25F, -2F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_2_r1 = head.addOrReplaceChild("top_lock_2_r1", CubeListBuilder.create()
                    .texOffs(73, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(0.25F, -7.75F, -2F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_3_r1 = head.addOrReplaceChild("top_lock_3_r1", CubeListBuilder.create()
                    .texOffs(88, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(-1.25F, -8.25F, -1.5F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_4_r1 = head.addOrReplaceChild("top_lock_4_r1", CubeListBuilder.create()
                    .texOffs(103, 53).addBox(-0.75F, -0.75F, -1F, 1.5F, 1.5F, 2F), PartPose.offsetAndRotation(-2.75F, -7.75F, -1.5F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_5_r1 = head.addOrReplaceChild("top_lock_5_r1", CubeListBuilder.create()
                    .texOffs(118, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(2.5F, -7.75F, 2F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_6_r1 = head.addOrReplaceChild("top_lock_6_r1", CubeListBuilder.create()
                    .texOffs(135, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(0F, -8.25F, 2F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_7_r1 = head.addOrReplaceChild("top_lock_7_r1", CubeListBuilder.create()
                    .texOffs(152, 53).addBox(-1F, -0.75F, -1F, 2F, 1.5F, 2F), PartPose.offsetAndRotation(-2.5F, -7.75F, 1.5F, 0F, 0F, -0.2094F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 67).addBox(-4.5F, -7F, -2F, 9F, 6.5F, 4.5F)
                .texOffs(55, 67).addBox(-4.5F, -7F, 2F, 9F, 6F, 1F)
                .texOffs(114, 67).addBox(1.5F, -7F, -3F, 3F, 6F, 5F)
                .texOffs(147, 67).addBox(-4.5F, -7F, -3F, 3F, 6F, 5F)
                .texOffs(180, 67).addBox(-4.5F, -1.5F, -3F, 9F, 1F, 5.5F)
                .texOffs(239, 67).addBox(-1.5F, -6.5F, -2.5F, 3F, 5F, 0.5F)
                .texOffs(0, 91).addBox(0.5F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(15, 91).addBox(-3F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(30, 91).addBox(-1.5F, -8F, -1F, 3F, 1.5F, 2F)
                .texOffs(121, 115).addBox(-3F, -1F, 1.5F, 6F, 1.5F, 1.5F)
                .texOffs(0, 256).addBox(-3.25F, -4.75F, -5F, 6.5F, 2.75F, 0.7F)
                .texOffs(29, 256).addBox(1F, -7.25F, -4.9F, 1F, 2.75F, 0.65F)
                .texOffs(36, 256).addBox(1F, -7.7F, -4.2F, 1F, 0.55F, 8.45F)
                .texOffs(75, 256).addBox(1F, -7.15F, 4.2F, 1F, 5.15F, 0.6F)
                .texOffs(82, 256).addBox(0.9F, -5.65F, -5.4F, 1.2F, 1.15F, 0.5F)
                .texOffs(89, 256).addBox(1.25F, -5.4F, -5.9F, 0.5F, 0.65F, 0.5F)
                .texOffs(94, 256).addBox(-2F, -7.25F, -4.9F, 1F, 2.75F, 0.65F)
                .texOffs(101, 256).addBox(-2F, -7.7F, -4.2F, 1F, 0.55F, 8.45F)
                .texOffs(140, 256).addBox(-2F, -7.15F, 4.2F, 1F, 5.15F, 0.6F)
                .texOffs(147, 256).addBox(-2.1F, -5.65F, -5.4F, 1.2F, 1.15F, 0.5F)
                .texOffs(154, 256).addBox(-1.75F, -5.4F, -5.9F, 0.5F, 0.65F, 0.5F)
                .texOffs(159, 256).addBox(-4.7F, -2F, -4.3F, 9.4F, 1.5F, 8.5F)
                .texOffs(0, 277).addBox(-4.7F, -2F, -5.4F, 9.4F, 1.5F, 1.1F)
                .texOffs(43, 277).addBox(-4.7F, -2F, 4.2F, 9.4F, 1.5F, 0.6F)
                .texOffs(84, 277).addBox(-1.25F, -2.5F, -5.9F, 2.5F, 2F, 0.5F)
                .texOffs(97, 277).addBox(-0.65F, -2F, -6.4F, 1.3F, 1F, 0.5F)
                .texOffs(182, 277).addBox(1.85F, -2.5F, -6.9F, 2.45F, 2.4F, 1.5F)
                .texOffs(199, 277).addBox(1.8F, -2.55F, -7.4F, 2.55F, 0.55F, 0.5F)
                .texOffs(212, 277).addBox(3.25F, -4F, -6.8F, 0.6F, 1.6F, 0.6F)
                .texOffs(217, 277).addBox(3.2F, -4.65F, -6.95F, 0.7F, 1.05F, 0.5F)
                .texOffs(222, 277).addBox(2.3F, -3.65F, -6.8F, 0.65F, 1.25F, 0.6F)
                .texOffs(227, 277).addBox(2.2F, -4.25F, -6.95F, 0.85F, 0.9F, 0.5F)
                .texOffs(234, 277).addBox(-0.75F, -2.5F, 4.8F, 1.5F, 1.5F, 0.6F), PartPose.offset(0F, 16F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(152, 115).addBox(-0.5F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(177, 115).addBox(-0.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(208, 115).addBox(-0.5F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(229, 115).addBox(-0.5F, 6F, -1.5F, 3F, 2F, 3.5F)
                .texOffs(0, 130).addBox(-1F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(9, 130).addBox(-0.5F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(5F, 9.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(39, 152).addBox(-2F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(64, 152).addBox(-2.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(95, 152).addBox(-2F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(116, 152).addBox(-2.5F, 6F, -1.5F, 3F, 2F, 3.5F)
                .texOffs(143, 152).addBox(0.5F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(152, 152).addBox(-2F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(-5F, 9.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(22, 130).addBox(-1.5F, -0.5F, -2F, 3.5F, 6F, 4.5F)
                .texOffs(55, 130).addBox(-1F, 1.5F, -2.5F, 2.5F, 2F, 0.5F)
                .texOffs(68, 130).addBox(-2F, 4F, -2.5F, 4.5F, 1F, 5F)
                .texOffs(107, 130).addBox(-1.5F, 5F, -2F, 3.5F, 2F, 4.5F)
                .texOffs(140, 130).addBox(-2F, 6F, -4F, 4.5F, 2F, 6F)
                .texOffs(183, 130).addBox(-2F, 7.5F, -4.5F, 4.5F, 0.5F, 7F)
                .texOffs(0, 152).addBox(-2F, 5.5F, -2.5F, 4.5F, 0.5F, 5F)
                .texOffs(106, 277).addBox(-1.875F, -0.6F, -5.1F, 3.875F, 4.6F, 0.6F)
                .texOffs(125, 277).addBox(-1.875F, 3.4F, -5.6F, 3.875F, 0.6F, 0.5F), PartPose.offset(2F, 16F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(165, 152).addBox(-2F, -0.5F, -2F, 3.5F, 6F, 4.5F)
                .texOffs(198, 152).addBox(-1.5F, 1.5F, -2.5F, 2.5F, 2F, 0.5F)
                .texOffs(211, 152).addBox(-2.5F, 4F, -2.5F, 4.5F, 1F, 5F)
                .texOffs(0, 174).addBox(-2F, 5F, -2F, 3.5F, 2F, 4.5F)
                .texOffs(33, 174).addBox(-2.5F, 6F, -4F, 4.5F, 2F, 6F)
                .texOffs(76, 174).addBox(-2.5F, 7.5F, -4.5F, 4.5F, 0.5F, 7F)
                .texOffs(123, 174).addBox(-2.5F, 5.5F, -2.5F, 4.5F, 0.5F, 5F)
                .texOffs(144, 277).addBox(-2F, -0.6F, -5.1F, 3.875F, 4.6F, 0.6F)
                .texOffs(163, 277).addBox(-2F, 3.4F, -5.6F, 3.875F, 0.6F, 0.5F), PartPose.offset(-2F, 16F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry. The texture
     * comes from the class's own TEXTURE constant too, so a row cannot retype a wrong skin either. The
     * two flags are the row's, not the class's: ArtModelCheck holds each one against the crop's name.
     */
    public static GoblinBodies.Body body(boolean child, boolean female, Optional<Profession> profession) {
        return new GoblinBodies.Body(child, female, profession, CROP, TEXTURE,
                GoblinArtisanMaleModel::createLayer, GoblinArtisanMaleModel::new);
    }
}
