package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_builder_female_p04.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinBuilderFemaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_builder_female_p04";

    public GoblinBuilderFemaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4F, -6.5F, -3F, 8F, 5F, 6F)
                .texOffs(57, 0).addBox(-3.5F, -6.5F, -3.5F, 7F, 1.5F, 1F)
                .texOffs(90, 0).addBox(3F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(117, 0).addBox(-4.5F, -4F, -3F, 1.5F, 2.5F, 5F)
                .texOffs(144, 0).addBox(-2.5F, -2F, -3F, 5F, 1.5F, 5.5F)
                .texOffs(187, 0).addBox(-2F, -2.5F, -4F, 4F, 1.5F, 1.5F)
                .texOffs(210, 0).addBox(-0.5F, -4F, -4.5F, 1F, 1.5F, 1.5F)
                .texOffs(221, 0).addBox(-1F, -3.5F, -5F, 2F, 1F, 1F)
                .texOffs(234, 0).addBox(1F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(0, 23).addBox(1F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(13, 23).addBox(1F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(28, 23).addBox(4F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(49, 23).addBox(5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(68, 23).addBox(7F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(81, 23).addBox(5F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(92, 23).addBox(5F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(111, 23).addBox(5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(126, 23).addBox(-3.5F, -5F, -3.5F, 2.5F, 2F, 0.5F)
                .texOffs(139, 23).addBox(-3.5F, -5F, -4F, 2.5F, 0.5F, 0.5F)
                .texOffs(152, 23).addBox(-3.5F, -5.5F, -4.5F, 2.5F, 0.5F, 1F)
                .texOffs(167, 23).addBox(-5.5F, -5F, -1.5F, 1.5F, 2.5F, 3.5F)
                .texOffs(188, 23).addBox(-7.5F, -5F, -1F, 2.5F, 2F, 2F)
                .texOffs(207, 23).addBox(-8.5F, -4.5F, -0.5F, 1.5F, 1F, 1.5F)
                .texOffs(220, 23).addBox(-7F, -4.5F, -1.5F, 2F, 1.5F, 0.5F)
                .texOffs(231, 23).addBox(-7F, -5F, -1.5F, 2F, 0.5F, 2.5F)
                .texOffs(0, 36).addBox(-6.5F, -3F, -1F, 1.5F, 0.5F, 2F)
                .texOffs(15, 36).addBox(-4F, -7.5F, -3F, 8F, 1.5F, 6.5F)
                .texOffs(74, 36).addBox(-4.5F, -7F, 3F, 9F, 5.5F, 2F)
                .texOffs(119, 36).addBox(3F, -6.5F, 4.5F, 1.5F, 5F, 1F)
                .texOffs(130, 36).addBox(1.5F, -6.5F, 4.5F, 1.5F, 5.5F, 1F)
                .texOffs(141, 36).addBox(0F, -6.5F, 4.5F, 1.5F, 5F, 1F)
                .texOffs(152, 36).addBox(-1.5F, -6.5F, 4.5F, 1.5F, 5.5F, 1F)
                .texOffs(163, 36).addBox(-3F, -6.5F, 4.5F, 1.5F, 5F, 1F)
                .texOffs(174, 36).addBox(-4.5F, -6.5F, 4.5F, 1.5F, 4.5F, 1F)
                .texOffs(185, 36).addBox(2.5F, -7.5F, -4.5F, 1.5F, 2.5F, 1.5F)
                .texOffs(198, 36).addBox(1.5F, -7F, -5F, 1.5F, 2.5F, 2F)
                .texOffs(213, 36).addBox(0F, -7.5F, -4.5F, 1.5F, 2F, 1.5F)
                .texOffs(226, 36).addBox(-1.5F, -7.5F, -5F, 1.5F, 2.5F, 2F)
                .texOffs(241, 36).addBox(-3F, -7F, -4.5F, 1.5F, 2.5F, 1.5F)
                .texOffs(0, 53).addBox(-4.5F, -7.5F, -5F, 1.5F, 2.5F, 2F)
                .texOffs(15, 53).addBox(3.5F, -5.5F, -4F, 1F, 3.5F, 1.5F)
                .texOffs(26, 53).addBox(3F, -6.5F, -4F, 1F, 3F, 1.5F)
                .texOffs(37, 53).addBox(2.5F, -3F, -5F, 1.5F, 2F, 1.5F)
                .texOffs(50, 53).addBox(2.5F, -1.5F, -5.5F, 1.5F, 2F, 1.5F)
                .texOffs(63, 53).addBox(2.5F, 0F, -5.5F, 1F, 1.5F, 1F)
                .texOffs(72, 53).addBox(2.5F, -0.5F, -5.5F, 1.5F, 0.5F, 1.5F)
                .texOffs(85, 53).addBox(-4.5F, -5.5F, -4F, 1F, 3.5F, 1.5F)
                .texOffs(96, 53).addBox(-4F, -6.5F, -4F, 1F, 3F, 1.5F)
                .texOffs(107, 53).addBox(-4F, -3F, -5F, 1.5F, 2F, 1.5F)
                .texOffs(120, 53).addBox(-4F, -1.5F, -5.5F, 1.5F, 2F, 1.5F)
                .texOffs(133, 53).addBox(-3.5F, 0F, -5.5F, 1F, 1.5F, 1F)
                .texOffs(142, 53).addBox(-4F, -0.5F, -5.5F, 1.5F, 0.5F, 1.5F)
                .texOffs(155, 53).addBox(-3F, -8.5F, 3.5F, 6F, 3F, 2.5F)
                .texOffs(190, 53).addBox(-2F, -9F, 3.5F, 4F, 1.5F, 2F)
                .texOffs(215, 53).addBox(1.5F, -8F, 4F, 2F, 2F, 2F)
                .texOffs(232, 53).addBox(-3.5F, -8F, 4F, 2F, 2F, 2F)
                .texOffs(0, 65).addBox(-4F, -7F, -4.5F, 8F, 0.5F, 1F)
                .texOffs(37, 65).addBox(3.5F, -7.5F, -3.5F, 1F, 1F, 7F)
                .texOffs(70, 65).addBox(-4.5F, -7.5F, -3.5F, 1F, 1F, 7F)
                .texOffs(103, 65).addBox(-3F, -7F, 5.5F, 6F, 1F, 1F)
                .texOffs(132, 65).addBox(1.5F, -6.5F, 5.5F, 1F, 3.5F, 1F)
                .texOffs(141, 65).addBox(-2.5F, -6.5F, 5.5F, 1F, 4F, 1F), PartPose.offset(0F, 9.5F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(150, 65).addBox(-1.5F, -8F, -1F, 3F, 1.5F, 2F)
                .texOffs(171, 65).addBox(-4F, -7F, -2F, 8F, 6F, 4.5F)
                .texOffs(222, 65).addBox(0.5F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(237, 65).addBox(-3F, -7.5F, -2.5F, 2.5F, 1F, 1F)
                .texOffs(0, 87).addBox(-4F, -5.5F, -3F, 8F, 4.5F, 6F)
                .texOffs(57, 87).addBox(-3.5F, -5.5F, -3.5F, 7F, 3.5F, 0.5F)
                .texOffs(88, 87).addBox(-3.5F, -5.5F, 3F, 7F, 3.5F, 0.5F)
                .texOffs(167, 87).addBox(-4F, -2F, -2.5F, 8F, 2F, 5.5F)
                .texOffs(118, 109).addBox(-3.5F, -0.5F, -2F, 7F, 5.5F, 4.5F)
                .texOffs(165, 109).addBox(-4F, 3.5F, -2.5F, 8F, 2F, 0.5F)
                .texOffs(200, 109).addBox(-4F, 3.5F, 2.5F, 8F, 2F, 0.5F)
                .texOffs(59, 130).addBox(2.5F, -1F, -4.5F, 1.5F, 1.5F, 0.5F)
                .texOffs(0, 256).addBox(-4.7F, -2F, -4.3F, 9.4F, 1.5F, 8.5F)
                .texOffs(73, 256).addBox(-4.7F, -2F, -4.8F, 9.4F, 1.5F, 0.5F)
                .texOffs(114, 256).addBox(-4.7F, -2F, 4.2F, 9.4F, 1.5F, 0.5F)
                .texOffs(155, 256).addBox(-1.4F, -2.5F, -5.4F, 2.8F, 2F, 0.6F)
                .texOffs(170, 256).addBox(-0.85F, -2F, -5.7F, 1.7F, 1F, 0.3F)
                .texOffs(179, 256).addBox(2.25F, -7.25F, -4.3F, 1F, 5.25F, 0.65F)
                .texOffs(186, 256).addBox(2.25F, -7.65F, -3.6F, 1F, 0.5F, 7.4F)
                .texOffs(221, 256).addBox(2.25F, -7.1F, 3.75F, 1F, 5.1F, 0.6F)
                .texOffs(228, 256).addBox(2.15F, -5.25F, -4.6F, 1.2F, 1.25F, 0.3F)
                .texOffs(235, 256).addBox(2.475F, -5F, -4.75F, 0.55F, 0.75F, 0.15F)
                .texOffs(238, 256).addBox(-3.25F, -7.25F, -4.3F, 1F, 5.25F, 0.65F)
                .texOffs(0, 277).addBox(-3.25F, -7.65F, -3.6F, 1F, 0.5F, 7.4F)
                .texOffs(35, 277).addBox(-3.25F, -7.1F, 3.75F, 1F, 5.1F, 0.6F)
                .texOffs(42, 277).addBox(-3.35F, -5.25F, -4.6F, 1.2F, 1.25F, 0.3F)
                .texOffs(49, 277).addBox(-3.025F, -5F, -4.75F, 0.55F, 0.75F, 0.15F)
                .texOffs(52, 277).addBox(1.8F, -2.25F, -6.5F, 2.7F, 2.15F, 1.65F)
                .texOffs(69, 277).addBox(1.75F, -2.5F, -6.7F, 2.8F, 0.5F, 1.9F)
                .texOffs(90, 277).addBox(2.8F, -2F, -6.85F, 0.7F, 1F, 0.15F)
                .texOffs(93, 277).addBox(2.7F, -3F, -5.15F, 0.9F, 0.75F, 0.9F)
                .texOffs(102, 277).addBox(-4.5F, -2.25F, -6.5F, 2.7F, 2.15F, 1.65F)
                .texOffs(119, 277).addBox(-4.55F, -2.5F, -6.7F, 2.8F, 0.5F, 1.9F)
                .texOffs(140, 277).addBox(-3.5F, -2F, -6.85F, 0.7F, 1F, 0.15F)
                .texOffs(143, 277).addBox(-3.6F, -3F, -5.15F, 0.9F, 0.75F, 0.9F)
                .texOffs(152, 277).addBox(-3.5F, -5.25F, -5.9F, 0.7F, 2.95F, 0.5F)
                .texOffs(157, 277).addBox(-3.55F, -5.3F, -6F, 0.8F, 0.55F, 0.1F)
                .texOffs(162, 277).addBox(3.15F, -4.1F, -5.8F, 0.75F, 1.75F, 0.6F)
                .texOffs(169, 277).addBox(2.9F, -5F, -6F, 1.25F, 1.25F, 0.5F)
                .texOffs(178, 277).addBox(-1F, -2.5F, 4.7F, 2F, 1F, 0.5F), PartPose.offset(0F, 16F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(68, 130).addBox(-0.5F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(93, 130).addBox(-0.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(124, 130).addBox(-0.5F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(145, 130).addBox(-0.5F, 6F, -1.5F, 3F, 2F, 3.5F)
                .texOffs(172, 130).addBox(-1F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(181, 130).addBox(-0.5F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(5F, 9.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(129, 167).addBox(-2F, -0.5F, -1.5F, 2.5F, 3.5F, 3.5F)
                .texOffs(154, 167).addBox(-2.5F, 2F, -2F, 3F, 1F, 4.5F)
                .texOffs(185, 167).addBox(-2F, 3F, -1F, 2.5F, 3.5F, 2.5F)
                .texOffs(206, 167).addBox(-2.5F, 6F, -1.5F, 3F, 2F, 3.5F)
                .texOffs(233, 167).addBox(0.5F, 6F, -2F, 1F, 1.5F, 1F)
                .texOffs(242, 167).addBox(-2F, 2F, -2.5F, 2.5F, 0.5F, 0.5F), PartPose.offset(-5F, 9.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(194, 130).addBox(-1.5F, 0F, -1.5F, 3F, 6F, 3.5F)
                .texOffs(221, 130).addBox(-1.5F, 4.5F, -2F, 3F, 1.5F, 4.5F)
                .texOffs(0, 150).addBox(-2F, 5F, -2F, 4F, 2F, 4.5F)
                .texOffs(35, 150).addBox(-2F, 6F, -4F, 4F, 2F, 6F)
                .texOffs(76, 150).addBox(-2F, 7.5F, -4.5F, 4F, 0.5F, 7F)
                .texOffs(121, 150).addBox(-2F, 5.5F, -2.5F, 4F, 0.5F, 5F)
                .texOffs(158, 150).addBox(-2F, -0.5F, -3.5F, 5F, 3F, 1F)
                .texOffs(183, 150).addBox(-2F, 2F, -4F, 5.5F, 3F, 1F)
                .texOffs(210, 150).addBox(-2F, -0.5F, 2.5F, 5F, 3F, 1F)
                .texOffs(0, 167).addBox(-2F, 2F, 3F, 5.5F, 3F, 1F)
                .texOffs(27, 167).addBox(2.5F, 0.5F, -3F, 1F, 4F, 6.5F)
                .texOffs(58, 167).addBox(-2F, 4.5F, -3F, 5F, 1.5F, 0.5F)
                .texOffs(81, 167).addBox(-2F, 4.5F, 2.5F, 5F, 1.5F, 0.5F)
                .texOffs(104, 167).addBox(-2F, 4.5F, -4.5F, 5.5F, 0.5F, 0.5F)
                .texOffs(181, 209).addBox(1F, 0F, -5F, 1F, 4.5F, 0.5F)
                .texOffs(188, 209).addBox(1F, 3.5F, -5.5F, 1F, 1F, 0.5F), PartPose.offset(2F, 16F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 189).addBox(-1.5F, 0F, -1.5F, 3F, 6F, 3.5F)
                .texOffs(27, 189).addBox(-1.5F, 4.5F, -2F, 3F, 1.5F, 4.5F)
                .texOffs(58, 189).addBox(-2F, 5F, -2F, 4F, 2F, 4.5F)
                .texOffs(93, 189).addBox(-2F, 6F, -4F, 4F, 2F, 6F)
                .texOffs(134, 189).addBox(-2F, 7.5F, -4.5F, 4F, 0.5F, 7F)
                .texOffs(179, 189).addBox(-2F, 5.5F, -2.5F, 4F, 0.5F, 5F)
                .texOffs(216, 189).addBox(-3F, -0.5F, -3.5F, 5F, 3F, 1F)
                .texOffs(0, 209).addBox(-3.5F, 2F, -4F, 5.5F, 3F, 1F)
                .texOffs(27, 209).addBox(-3F, -0.5F, 2.5F, 5F, 3F, 1F)
                .texOffs(52, 209).addBox(-3.5F, 2F, 3F, 5.5F, 3F, 1F)
                .texOffs(79, 209).addBox(-3.5F, 0.5F, -3F, 1F, 4F, 6.5F)
                .texOffs(110, 209).addBox(-3F, 4.5F, -3F, 5F, 1.5F, 0.5F)
                .texOffs(133, 209).addBox(-3F, 4.5F, 2.5F, 5F, 1.5F, 0.5F)
                .texOffs(156, 209).addBox(-3.5F, 4.5F, -4.5F, 5.5F, 0.5F, 0.5F)
                .texOffs(195, 209).addBox(-2F, 2F, -4.5F, 2.5F, 2F, 0.5F)
                .texOffs(208, 209).addBox(-1.5F, 1.5F, -4.5F, 1F, 0.5F, 0.5F), PartPose.offset(-2F, 16F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry.
     */
    public static GoblinBodies.Body body(boolean female, Optional<Profession> profession, String texture) {
        return new GoblinBodies.Body(female, profession, CROP, texture,
                GoblinBuilderFemaleModel::createLayer, GoblinBuilderFemaleModel::new);
    }
}
