package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_artisan_male_p06.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinArtisanMaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_artisan_male_p06";
    /** The texture this body samples. Rows in GoblinBodies name the class instead of retyping it. */
    public static final String TEXTURE = "goblin_artisan_male";

    public GoblinArtisanMaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-8F, -13F, -6F, 16F, 10F, 12F)
                .texOffs(57, 0).addBox(-7F, -13F, -7F, 14F, 3F, 2F)
                .texOffs(90, 0).addBox(6F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(117, 0).addBox(-9F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(144, 0).addBox(-6F, -4F, -6F, 12F, 4F, 11F)
                .texOffs(191, 0).addBox(-5F, -5F, -8F, 10F, 4F, 3F)
                .texOffs(218, 0).addBox(-2F, -9F, -9F, 4F, 4F, 3F)
                .texOffs(233, 0).addBox(-3F, -7F, -11F, 6F, 2F, 3F)
                .texOffs(0, 23).addBox(2F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(15, 23).addBox(-7F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(30, 23).addBox(2F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(43, 23).addBox(-7F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(56, 23).addBox(2F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(69, 23).addBox(-7F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(82, 23).addBox(-3F, -1F, -8F, 6F, 2F, 2F)
                .texOffs(99, 23).addBox(-2F, 0F, -8F, 4F, 2F, 2F)
                .texOffs(112, 23).addBox(8F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(133, 23).addBox(10F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(152, 23).addBox(14F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(165, 23).addBox(10F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(176, 23).addBox(11F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(195, 23).addBox(10F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(210, 23).addBox(-11F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(231, 23).addBox(-15F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(0, 36).addBox(-17F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(13, 36).addBox(-14F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(24, 36).addBox(-15F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(43, 36).addBox(-13F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(58, 36).addBox(-8F, -15F, -6F, 16F, 3F, 13F)
                .texOffs(117, 36).addBox(-8F, -14F, 5F, 16F, 7F, 3F)
                .texOffs(156, 36).addBox(5F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(167, 36).addBox(2F, -15F, 7F, 3F, 10F, 2F)
                .texOffs(178, 36).addBox(-1F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(189, 36).addBox(-4F, -15F, 7F, 3F, 10F, 2F)
                .texOffs(200, 36).addBox(-7F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(211, 36).addBox(6F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(224, 36).addBox(4F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(239, 36).addBox(1F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(0, 53).addBox(-2F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(15, 53).addBox(-5F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(28, 53).addBox(-8F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(169, 53).addBox(8F, -14F, -6F, 2F, 9F, 4F)
                .texOffs(182, 53).addBox(8F, -11F, -4F, 3F, 8F, 5F)
                .texOffs(199, 53).addBox(8F, -13F, 2F, 2F, 7F, 4F)
                .texOffs(212, 53).addBox(-10F, -14F, -6F, 2F, 9F, 4F)
                .texOffs(225, 53).addBox(-11F, -11F, -4F, 3F, 8F, 5F)
                .texOffs(242, 53).addBox(-10F, -13F, 2F, 2F, 7F, 4F)
                .texOffs(0, 288).addBox(-9.5F, -14F, -10.2F, 19F, 2F, 1F)
                .texOffs(41, 288).addBox(9.5F, -14F, -9.2F, 1F, 2F, 18.2F)
                .texOffs(80, 288).addBox(-10.5F, -14F, -9.2F, 1F, 2F, 18.2F)
                .texOffs(119, 288).addBox(-9.5F, -14F, 8F, 19F, 2F, 1F)
                .texOffs(160, 288).addBox(2F, -15.7F, -11.4F, 5.4F, 4.5F, 1.2F)
                .texOffs(173, 288).addBox(3F, -14.8F, -12.4F, 3.4F, 2.8F, 1F)
                .texOffs(182, 288).addBox(-7.4F, -15.7F, -11.4F, 5.4F, 4.5F, 1.2F)
                .texOffs(195, 288).addBox(-6.4F, -14.8F, -12.4F, 3.4F, 2.8F, 1F)
                .texOffs(204, 288).addBox(-2F, -14F, -11.4F, 4F, 1.5F, 1.2F), PartPose.offset(0F, -5F, 0F));
            PartDefinition top_lock_0_r1 = head.addOrReplaceChild("top_lock_0_r1", CubeListBuilder.create()
                    .texOffs(43, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(6.5F, -15.5F, -3F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_1_r1 = head.addOrReplaceChild("top_lock_1_r1", CubeListBuilder.create()
                    .texOffs(58, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(3.5F, -16.5F, -4F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_2_r1 = head.addOrReplaceChild("top_lock_2_r1", CubeListBuilder.create()
                    .texOffs(73, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(0.5F, -15.5F, -4F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_3_r1 = head.addOrReplaceChild("top_lock_3_r1", CubeListBuilder.create()
                    .texOffs(88, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(-2.5F, -16.5F, -3F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_4_r1 = head.addOrReplaceChild("top_lock_4_r1", CubeListBuilder.create()
                    .texOffs(103, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(-5.5F, -15.5F, -3F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_5_r1 = head.addOrReplaceChild("top_lock_5_r1", CubeListBuilder.create()
                    .texOffs(118, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(5F, -15.5F, 4F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_6_r1 = head.addOrReplaceChild("top_lock_6_r1", CubeListBuilder.create()
                    .texOffs(135, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(0F, -16.5F, 4F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_7_r1 = head.addOrReplaceChild("top_lock_7_r1", CubeListBuilder.create()
                    .texOffs(152, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(-5F, -15.5F, 3F, 0F, 0F, -0.2094F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 67).addBox(-9F, -14F, -4F, 18F, 13F, 9F)
                .texOffs(55, 67).addBox(-9F, -14F, 4F, 18F, 12F, 2F)
                .texOffs(114, 67).addBox(3F, -14F, -6F, 6F, 12F, 10F)
                .texOffs(147, 67).addBox(-9F, -14F, -6F, 6F, 12F, 10F)
                .texOffs(180, 67).addBox(-9F, -3F, -6F, 18F, 2F, 11F)
                .texOffs(239, 67).addBox(-3F, -13F, -5F, 6F, 10F, 1F)
                .texOffs(0, 91).addBox(1F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(15, 91).addBox(-6F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(30, 91).addBox(-3F, -16F, -2F, 6F, 3F, 4F)
                .texOffs(121, 115).addBox(-6F, -2F, 3F, 12F, 3F, 3F)
                .texOffs(0, 256).addBox(-6.5F, -9.5F, -10F, 13F, 5.5F, 1.4F)
                .texOffs(29, 256).addBox(2F, -14.5F, -9.8F, 2F, 5.5F, 1.3F)
                .texOffs(36, 256).addBox(2F, -15.4F, -8.4F, 2F, 1.1F, 16.9F)
                .texOffs(75, 256).addBox(2F, -14.3F, 8.4F, 2F, 10.3F, 1.2F)
                .texOffs(82, 256).addBox(1.8F, -11.3F, -10.8F, 2.4F, 2.3F, 1F)
                .texOffs(89, 256).addBox(2.5F, -10.8F, -11.8F, 1F, 1.3F, 1F)
                .texOffs(94, 256).addBox(-4F, -14.5F, -9.8F, 2F, 5.5F, 1.3F)
                .texOffs(101, 256).addBox(-4F, -15.4F, -8.4F, 2F, 1.1F, 16.9F)
                .texOffs(140, 256).addBox(-4F, -14.3F, 8.4F, 2F, 10.3F, 1.2F)
                .texOffs(147, 256).addBox(-4.2F, -11.3F, -10.8F, 2.4F, 2.3F, 1F)
                .texOffs(154, 256).addBox(-3.5F, -10.8F, -11.8F, 1F, 1.3F, 1F)
                .texOffs(159, 256).addBox(-9.4F, -4F, -8.6F, 18.8F, 3F, 17F)
                .texOffs(0, 277).addBox(-9.4F, -4F, -10.8F, 18.8F, 3F, 2.2F)
                .texOffs(43, 277).addBox(-9.4F, -4F, 8.4F, 18.8F, 3F, 1.2F)
                .texOffs(84, 277).addBox(-2.5F, -5F, -11.8F, 5F, 4F, 1F)
                .texOffs(97, 277).addBox(-1.3F, -4F, -12.8F, 2.6F, 2F, 1F)
                .texOffs(182, 277).addBox(3.7F, -5F, -13.8F, 4.9F, 4.8F, 3F)
                .texOffs(199, 277).addBox(3.6F, -5.1F, -14.8F, 5.1F, 1.1F, 1F)
                .texOffs(212, 277).addBox(6.5F, -8F, -13.6F, 1.2F, 3.2F, 1.2F)
                .texOffs(217, 277).addBox(6.4F, -9.3F, -13.9F, 1.4F, 2.1F, 1F)
                .texOffs(222, 277).addBox(4.6F, -7.3F, -13.6F, 1.3F, 2.5F, 1.2F)
                .texOffs(227, 277).addBox(4.4F, -8.5F, -13.9F, 1.7F, 1.8F, 1F)
                .texOffs(234, 277).addBox(-1.5F, -5F, 9.6F, 3F, 3F, 1.2F), PartPose.offset(0F, 8F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(152, 115).addBox(-1F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(177, 115).addBox(-1F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(208, 115).addBox(-1F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(229, 115).addBox(-1F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(0, 130).addBox(-2F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(9, 130).addBox(-1F, 4F, -5F, 5F, 1F, 1F), PartPose.offset(10F, -5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(39, 152).addBox(-4F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(64, 152).addBox(-5F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(95, 152).addBox(-4F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(116, 152).addBox(-5F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(143, 152).addBox(1F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(152, 152).addBox(-4F, 4F, -5F, 5F, 1F, 1F), PartPose.offset(-10F, -5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(22, 130).addBox(-3F, -1F, -4F, 7F, 12F, 9F)
                .texOffs(55, 130).addBox(-2F, 3F, -5F, 5F, 4F, 1F)
                .texOffs(68, 130).addBox(-4F, 8F, -5F, 9F, 2F, 10F)
                .texOffs(107, 130).addBox(-3F, 10F, -4F, 7F, 4F, 9F)
                .texOffs(140, 130).addBox(-4F, 12F, -8F, 9F, 4F, 12F)
                .texOffs(183, 130).addBox(-4F, 15F, -9F, 9F, 1F, 14F)
                .texOffs(0, 152).addBox(-4F, 11F, -5F, 9F, 1F, 10F)
                .texOffs(106, 277).addBox(-3.75F, -1.2F, -10.2F, 7.75F, 9.2F, 1.2F)
                .texOffs(125, 277).addBox(-3.75F, 6.8F, -11.2F, 7.75F, 1.2F, 1F), PartPose.offset(4F, 8F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(165, 152).addBox(-4F, -1F, -4F, 7F, 12F, 9F)
                .texOffs(198, 152).addBox(-3F, 3F, -5F, 5F, 4F, 1F)
                .texOffs(211, 152).addBox(-5F, 8F, -5F, 9F, 2F, 10F)
                .texOffs(0, 174).addBox(-4F, 10F, -4F, 7F, 4F, 9F)
                .texOffs(33, 174).addBox(-5F, 12F, -8F, 9F, 4F, 12F)
                .texOffs(76, 174).addBox(-5F, 15F, -9F, 9F, 1F, 14F)
                .texOffs(123, 174).addBox(-5F, 11F, -5F, 9F, 1F, 10F)
                .texOffs(144, 277).addBox(-4F, -1.2F, -10.2F, 7.75F, 9.2F, 1.2F)
                .texOffs(163, 277).addBox(-4F, 6.8F, -11.2F, 7.75F, 1.2F, 1F), PartPose.offset(-4F, 8F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry. The texture
     * comes from the class's own TEXTURE constant too, so a row cannot retype a wrong skin either. The
     * two flags are the row's, not the class's: ArtModelCheck holds each one against the crop's name.
     */
    public static GoblinBodies.Body body(boolean child, boolean female, Optional<Profession> profession) {
        return new GoblinBodies.Body(child, female, profession, CROP, TEXTURE,
                GoblinArtisanMaleModel::createLayer, GoblinArtisanMaleModel::new);
    }
}
