package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.colony.Profession;
import java.util.Optional;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models/goblin_sentry_male_p07.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoblinSentryMaleModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GoblinBodies name it instead of retyping it. */
    public static final String CROP = "goblin_sentry_male_p07";
    /** The texture this body samples. Rows in GoblinBodies name the class instead of retyping it. */
    public static final String TEXTURE = "goblin_sentry_male";

    public GoblinSentryMaleModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-8F, -13F, -6F, 16F, 10F, 12F)
                .texOffs(57, 0).addBox(-7F, -13F, -7F, 14F, 3F, 2F)
                .texOffs(90, 0).addBox(6F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(117, 0).addBox(-9F, -8F, -6F, 3F, 5F, 10F)
                .texOffs(144, 0).addBox(-6F, -4F, -6F, 12F, 4F, 11F)
                .texOffs(191, 0).addBox(-5F, -5F, -8F, 10F, 4F, 3F)
                .texOffs(218, 0).addBox(-2F, -9F, -9F, 4F, 4F, 3F)
                .texOffs(233, 0).addBox(-3F, -7F, -11F, 6F, 2F, 3F)
                .texOffs(0, 23).addBox(2F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(15, 23).addBox(-7F, -11F, -9F, 5F, 1F, 2F)
                .texOffs(30, 23).addBox(2F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(43, 23).addBox(-7F, -10F, -7F, 5F, 4F, 1F)
                .texOffs(56, 23).addBox(2F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(69, 23).addBox(-7F, -10F, -8F, 5F, 1F, 1F)
                .texOffs(82, 23).addBox(-3F, -1F, -8F, 6F, 2F, 2F)
                .texOffs(99, 23).addBox(-2F, 0F, -8F, 4F, 2F, 2F)
                .texOffs(112, 23).addBox(8F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(133, 23).addBox(10F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(152, 23).addBox(14F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(165, 23).addBox(10F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(176, 23).addBox(11F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(195, 23).addBox(10F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(210, 23).addBox(-11F, -10F, -3F, 3F, 5F, 7F)
                .texOffs(231, 23).addBox(-15F, -10F, -2F, 5F, 4F, 4F)
                .texOffs(0, 36).addBox(-17F, -9F, -1F, 3F, 2F, 3F)
                .texOffs(13, 36).addBox(-14F, -9F, -3F, 4F, 3F, 1F)
                .texOffs(24, 36).addBox(-15F, -10F, -3F, 4F, 1F, 5F)
                .texOffs(43, 36).addBox(-13F, -6F, -2F, 3F, 1F, 4F)
                .texOffs(58, 36).addBox(-8F, -15F, -6F, 16F, 3F, 13F)
                .texOffs(117, 36).addBox(-8F, -14F, 5F, 16F, 7F, 3F)
                .texOffs(156, 36).addBox(5F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(167, 36).addBox(2F, -15F, 7F, 3F, 10F, 2F)
                .texOffs(178, 36).addBox(-1F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(189, 36).addBox(-4F, -15F, 7F, 3F, 10F, 2F)
                .texOffs(200, 36).addBox(-7F, -14F, 7F, 3F, 10F, 2F)
                .texOffs(211, 36).addBox(6F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(224, 36).addBox(4F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(239, 36).addBox(1F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(0, 53).addBox(-2F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(15, 53).addBox(-5F, -15F, -9F, 3F, 3F, 3F)
                .texOffs(28, 53).addBox(-8F, -14F, -10F, 3F, 3F, 4F)
                .texOffs(169, 53).addBox(8F, -14F, -6F, 2F, 9F, 4F)
                .texOffs(182, 53).addBox(8F, -11F, -4F, 3F, 8F, 5F)
                .texOffs(199, 53).addBox(8F, -13F, 2F, 2F, 7F, 4F)
                .texOffs(212, 53).addBox(-10F, -14F, -6F, 2F, 9F, 4F)
                .texOffs(225, 53).addBox(-11F, -11F, -4F, 3F, 8F, 5F)
                .texOffs(242, 53).addBox(-10F, -13F, 2F, 2F, 7F, 4F)
                .texOffs(0, 256).addBox(-9.5F, -13.3F, -11F, 19F, 2F, 1F)
                .texOffs(41, 256).addBox(-2.6F, -15F, -12F, 5.2F, 4F, 1F)
                .texOffs(54, 256).addBox(-1.6F, -14F, -13F, 3.2F, 2F, 1F)
                .texOffs(63, 256).addBox(9.5F, -13.3F, -10F, 1F, 2F, 19F)
                .texOffs(104, 256).addBox(9F, -12.8F, -7F, 2F, 1F, 1F)
                .texOffs(111, 256).addBox(-10.5F, -13.3F, -10F, 1F, 2F, 19F)
                .texOffs(152, 256).addBox(-11F, -12.8F, -7F, 2F, 1F, 1F)
                .texOffs(159, 256).addBox(-9.5F, -13.3F, 9F, 19F, 2F, 1F)
                .texOffs(200, 256).addBox(-1F, -16F, -10F, 2F, 2.7F, 1F)
                .texOffs(207, 256).addBox(-1F, -16.5F, -9F, 2F, 1.5F, 17F)
                .texOffs(246, 256).addBox(-1F, -16F, 8F, 2F, 2.7F, 1F), PartPose.offset(0F, -5F, 0F));
            PartDefinition top_lock_0_r1 = head.addOrReplaceChild("top_lock_0_r1", CubeListBuilder.create()
                    .texOffs(43, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(6.5F, -15.5F, -3F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_1_r1 = head.addOrReplaceChild("top_lock_1_r1", CubeListBuilder.create()
                    .texOffs(58, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(3.5F, -16.5F, -4F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_2_r1 = head.addOrReplaceChild("top_lock_2_r1", CubeListBuilder.create()
                    .texOffs(73, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(0.5F, -15.5F, -4F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_3_r1 = head.addOrReplaceChild("top_lock_3_r1", CubeListBuilder.create()
                    .texOffs(88, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(-2.5F, -16.5F, -3F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_4_r1 = head.addOrReplaceChild("top_lock_4_r1", CubeListBuilder.create()
                    .texOffs(103, 53).addBox(-1.5F, -1.5F, -2F, 3F, 3F, 4F), PartPose.offsetAndRotation(-5.5F, -15.5F, -3F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_5_r1 = head.addOrReplaceChild("top_lock_5_r1", CubeListBuilder.create()
                    .texOffs(118, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(5F, -15.5F, 4F, 0F, 0F, -0.2094F));
            PartDefinition top_lock_6_r1 = head.addOrReplaceChild("top_lock_6_r1", CubeListBuilder.create()
                    .texOffs(135, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(0F, -16.5F, 4F, 0F, 0F, 0.2094F));
            PartDefinition top_lock_7_r1 = head.addOrReplaceChild("top_lock_7_r1", CubeListBuilder.create()
                    .texOffs(152, 53).addBox(-2F, -1.5F, -2F, 4F, 3F, 4F), PartPose.offsetAndRotation(-5F, -15.5F, 3F, 0F, 0F, -0.2094F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 67).addBox(-9F, -14F, -4F, 18F, 13F, 9F)
                .texOffs(55, 67).addBox(-9F, -14F, 4F, 18F, 12F, 2F)
                .texOffs(107, 67).addBox(-4F, -11F, 8F, 2F, 2F, 1F)
                .texOffs(114, 67).addBox(3F, -14F, -6F, 6F, 12F, 10F)
                .texOffs(147, 67).addBox(-9F, -14F, -6F, 6F, 12F, 10F)
                .texOffs(180, 67).addBox(-9F, -3F, -6F, 18F, 2F, 11F)
                .texOffs(239, 67).addBox(-3F, -13F, -5F, 6F, 10F, 1F)
                .texOffs(0, 91).addBox(1F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(15, 91).addBox(-6F, -15F, -5F, 5F, 2F, 2F)
                .texOffs(30, 91).addBox(-3F, -16F, -2F, 6F, 3F, 4F)
                .texOffs(62, 91).addBox(-1F, -10F, -9F, 5F, 5F, 1F)
                .texOffs(75, 91).addBox(0F, -9F, -10F, 3F, 3F, 1F)
                .texOffs(84, 91).addBox(-9F, -3F, -7F, 18F, 3F, 13F)
                .texOffs(147, 91).addBox(-8F, -3F, -8F, 16F, 2F, 1F)
                .texOffs(182, 91).addBox(-8F, -3F, 6F, 16F, 2F, 2F)
                .texOffs(219, 91).addBox(-3F, -4F, -9F, 6F, 4F, 1F)
                .texOffs(234, 91).addBox(-2F, -3F, -10F, 4F, 2F, 1F)
                .texOffs(0, 115).addBox(8F, -3F, -4F, 4F, 5F, 6F)
                .texOffs(21, 115).addBox(8F, -4F, -5F, 5F, 2F, 8F)
                .texOffs(48, 115).addBox(-13F, -3F, -4F, 5F, 5F, 7F)
                .texOffs(73, 115).addBox(-13F, -4F, -5F, 5F, 2F, 8F)
                .texOffs(100, 115).addBox(-11F, -3F, -6F, 1F, 3F, 1F)
                .texOffs(105, 115).addBox(-13F, 0F, -5F, 2F, 4F, 2F)
                .texOffs(114, 115).addBox(-13F, -1F, -6F, 2F, 3F, 1F)
                .texOffs(121, 115).addBox(-6F, -2F, 3F, 12F, 3F, 3F), PartPose.offset(0F, 8F, 0F));
            PartDefinition back_diagonal_strap_r1 = body.addOrReplaceChild("back_diagonal_strap_r1", CubeListBuilder.create()
                    .texOffs(96, 67).addBox(-1.5F, -10.5F, -1F, 3F, 21F, 2F), PartPose.offsetAndRotation(0.5F, -6.5F, 7F, 0F, 0F, -0.733F));
            PartDefinition front_diagonal_strap_r1 = body.addOrReplaceChild("front_diagonal_strap_r1", CubeListBuilder.create()
                    .texOffs(51, 91).addBox(-1.5F, -10.5F, -1F, 3F, 21F, 2F), PartPose.offsetAndRotation(0.5F, -6.5F, -7F, 0F, 0F, 0.733F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(152, 115).addBox(-1F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(177, 115).addBox(-1F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(208, 115).addBox(-1F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(229, 115).addBox(-1F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(0, 130).addBox(-2F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(9, 130).addBox(-1F, 4F, -5F, 5F, 1F, 1F)
                .texOffs(0, 278).addBox(-1F, -2.5F, -4.5F, 6.5F, 3.5F, 10F)
                .texOffs(33, 278).addBox(-1F, 0F, -5.5F, 6.5F, 1.5F, 1F)
                .texOffs(48, 278).addBox(-1F, 0F, 5.5F, 6.5F, 1.5F, 1F)
                .texOffs(63, 278).addBox(-0.5F, -3.5F, -3.5F, 5.5F, 1F, 8F)
                .texOffs(92, 278).addBox(1.75F, -1.5F, -5.5F, 1F, 1F, 1F)
                .texOffs(97, 278).addBox(-0.5F, 7F, -3.5F, 5.5F, 4.5F, 8F)
                .texOffs(126, 278).addBox(-1F, 7F, -4.5F, 6.5F, 1F, 10F)
                .texOffs(159, 278).addBox(-1F, 10.5F, -4.5F, 6.5F, 1F, 10F)
                .texOffs(192, 278).addBox(1.75F, 8.8F, -4.5F, 1F, 1F, 1F), PartPose.offset(10F, -5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(39, 152).addBox(-4F, -1F, -3F, 5F, 7F, 7F)
                .texOffs(64, 152).addBox(-5F, 4F, -4F, 6F, 2F, 9F)
                .texOffs(95, 152).addBox(-4F, 6F, -2F, 5F, 7F, 5F)
                .texOffs(116, 152).addBox(-5F, 12F, -3F, 6F, 4F, 7F)
                .texOffs(143, 152).addBox(1F, 12F, -4F, 2F, 3F, 2F)
                .texOffs(152, 152).addBox(-4F, 4F, -5F, 5F, 1F, 1F)
                .texOffs(0, 293).addBox(-5.5F, -2.5F, -4.5F, 6.5F, 3.5F, 10F)
                .texOffs(33, 293).addBox(-5.5F, 0F, -5.5F, 6.5F, 1.5F, 1F)
                .texOffs(48, 293).addBox(-5.5F, 0F, 5.5F, 6.5F, 1.5F, 1F)
                .texOffs(63, 293).addBox(-5F, -3.5F, -3.5F, 5.5F, 1F, 8F)
                .texOffs(92, 293).addBox(-2.75F, -1.5F, -5.5F, 1F, 1F, 1F)
                .texOffs(97, 293).addBox(-5F, 7F, -3.5F, 5.5F, 4.5F, 8F)
                .texOffs(126, 293).addBox(-5.5F, 7F, -4.5F, 6.5F, 1F, 10F)
                .texOffs(159, 293).addBox(-5.5F, 10.5F, -4.5F, 6.5F, 1F, 10F)
                .texOffs(192, 293).addBox(-2.75F, 8.8F, -4.5F, 1F, 1F, 1F), PartPose.offset(-10F, -5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(22, 130).addBox(-3F, -1F, -4F, 7F, 12F, 9F)
                .texOffs(55, 130).addBox(-2F, 3F, -5F, 5F, 4F, 1F)
                .texOffs(68, 130).addBox(-4F, 8F, -5F, 9F, 2F, 10F)
                .texOffs(107, 130).addBox(-3F, 10F, -4F, 7F, 4F, 9F)
                .texOffs(140, 130).addBox(-4F, 12F, -8F, 9F, 4F, 12F)
                .texOffs(183, 130).addBox(-4F, 15F, -9F, 9F, 1F, 14F)
                .texOffs(0, 152).addBox(-4F, 11F, -5F, 9F, 1F, 10F)
                .texOffs(197, 278).addBox(-3.5F, 5F, -7.5F, 7.5F, 4F, 1.5F)
                .texOffs(218, 278).addBox(-3.5F, 5F, -8.5F, 7.5F, 1F, 1F), PartPose.offset(4F, 8F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(165, 152).addBox(-4F, -1F, -4F, 7F, 12F, 9F)
                .texOffs(198, 152).addBox(-3F, 3F, -5F, 5F, 4F, 1F)
                .texOffs(211, 152).addBox(-5F, 8F, -5F, 9F, 2F, 10F)
                .texOffs(0, 174).addBox(-4F, 10F, -4F, 7F, 4F, 9F)
                .texOffs(33, 174).addBox(-5F, 12F, -8F, 9F, 4F, 12F)
                .texOffs(76, 174).addBox(-5F, 15F, -9F, 9F, 1F, 14F)
                .texOffs(123, 174).addBox(-5F, 11F, -5F, 9F, 1F, 10F)
                .texOffs(197, 293).addBox(-4F, 5F, -7.5F, 7.5F, 4F, 1.5F)
                .texOffs(218, 293).addBox(-4F, 5F, -8.5F, 7.5F, 1F, 1F), PartPose.offset(-4F, 8F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GoblinBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step -- a row can no longer pair one class's crop with another's geometry. The texture
     * comes from the class's own TEXTURE constant too, so a row cannot retype a wrong skin either. The
     * two flags are the row's, not the class's: ArtModelCheck holds each one against the crop's name.
     */
    public static GoblinBodies.Body body(boolean child, boolean female, Optional<Profession> profession) {
        return new GoblinBodies.Body(child, female, profession, CROP, TEXTURE,
                GoblinSentryMaleModel::createLayer, GoblinSentryMaleModel::new);
    }
}
