package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/gold_golem_f03.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoldGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "gold_golem_f03";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "gold_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "gold_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.GOLD;

    public GoldGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-4F, -8.5F, -3.5F, 8F, 7.5F, 7F)
                .texOffs(100, 0).addBox(-4.5F, -9F, -3.5F, 9F, 2F, 7.5F)
                .texOffs(167, 0).addBox(-1.5F, -9F, -4F, 3F, 4F, 0.5F)
                .texOffs(182, 0).addBox(1.5F, -7F, -4.5F, 3F, 1.5F, 1.5F)
                .texOffs(201, 0).addBox(-4.5F, -7F, -4.5F, 3F, 1.5F, 1.5F)
                .texOffs(220, 0).addBox(-3.5F, -5.5F, -4F, 7F, 1.5F, 0.5F)
                .texOffs(251, 0).addBox(1F, -5F, -4.15F, 2F, 0.5F, 0.15F)
                .texOffs(260, 0).addBox(-3F, -5F, -4.15F, 2F, 0.5F, 0.15F)
                .texOffs(269, 0).addBox(1.5F, -4F, -4.5F, 2.5F, 3.5F, 1.5F)
                .texOffs(286, 0).addBox(-4F, -4F, -4.5F, 2.5F, 3.5F, 1.5F)
                .texOffs(303, 0).addBox(-1F, -4F, -4.25F, 2F, 3F, 0.75F)
                .texOffs(316, 0).addBox(-4.15F, -6.5F, 3.5F, 8.3F, 1.5F, 1F)
                .texOffs(355, 0).addBox(2.5F, -6.75F, -4.75F, 1F, 1F, 0.25F)
                .texOffs(360, 0).addBox(-3.5F, -6.75F, -4.75F, 1F, 1F, 0.25F), PartPose.offset(0F, -10F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.5F, -16F, -2F, 5F, 3F, 4.5F)
                .texOffs(365, 0).addBox(-7.5F, -14F, -3.5F, 15F, 14F, 7.5F)
                .texOffs(0, 44).addBox(4.5F, -13F, -5.5F, 4.5F, 12.5F, 10F)
                .texOffs(59, 44).addBox(-9F, -13F, -5.5F, 4.5F, 12.5F, 10F)
                .texOffs(118, 44).addBox(-9.4F, -14.5F, -6F, 18.8F, 3.5F, 3F)
                .texOffs(207, 44).addBox(-8.5F, -3F, -6F, 17F, 3F, 3F)
                .texOffs(288, 44).addBox(-4.5F, -11F, -5F, 9F, 7.5F, 1.5F)
                .texOffs(331, 44).addBox(-3.5F, -10F, -5.15F, 7F, 5.5F, 0.15F)
                .texOffs(360, 44).addBox(-2.5F, -9F, -5.275F, 5F, 3.5F, 0.125F)
                .texOffs(381, 44).addBox(-1F, -8F, -5.4F, 2F, 1.5F, 0.125F)
                .texOffs(390, 44).addBox(4F, -11.5F, -6.5F, 1.5F, 8.5F, 1.5F)
                .texOffs(403, 44).addBox(-5.5F, -11.5F, -6.5F, 1.5F, 8.5F, 1.5F)
                .texOffs(416, 44).addBox(-5.5F, -11.5F, -6.575F, 11F, 1.5F, 1.575F)
                .texOffs(0, 90).addBox(-5.5F, -4.5F, -6.575F, 11F, 2F, 1.575F)
                .texOffs(51, 90).addBox(6.5F, -14.5F, -6.5F, 3F, 6F, 1.5F)
                .texOffs(70, 90).addBox(6F, -11.5F, -7.5F, 4F, 3F, 1.5F)
                .texOffs(93, 90).addBox(6.5F, -4F, -7F, 3F, 2.5F, 1.5F)
                .texOffs(112, 90).addBox(7.5F, -10.5F, -7.75F, 1F, 1F, 0.25F)
                .texOffs(117, 90).addBox(7.5F, -3.25F, -7.25F, 1F, 1F, 0.25F)
                .texOffs(122, 90).addBox(-9.5F, -14.5F, -6.5F, 3F, 6F, 1.5F)
                .texOffs(141, 90).addBox(-10F, -11.5F, -7.5F, 4F, 3F, 1.5F)
                .texOffs(164, 90).addBox(-9.5F, -4F, -7F, 3F, 2.5F, 1.5F)
                .texOffs(183, 90).addBox(-8.5F, -10.5F, -7.75F, 1F, 1F, 0.25F)
                .texOffs(188, 90).addBox(-8.5F, -3.25F, -7.25F, 1F, 1F, 0.25F)
                .texOffs(193, 90).addBox(4.25F, -4F, -6.75F, 1F, 1F, 0.25F)
                .texOffs(198, 90).addBox(4.25F, -11F, -6.75F, 1F, 1F, 0.25F)
                .texOffs(203, 90).addBox(-5.25F, -4F, -6.75F, 1F, 1F, 0.25F)
                .texOffs(208, 90).addBox(-5.25F, -11F, -6.75F, 1F, 1F, 0.25F)
                .texOffs(213, 90).addBox(-5.5F, -0.5F, -3F, 11F, 3F, 6.5F)
                .texOffs(284, 90).addBox(-7F, 0F, -4F, 14F, 2F, 8.5F)
                .texOffs(375, 90).addBox(-3F, 0.5F, -5.5F, 6F, 4.5F, 2.5F)
                .texOffs(410, 90).addBox(-1F, 1F, -5.65F, 2F, 3.5F, 0.15F)
                .texOffs(419, 90).addBox(-0.5F, 1.5F, -5.75F, 1F, 2.5F, 0.1F)
                .texOffs(424, 90).addBox(2F, -13.5F, 4F, 6.5F, 12F, 2F)
                .texOffs(459, 90).addBox(-8.5F, -13.5F, 4F, 6.5F, 12F, 2F)
                .texOffs(494, 90).addBox(-1.5F, -13.5F, 4.5F, 3F, 13F, 1.5F)
                .texOffs(0, 120).addBox(-0.5F, -12.5F, 6F, 1F, 10.5F, 0.125F)
                .texOffs(5, 120).addBox(-9F, -4F, 6F, 18F, 2F, 1.5F)
                .texOffs(84, 120).addBox(6F, -3.5F, 7.5F, 1F, 1F, 0.25F)
                .texOffs(89, 120).addBox(-7F, -3.5F, 7.5F, 1F, 1F, 0.25F)
                .texOffs(94, 120).addBox(-9F, -13F, 6F, 18F, 2F, 1.5F)
                .texOffs(173, 120).addBox(6F, -12.5F, 7.5F, 1F, 1F, 0.25F)
                .texOffs(178, 120).addBox(-7F, -12.5F, 7.5F, 1F, 1F, 0.25F), PartPose.offset(0F, 4.5F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(183, 120).addBox(-1.5F, -1.5F, -3F, 4F, 5F, 6.5F)
                .texOffs(226, 120).addBox(-3F, -3F, -4.5F, 7F, 10.5F, 9.5F)
                .texOffs(293, 120).addBox(-3.5F, -4F, -5F, 8F, 2.5F, 10.5F)
                .texOffs(368, 120).addBox(-2.5F, -1.5F, -5.5F, 6F, 6F, 1F)
                .texOffs(397, 120).addBox(-3.5F, 6F, -5F, 8F, 2F, 10.5F)
                .texOffs(472, 120).addBox(-1.5F, 7.5F, -2.5F, 4F, 4F, 5.5F)
                .texOffs(0, 161).addBox(-0.5F, 8F, -3F, 2F, 3.5F, 0.5F)
                .texOffs(11, 161).addBox(0F, 8.5F, -3.1F, 1F, 2.5F, 0.1F)
                .texOffs(16, 161).addBox(-2F, 10.5F, -4F, 6.5F, 10F, 9F)
                .texOffs(79, 161).addBox(-2.5F, 9.5F, -4.5F, 7.5F, 2.5F, 10F)
                .texOffs(150, 161).addBox(-1.5F, 12F, -5.5F, 5.5F, 7F, 1.5F)
                .texOffs(179, 161).addBox(-2.5F, 15F, -6F, 7.5F, 2F, 12F)
                .texOffs(258, 161).addBox(0F, 14.5F, -7F, 2.5F, 3F, 1.5F)
                .texOffs(275, 161).addBox(0.75F, 15.5F, -7.25F, 1F, 1F, 0.25F)
                .texOffs(280, 161).addBox(-1F, 19.5F, -3F, 4.5F, 2.5F, 6.5F)
                .texOffs(325, 161).addBox(-1.5F, 21F, -3.5F, 5.5F, 4F, 7.5F)
                .texOffs(378, 161).addBox(-1F, 22F, -4.5F, 4.5F, 2.5F, 1F)
                .texOffs(401, 161).addBox(2.1F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(430, 161).addBox(0.35F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(459, 161).addBox(-1.4F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(488, 161).addBox(-1F, -6.5F, 1F, 3F, 2.5F, 2.5F)
                .texOffs(0, 200).addBox(-1.5F, -5F, 0.5F, 4F, 1.5F, 3.5F)
                .texOffs(31, 200).addBox(-1.5F, -8F, 0.5F, 4F, 1.5F, 3.5F)
                .texOffs(62, 200).addBox(-0.5F, -6.5F, 0.75F, 2F, 1.5F, 0.25F)
                .texOffs(71, 200).addBox(-1F, -1.5F, -6.5F, 3F, 2.5F, 1.5F)
                .texOffs(90, 200).addBox(0F, -0.75F, -6.75F, 1F, 1F, 0.25F), PartPose.offset(13F, -6.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(177, 234).addBox(-2.5F, -1.5F, -3F, 4F, 5F, 6.5F)
                .texOffs(220, 234).addBox(-4F, -3F, -4.5F, 7F, 10.5F, 9.5F)
                .texOffs(287, 234).addBox(-4.5F, -4F, -5F, 8F, 2.5F, 10.5F)
                .texOffs(362, 234).addBox(-3.5F, -1.5F, -5.5F, 6F, 6F, 1F)
                .texOffs(391, 234).addBox(-4.5F, 6F, -5F, 8F, 2F, 10.5F)
                .texOffs(466, 234).addBox(-2.5F, 7.5F, -2.5F, 4F, 4F, 5.5F)
                .texOffs(0, 275).addBox(-1.5F, 8F, -3F, 2F, 3.5F, 0.5F)
                .texOffs(11, 275).addBox(-1F, 8.5F, -3.1F, 1F, 2.5F, 0.1F)
                .texOffs(16, 275).addBox(-4.5F, 10.5F, -4F, 6.5F, 10F, 9F)
                .texOffs(79, 275).addBox(-5F, 9.5F, -4.5F, 7.5F, 2.5F, 10F)
                .texOffs(150, 275).addBox(-4F, 12F, -5.5F, 5.5F, 7F, 1.5F)
                .texOffs(179, 275).addBox(-5F, 15F, -6F, 7.5F, 2F, 12F)
                .texOffs(258, 275).addBox(-2.5F, 14.5F, -7F, 2.5F, 3F, 1.5F)
                .texOffs(275, 275).addBox(-1.75F, 15.5F, -7.25F, 1F, 1F, 0.25F)
                .texOffs(280, 275).addBox(-3.5F, 19.5F, -3F, 4.5F, 2.5F, 6.5F)
                .texOffs(325, 275).addBox(-4F, 21F, -3.5F, 5.5F, 4F, 7.5F)
                .texOffs(378, 275).addBox(-3.5F, 22F, -4.5F, 4.5F, 2.5F, 1F)
                .texOffs(401, 275).addBox(-0.4F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(430, 275).addBox(-2.15F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(459, 275).addBox(-3.9F, 24F, -3F, 1.4F, 2F, 5.5F)
                .texOffs(488, 275).addBox(-2F, -6.5F, 1F, 3F, 2.5F, 2.5F)
                .texOffs(0, 314).addBox(-2.5F, -5F, 0.5F, 4F, 1.5F, 3.5F)
                .texOffs(31, 314).addBox(-2.5F, -8F, 0.5F, 4F, 1.5F, 3.5F)
                .texOffs(62, 314).addBox(-1.5F, -6.5F, 0.75F, 2F, 1.5F, 0.25F)
                .texOffs(71, 314).addBox(-2F, -1.5F, -6.5F, 3F, 2.5F, 1.5F)
                .texOffs(90, 314).addBox(-1F, -0.75F, -6.75F, 1F, 1F, 0.25F), PartPose.offset(-13F, -6.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(95, 200).addBox(-2F, -1.5F, -2.5F, 4.5F, 4F, 6F)
                .texOffs(138, 200).addBox(-3F, 0F, -4F, 6.5F, 8F, 8.5F)
                .texOffs(199, 200).addBox(-2.5F, 0.5F, -5F, 5.5F, 5.5F, 1F)
                .texOffs(226, 200).addBox(-3.5F, 6.5F, -5F, 7.5F, 2.5F, 10F)
                .texOffs(297, 200).addBox(-1F, 6F, -6F, 2.5F, 3.5F, 1.5F)
                .texOffs(314, 200).addBox(-0.25F, 7.25F, -6.25F, 1F, 1F, 0.25F)
                .texOffs(319, 200).addBox(-2.5F, 8.5F, -3.5F, 5.5F, 7F, 7.5F)
                .texOffs(372, 200).addBox(-0.5F, 9.5F, -4F, 1.5F, 5.5F, 0.5F)
                .texOffs(381, 200).addBox(0F, 10F, -4.1F, 0.5F, 4.5F, 0.1F)
                .texOffs(384, 200).addBox(-3.5F, 13F, -4.5F, 7.5F, 0.95F, 9.5F)
                .texOffs(0, 234).addBox(-4F, 16F, -7F, 8.5F, 1.5F, 12.5F)
                .texOffs(85, 234).addBox(-3.5F, 14F, -6F, 7.5F, 2F, 11F)
                .texOffs(160, 234).addBox(-1F, 15F, -7.5F, 2.5F, 2F, 1.5F), PartPose.offset(5.5F, 6.5F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(95, 314).addBox(-2.5F, -1.5F, -2.5F, 4.5F, 4F, 6F)
                .texOffs(138, 314).addBox(-3.5F, 0F, -4F, 6.5F, 8F, 8.5F)
                .texOffs(199, 314).addBox(-3F, 0.5F, -5F, 5.5F, 5.5F, 1F)
                .texOffs(226, 314).addBox(-4F, 6.5F, -5F, 7.5F, 2.5F, 10F)
                .texOffs(297, 314).addBox(-1.5F, 6F, -6F, 2.5F, 3.5F, 1.5F)
                .texOffs(314, 314).addBox(-0.75F, 7.25F, -6.25F, 1F, 1F, 0.25F)
                .texOffs(319, 314).addBox(-3F, 8.5F, -3.5F, 5.5F, 7F, 7.5F)
                .texOffs(372, 314).addBox(-1F, 9.5F, -4F, 1.5F, 5.5F, 0.5F)
                .texOffs(381, 314).addBox(-0.5F, 10F, -4.1F, 0.5F, 4.5F, 0.1F)
                .texOffs(384, 314).addBox(-4F, 13F, -4.5F, 7.5F, 0.95F, 9.5F)
                .texOffs(0, 348).addBox(-4.5F, 16F, -7F, 8.5F, 1.5F, 12.5F)
                .texOffs(85, 348).addBox(-4F, 14F, -6F, 7.5F, 2F, 11F)
                .texOffs(160, 348).addBox(-1.5F, 15F, -7.5F, 2.5F, 2F, 1.5F), PartPose.offset(-5.5F, 6.5F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                GoldGolemModel::createLayer, GoldGolemModel::new);
    }
}
