package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/gold_golem_f03.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class GoldGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "gold_golem_f03";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "gold_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "gold_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.GOLD;

    public GoldGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-8F, -17F, -7F, 16F, 15F, 14F)
                .texOffs(100, 0).addBox(-9F, -18F, -7F, 18F, 4F, 15F)
                .texOffs(167, 0).addBox(-3F, -18F, -8F, 6F, 8F, 1F)
                .texOffs(182, 0).addBox(3F, -14F, -9F, 6F, 3F, 3F)
                .texOffs(201, 0).addBox(-9F, -14F, -9F, 6F, 3F, 3F)
                .texOffs(220, 0).addBox(-7F, -11F, -8F, 14F, 3F, 1F)
                .texOffs(251, 0).addBox(2F, -10F, -8.3F, 4F, 1F, 0.3F)
                .texOffs(260, 0).addBox(-6F, -10F, -8.3F, 4F, 1F, 0.3F)
                .texOffs(269, 0).addBox(3F, -8F, -9F, 5F, 7F, 3F)
                .texOffs(286, 0).addBox(-8F, -8F, -9F, 5F, 7F, 3F)
                .texOffs(303, 0).addBox(-2F, -8F, -8.5F, 4F, 6F, 1.5F)
                .texOffs(316, 0).addBox(-8.3F, -13F, 7F, 16.6F, 3F, 2F)
                .texOffs(355, 0).addBox(5F, -13.5F, -9.5F, 2F, 2F, 0.5F)
                .texOffs(360, 0).addBox(-7F, -13.5F, -9.5F, 2F, 2F, 0.5F), PartPose.offset(0F, -44F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-5F, -32F, -4F, 10F, 6F, 9F)
                .texOffs(365, 0).addBox(-15F, -28F, -7F, 30F, 28F, 15F)
                .texOffs(0, 44).addBox(9F, -26F, -11F, 9F, 25F, 20F)
                .texOffs(59, 44).addBox(-18F, -26F, -11F, 9F, 25F, 20F)
                .texOffs(118, 44).addBox(-18.8F, -29F, -12F, 37.6F, 7F, 6F)
                .texOffs(207, 44).addBox(-17F, -6F, -12F, 34F, 6F, 6F)
                .texOffs(288, 44).addBox(-9F, -22F, -10F, 18F, 15F, 3F)
                .texOffs(331, 44).addBox(-7F, -20F, -10.3F, 14F, 11F, 0.3F)
                .texOffs(360, 44).addBox(-5F, -18F, -10.55F, 10F, 7F, 0.25F)
                .texOffs(381, 44).addBox(-2F, -16F, -10.8F, 4F, 3F, 0.25F)
                .texOffs(390, 44).addBox(8F, -23F, -13F, 3F, 17F, 3F)
                .texOffs(403, 44).addBox(-11F, -23F, -13F, 3F, 17F, 3F)
                .texOffs(416, 44).addBox(-11F, -23F, -13.15F, 22F, 3F, 3.15F)
                .texOffs(0, 90).addBox(-11F, -9F, -13.15F, 22F, 4F, 3.15F)
                .texOffs(51, 90).addBox(13F, -29F, -13F, 6F, 12F, 3F)
                .texOffs(70, 90).addBox(12F, -23F, -15F, 8F, 6F, 3F)
                .texOffs(93, 90).addBox(13F, -8F, -14F, 6F, 5F, 3F)
                .texOffs(112, 90).addBox(15F, -21F, -15.5F, 2F, 2F, 0.5F)
                .texOffs(117, 90).addBox(15F, -6.5F, -14.5F, 2F, 2F, 0.5F)
                .texOffs(122, 90).addBox(-19F, -29F, -13F, 6F, 12F, 3F)
                .texOffs(141, 90).addBox(-20F, -23F, -15F, 8F, 6F, 3F)
                .texOffs(164, 90).addBox(-19F, -8F, -14F, 6F, 5F, 3F)
                .texOffs(183, 90).addBox(-17F, -21F, -15.5F, 2F, 2F, 0.5F)
                .texOffs(188, 90).addBox(-17F, -6.5F, -14.5F, 2F, 2F, 0.5F)
                .texOffs(193, 90).addBox(8.5F, -8F, -13.5F, 2F, 2F, 0.5F)
                .texOffs(198, 90).addBox(8.5F, -22F, -13.5F, 2F, 2F, 0.5F)
                .texOffs(203, 90).addBox(-10.5F, -8F, -13.5F, 2F, 2F, 0.5F)
                .texOffs(208, 90).addBox(-10.5F, -22F, -13.5F, 2F, 2F, 0.5F)
                .texOffs(213, 90).addBox(-11F, -1F, -6F, 22F, 6F, 13F)
                .texOffs(284, 90).addBox(-14F, 0F, -8F, 28F, 4F, 17F)
                .texOffs(375, 90).addBox(-6F, 1F, -11F, 12F, 9F, 5F)
                .texOffs(410, 90).addBox(-2F, 2F, -11.3F, 4F, 7F, 0.3F)
                .texOffs(419, 90).addBox(-1F, 3F, -11.5F, 2F, 5F, 0.2F)
                .texOffs(424, 90).addBox(4F, -27F, 8F, 13F, 24F, 4F)
                .texOffs(459, 90).addBox(-17F, -27F, 8F, 13F, 24F, 4F)
                .texOffs(494, 90).addBox(-3F, -27F, 9F, 6F, 26F, 3F)
                .texOffs(0, 120).addBox(-1F, -25F, 12F, 2F, 21F, 0.25F)
                .texOffs(5, 120).addBox(-18F, -8F, 12F, 36F, 4F, 3F)
                .texOffs(84, 120).addBox(12F, -7F, 15F, 2F, 2F, 0.5F)
                .texOffs(89, 120).addBox(-14F, -7F, 15F, 2F, 2F, 0.5F)
                .texOffs(94, 120).addBox(-18F, -26F, 12F, 36F, 4F, 3F)
                .texOffs(173, 120).addBox(12F, -25F, 15F, 2F, 2F, 0.5F)
                .texOffs(178, 120).addBox(-14F, -25F, 15F, 2F, 2F, 0.5F), PartPose.offset(0F, -15F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(183, 120).addBox(-3F, -3F, -6F, 8F, 10F, 13F)
                .texOffs(226, 120).addBox(-6F, -6F, -9F, 14F, 21F, 19F)
                .texOffs(293, 120).addBox(-7F, -8F, -10F, 16F, 5F, 21F)
                .texOffs(368, 120).addBox(-5F, -3F, -11F, 12F, 12F, 2F)
                .texOffs(397, 120).addBox(-7F, 12F, -10F, 16F, 4F, 21F)
                .texOffs(472, 120).addBox(-3F, 15F, -5F, 8F, 8F, 11F)
                .texOffs(0, 161).addBox(-1F, 16F, -6F, 4F, 7F, 1F)
                .texOffs(11, 161).addBox(0F, 17F, -6.2F, 2F, 5F, 0.2F)
                .texOffs(16, 161).addBox(-4F, 21F, -8F, 13F, 20F, 18F)
                .texOffs(79, 161).addBox(-5F, 19F, -9F, 15F, 5F, 20F)
                .texOffs(150, 161).addBox(-3F, 24F, -11F, 11F, 14F, 3F)
                .texOffs(179, 161).addBox(-5F, 30F, -12F, 15F, 4F, 24F)
                .texOffs(258, 161).addBox(0F, 29F, -14F, 5F, 6F, 3F)
                .texOffs(275, 161).addBox(1.5F, 31F, -14.5F, 2F, 2F, 0.5F)
                .texOffs(280, 161).addBox(-2F, 39F, -6F, 9F, 5F, 13F)
                .texOffs(325, 161).addBox(-3F, 42F, -7F, 11F, 8F, 15F)
                .texOffs(378, 161).addBox(-2F, 44F, -9F, 9F, 5F, 2F)
                .texOffs(401, 161).addBox(4.2F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(430, 161).addBox(0.7F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(459, 161).addBox(-2.8F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(488, 161).addBox(-2F, -13F, 2F, 6F, 5F, 5F)
                .texOffs(0, 200).addBox(-3F, -10F, 1F, 8F, 3F, 7F)
                .texOffs(31, 200).addBox(-3F, -16F, 1F, 8F, 3F, 7F)
                .texOffs(62, 200).addBox(-1F, -13F, 1.5F, 4F, 3F, 0.5F)
                .texOffs(71, 200).addBox(-2F, -3F, -13F, 6F, 5F, 3F)
                .texOffs(90, 200).addBox(0F, -1.5F, -13.5F, 2F, 2F, 0.5F), PartPose.offset(26F, -37F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(177, 234).addBox(-5F, -3F, -6F, 8F, 10F, 13F)
                .texOffs(220, 234).addBox(-8F, -6F, -9F, 14F, 21F, 19F)
                .texOffs(287, 234).addBox(-9F, -8F, -10F, 16F, 5F, 21F)
                .texOffs(362, 234).addBox(-7F, -3F, -11F, 12F, 12F, 2F)
                .texOffs(391, 234).addBox(-9F, 12F, -10F, 16F, 4F, 21F)
                .texOffs(466, 234).addBox(-5F, 15F, -5F, 8F, 8F, 11F)
                .texOffs(0, 275).addBox(-3F, 16F, -6F, 4F, 7F, 1F)
                .texOffs(11, 275).addBox(-2F, 17F, -6.2F, 2F, 5F, 0.2F)
                .texOffs(16, 275).addBox(-9F, 21F, -8F, 13F, 20F, 18F)
                .texOffs(79, 275).addBox(-10F, 19F, -9F, 15F, 5F, 20F)
                .texOffs(150, 275).addBox(-8F, 24F, -11F, 11F, 14F, 3F)
                .texOffs(179, 275).addBox(-10F, 30F, -12F, 15F, 4F, 24F)
                .texOffs(258, 275).addBox(-5F, 29F, -14F, 5F, 6F, 3F)
                .texOffs(275, 275).addBox(-3.5F, 31F, -14.5F, 2F, 2F, 0.5F)
                .texOffs(280, 275).addBox(-7F, 39F, -6F, 9F, 5F, 13F)
                .texOffs(325, 275).addBox(-8F, 42F, -7F, 11F, 8F, 15F)
                .texOffs(378, 275).addBox(-7F, 44F, -9F, 9F, 5F, 2F)
                .texOffs(401, 275).addBox(-0.8F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(430, 275).addBox(-4.3F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(459, 275).addBox(-7.8F, 48F, -6F, 2.8F, 4F, 11F)
                .texOffs(488, 275).addBox(-4F, -13F, 2F, 6F, 5F, 5F)
                .texOffs(0, 314).addBox(-5F, -10F, 1F, 8F, 3F, 7F)
                .texOffs(31, 314).addBox(-5F, -16F, 1F, 8F, 3F, 7F)
                .texOffs(62, 314).addBox(-3F, -13F, 1.5F, 4F, 3F, 0.5F)
                .texOffs(71, 314).addBox(-4F, -3F, -13F, 6F, 5F, 3F)
                .texOffs(90, 314).addBox(-2F, -1.5F, -13.5F, 2F, 2F, 0.5F), PartPose.offset(-26F, -37F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(95, 200).addBox(-4F, -3F, -5F, 9F, 8F, 12F)
                .texOffs(138, 200).addBox(-6F, 0F, -8F, 13F, 16F, 17F)
                .texOffs(199, 200).addBox(-5F, 1F, -10F, 11F, 11F, 2F)
                .texOffs(226, 200).addBox(-7F, 13F, -10F, 15F, 5F, 20F)
                .texOffs(297, 200).addBox(-2F, 12F, -12F, 5F, 7F, 3F)
                .texOffs(314, 200).addBox(-0.5F, 14.5F, -12.5F, 2F, 2F, 0.5F)
                .texOffs(319, 200).addBox(-5F, 17F, -7F, 11F, 14F, 15F)
                .texOffs(372, 200).addBox(-1F, 19F, -8F, 3F, 11F, 1F)
                .texOffs(381, 200).addBox(0F, 20F, -8.2F, 1F, 9F, 0.2F)
                .texOffs(384, 200).addBox(-7F, 26F, -9F, 15F, 1.9F, 19F)
                .texOffs(0, 234).addBox(-8F, 32F, -14F, 17F, 3F, 25F)
                .texOffs(85, 234).addBox(-7F, 28F, -12F, 15F, 4F, 22F)
                .texOffs(160, 234).addBox(-2F, 30F, -15F, 5F, 4F, 3F), PartPose.offset(11F, -11F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(95, 314).addBox(-5F, -3F, -5F, 9F, 8F, 12F)
                .texOffs(138, 314).addBox(-7F, 0F, -8F, 13F, 16F, 17F)
                .texOffs(199, 314).addBox(-6F, 1F, -10F, 11F, 11F, 2F)
                .texOffs(226, 314).addBox(-8F, 13F, -10F, 15F, 5F, 20F)
                .texOffs(297, 314).addBox(-3F, 12F, -12F, 5F, 7F, 3F)
                .texOffs(314, 314).addBox(-1.5F, 14.5F, -12.5F, 2F, 2F, 0.5F)
                .texOffs(319, 314).addBox(-6F, 17F, -7F, 11F, 14F, 15F)
                .texOffs(372, 314).addBox(-2F, 19F, -8F, 3F, 11F, 1F)
                .texOffs(381, 314).addBox(-1F, 20F, -8.2F, 1F, 9F, 0.2F)
                .texOffs(384, 314).addBox(-8F, 26F, -9F, 15F, 1.9F, 19F)
                .texOffs(0, 348).addBox(-9F, 32F, -14F, 17F, 3F, 25F)
                .texOffs(85, 348).addBox(-8F, 28F, -12F, 15F, 4F, 22F)
                .texOffs(160, 348).addBox(-3F, 30F, -15F, 5F, 4F, 3F), PartPose.offset(-11F, -11F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                GoldGolemModel::createLayer, GoldGolemModel::new);
    }
}
