package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/obsidian_golem_f05.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class ObsidianGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "obsidian_golem_f05";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "obsidian_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "obsidian_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.OBSIDIAN;

    public ObsidianGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-8F, -13F, -7F, 16F, 12F, 15F)
                .texOffs(102, 0).addBox(-7F, -15F, -6F, 14F, 3F, 13F)
                .texOffs(157, 0).addBox(-2F, -15F, -8F, 4F, 5F, 2F)
                .texOffs(170, 0).addBox(-7F, -10F, -8F, 14F, 4F, 1F)
                .texOffs(201, 0).addBox(2.3F, -8.5F, -8.3F, 3.4F, 1.5F, 0.3F)
                .texOffs(208, 0).addBox(1.5F, -12.5F, -9.5F, 5F, 3F, 2F)
                .texOffs(223, 0).addBox(1.5F, -6F, -9.3F, 5F, 5F, 2.3F)
                .texOffs(238, 0).addBox(8F, -11F, -3F, 6F, 5F, 8F)
                .texOffs(267, 0).addBox(8.5F, -17F, -2F, 5F, 7F, 6F)
                .texOffs(290, 0).addBox(9F, -20F, -1.5F, 4F, 4F, 5F)
                .texOffs(309, 0).addBox(-5.7F, -8.5F, -8.3F, 3.4F, 1.5F, 0.3F)
                .texOffs(316, 0).addBox(-6.5F, -12.5F, -9.5F, 5F, 3F, 2F)
                .texOffs(331, 0).addBox(-6.5F, -6F, -9.3F, 5F, 5F, 2.3F)
                .texOffs(346, 0).addBox(-14F, -11F, -3F, 6F, 5F, 8F)
                .texOffs(375, 0).addBox(-13.5F, -17F, -2F, 5F, 7F, 6F)
                .texOffs(398, 0).addBox(-13F, -20F, -1.5F, 4F, 4F, 5F)
                .texOffs(417, 0).addBox(-1.8F, -8F, -10F, 3.6F, 7F, 2F)
                .texOffs(430, 0).addBox(-7F, -2F, -9.8F, 14F, 2F, 2.6F)
                .texOffs(465, 0).addBox(-2F, -13F, 8F, 4F, 11F, 2F)
                .texOffs(0, 28).addBox(-8.3F, -4F, 8.2F, 16.6F, 3F, 2F), PartPose.offset(0F, -42F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-5F, -29F, -4F, 10F, 5F, 9F)
                .texOffs(39, 28).addBox(-14F, -25F, -6F, 28F, 25F, 13F)
                .texOffs(122, 28).addBox(8.2F, -25F, -10F, 9.8F, 24F, 19F)
                .texOffs(181, 28).addBox(-18F, -25F, -10F, 9.8F, 24F, 19F)
                .texOffs(240, 28).addBox(-18.8F, -26F, -11F, 37.6F, 5F, 5F)
                .texOffs(327, 28).addBox(-17F, -5F, -10.5F, 34F, 6F, 4.5F)
                .texOffs(404, 28).addBox(-8F, -21F, -9F, 16F, 16F, 3F)
                .texOffs(443, 28).addBox(-6F, -19F, -9.4F, 12F, 12F, 0.4F)
                .texOffs(468, 28).addBox(-4F, -17F, -9.8F, 8F, 8F, 0.4F)
                .texOffs(485, 28).addBox(-2F, -15F, -10.2F, 4F, 4F, 0.4F)
                .texOffs(494, 28).addBox(8F, -22F, -12F, 3F, 18F, 3F)
                .texOffs(0, 72).addBox(-11F, -22F, -12F, 3F, 18F, 3F)
                .texOffs(13, 72).addBox(-10.8F, -23F, -12.2F, 21.6F, 3F, 3.4F)
                .texOffs(64, 72).addBox(-10.8F, -7F, -12.2F, 21.6F, 4F, 3.4F)
                .texOffs(115, 72).addBox(12.5F, -27F, -13F, 5F, 14F, 2.5F)
                .texOffs(130, 72).addBox(11.5F, -23F, -14.5F, 7F, 5F, 3F)
                .texOffs(151, 72).addBox(12F, -6F, -13.5F, 6F, 5F, 3F)
                .texOffs(170, 72).addBox(14F, -21.5F, -15.1F, 2F, 2F, 0.6F)
                .texOffs(177, 72).addBox(14F, -4.5F, -14.1F, 2F, 2F, 0.6F)
                .texOffs(184, 72).addBox(-17.5F, -27F, -13F, 5F, 14F, 2.5F)
                .texOffs(199, 72).addBox(-18.5F, -23F, -14.5F, 7F, 5F, 3F)
                .texOffs(220, 72).addBox(-18F, -6F, -13.5F, 6F, 5F, 3F)
                .texOffs(239, 72).addBox(-16F, -21.5F, -15.1F, 2F, 2F, 0.6F)
                .texOffs(246, 72).addBox(-16F, -4.5F, -14.1F, 2F, 2F, 0.6F)
                .texOffs(253, 72).addBox(-11F, 0F, -5F, 22F, 6F, 11F)
                .texOffs(320, 72).addBox(-15F, 1F, -8F, 30F, 4F, 17.2F)
                .texOffs(415, 72).addBox(-6F, 4F, -9F, 12F, 7F, 3F)
                .texOffs(446, 72).addBox(-2F, 4F, -11F, 4F, 8F, 2F)
                .texOffs(459, 72).addBox(-1F, 6F, -11.6F, 2F, 2F, 0.6F)
                .texOffs(466, 72).addBox(2F, -25F, 8F, 15F, 23F, 4F)
                .texOffs(0, 100).addBox(-17F, -25F, 8F, 15F, 23F, 4F)
                .texOffs(39, 100).addBox(-2.5F, -26F, 12.2F, 5F, 25F, 2.8F)
                .texOffs(56, 100).addBox(-16F, -6F, 15.2F, 32F, 3F, 1.8F)
                .texOffs(125, 100).addBox(10F, -5.5F, 16.4F, 2F, 2F, 0.6F)
                .texOffs(132, 100).addBox(-1F, -5.5F, 16.4F, 2F, 2F, 0.6F)
                .texOffs(139, 100).addBox(-12F, -5.5F, 16.4F, 2F, 2F, 0.6F)
                .texOffs(146, 100).addBox(-16F, -21F, 15.2F, 32F, 3F, 1.8F)
                .texOffs(215, 100).addBox(10F, -20.5F, 16.4F, 2F, 2F, 0.6F)
                .texOffs(222, 100).addBox(-1F, -20.5F, 16.4F, 2F, 2F, 0.6F)
                .texOffs(229, 100).addBox(-12F, -20.5F, 16.4F, 2F, 2F, 0.6F), PartPose.offset(0F, -15F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(236, 100).addBox(-3F, -3F, -4F, 8F, 11F, 10F)
                .texOffs(273, 100).addBox(-5F, -5F, -8F, 12F, 19.8F, 18F)
                .texOffs(334, 100).addBox(-6F, -5F, -9F, 14F, 10F, 20F)
                .texOffs(403, 100).addBox(-4.5F, -8F, -7F, 11F, 4F, 16F)
                .texOffs(458, 100).addBox(5.6F, -2F, -6F, 2.8F, 13F, 14F)
                .texOffs(493, 100).addBox(-1F, -11F, 3F, 4F, 4F, 4F)
                .texOffs(0, 139).addBox(-4F, -3F, -11F, 10F, 14F, 2F)
                .texOffs(25, 139).addBox(-6F, 12F, -10F, 14F, 4F, 22F)
                .texOffs(98, 139).addBox(-1.5F, 11.5F, -12F, 5F, 4F, 2F)
                .texOffs(113, 139).addBox(0F, 12.5F, -12.6F, 2F, 2F, 0.6F)
                .texOffs(120, 139).addBox(-2F, 15F, -4F, 6F, 8F, 10F)
                .texOffs(153, 139).addBox(-0.5F, 16F, -6F, 3F, 7F, 2F)
                .texOffs(164, 139).addBox(-4F, 22F, -7F, 12F, 19.8F, 17F)
                .texOffs(223, 139).addBox(-3F, 24F, -10F, 10F, 14F, 3F)
                .texOffs(250, 139).addBox(5.5F, 25F, -6F, 3F, 12F, 14F)
                .texOffs(285, 139).addBox(-5F, 20F, -11F, 14F, 4F, 22F)
                .texOffs(358, 139).addBox(0F, 19.7F, -13F, 4F, 4.6F, 3F)
                .texOffs(373, 139).addBox(1F, 21F, -13.6F, 2F, 2F, 0.6F)
                .texOffs(380, 139).addBox(-5F, 38F, -11F, 14F, 4F, 22F)
                .texOffs(453, 139).addBox(0F, 37.7F, -13F, 4F, 4.6F, 3F)
                .texOffs(468, 139).addBox(1F, 39F, -13.6F, 2F, 2F, 0.6F)
                .texOffs(475, 139).addBox(-1F, 41F, -4F, 6F, 4F, 10F)
                .texOffs(0, 177).addBox(-3F, 44F, -7F, 10F, 8F, 14F)
                .texOffs(49, 177).addBox(4F, 49F, -8F, 2.5F, 5F, 2F)
                .texOffs(58, 177).addBox(0.8F, 49F, -8F, 2.5F, 5F, 2F)
                .texOffs(67, 177).addBox(-2.4F, 49F, -8F, 2.5F, 5F, 2F), PartPose.offset(27F, -36F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(88, 211).addBox(-5F, -3F, -4F, 8F, 11F, 10F)
                .texOffs(125, 211).addBox(-7F, -5F, -8F, 12F, 19.8F, 18F)
                .texOffs(186, 211).addBox(-8F, -5F, -9F, 14F, 10F, 20F)
                .texOffs(255, 211).addBox(-6.5F, -8F, -7F, 11F, 4F, 16F)
                .texOffs(310, 211).addBox(-8.4F, -2F, -6F, 2.8F, 13F, 14F)
                .texOffs(345, 211).addBox(-3F, -11F, 3F, 4F, 4F, 4F)
                .texOffs(362, 211).addBox(-6F, -3F, -11F, 10F, 14F, 2F)
                .texOffs(387, 211).addBox(-8F, 12F, -10F, 14F, 4F, 22F)
                .texOffs(460, 211).addBox(-3.5F, 11.5F, -12F, 5F, 4F, 2F)
                .texOffs(475, 211).addBox(-2F, 12.5F, -12.6F, 2F, 2F, 0.6F)
                .texOffs(0, 250).addBox(-4F, 15F, -4F, 6F, 8F, 10F)
                .texOffs(33, 250).addBox(-2.5F, 16F, -6F, 3F, 7F, 2F)
                .texOffs(44, 250).addBox(-8F, 22F, -7F, 12F, 19.8F, 17F)
                .texOffs(103, 250).addBox(-7F, 24F, -10F, 10F, 14F, 3F)
                .texOffs(130, 250).addBox(-8.5F, 25F, -6F, 3F, 12F, 14F)
                .texOffs(165, 250).addBox(-9F, 20F, -11F, 14F, 4F, 22F)
                .texOffs(238, 250).addBox(-4F, 19.7F, -13F, 4F, 4.6F, 3F)
                .texOffs(253, 250).addBox(-3F, 21F, -13.6F, 2F, 2F, 0.6F)
                .texOffs(260, 250).addBox(-9F, 38F, -11F, 14F, 4F, 22F)
                .texOffs(333, 250).addBox(-4F, 37.7F, -13F, 4F, 4.6F, 3F)
                .texOffs(348, 250).addBox(-3F, 39F, -13.6F, 2F, 2F, 0.6F)
                .texOffs(355, 250).addBox(-5F, 41F, -4F, 6F, 4F, 10F)
                .texOffs(388, 250).addBox(-7F, 44F, -7F, 10F, 8F, 14F)
                .texOffs(437, 250).addBox(0F, 49F, -8F, 2.5F, 5F, 2F)
                .texOffs(446, 250).addBox(-3.2F, 49F, -8F, 2.5F, 5F, 2F)
                .texOffs(455, 250).addBox(-6.4F, 49F, -8F, 2.5F, 5F, 2F), PartPose.offset(-27F, -36F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(76, 177).addBox(-2.8F, -2F, -4F, 5.6F, 8F, 10F)
                .texOffs(109, 177).addBox(-6F, 0F, -7F, 12F, 16.8F, 16F)
                .texOffs(166, 177).addBox(-5F, 2F, -9F, 10F, 11F, 2F)
                .texOffs(191, 177).addBox(-7F, 14F, -10F, 14F, 4F, 20F)
                .texOffs(260, 177).addBox(-2.5F, 13F, -12F, 5F, 6F, 3F)
                .texOffs(277, 177).addBox(-1F, 15F, -12.6F, 2F, 2F, 0.6F)
                .texOffs(284, 177).addBox(-5F, 17F, -6F, 10F, 12.8F, 14F)
                .texOffs(333, 177).addBox(-2.5F, 19F, -8F, 5F, 9F, 2F)
                .texOffs(348, 177).addBox(-6F, 27F, -9F, 12F, 3F, 18F)
                .texOffs(409, 177).addBox(-7F, 32F, -13F, 14F, 3F, 24F)
                .texOffs(0, 211).addBox(-6.5F, 30F, -12F, 13F, 2F, 22F)
                .texOffs(71, 211).addBox(-3F, 31F, -14F, 6F, 3F, 2F), PartPose.offset(12F, -11F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(464, 250).addBox(-2.8F, -2F, -4F, 5.6F, 8F, 10F)
                .texOffs(0, 288).addBox(-6F, 0F, -7F, 12F, 16.8F, 16F)
                .texOffs(57, 288).addBox(-5F, 2F, -9F, 10F, 11F, 2F)
                .texOffs(82, 288).addBox(-7F, 14F, -10F, 14F, 4F, 20F)
                .texOffs(151, 288).addBox(-2.5F, 13F, -12F, 5F, 6F, 3F)
                .texOffs(168, 288).addBox(-1F, 15F, -12.6F, 2F, 2F, 0.6F)
                .texOffs(175, 288).addBox(-5F, 17F, -6F, 10F, 12.8F, 14F)
                .texOffs(224, 288).addBox(-2.5F, 19F, -8F, 5F, 9F, 2F)
                .texOffs(239, 288).addBox(-6F, 27F, -9F, 12F, 3F, 18F)
                .texOffs(300, 288).addBox(-7F, 32F, -13F, 14F, 3F, 24F)
                .texOffs(377, 288).addBox(-6.5F, 30F, -12F, 13F, 2F, 22F)
                .texOffs(448, 288).addBox(-3F, 31F, -14F, 6F, 3F, 2F), PartPose.offset(-12F, -11F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                ObsidianGolemModel::createLayer, ObsidianGolemModel::new);
    }
}
