package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/obsidian_golem_f05.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class ObsidianGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "obsidian_golem_f05";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "obsidian_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "obsidian_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.OBSIDIAN;

    public ObsidianGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(39, 0).addBox(-4F, -6.5F, -3.5F, 8F, 6F, 7.5F)
                .texOffs(102, 0).addBox(-3.5F, -7.5F, -3F, 7F, 1.5F, 6.5F)
                .texOffs(157, 0).addBox(-1F, -7.5F, -4F, 2F, 2.5F, 1F)
                .texOffs(170, 0).addBox(-3.5F, -5F, -4F, 7F, 2F, 0.5F)
                .texOffs(201, 0).addBox(1.15F, -4.25F, -4.15F, 1.7F, 0.75F, 0.15F)
                .texOffs(208, 0).addBox(0.75F, -6.25F, -4.75F, 2.5F, 1.5F, 1F)
                .texOffs(223, 0).addBox(0.75F, -3F, -4.65F, 2.5F, 2.5F, 1.15F)
                .texOffs(238, 0).addBox(4F, -5.5F, -1.5F, 3F, 2.5F, 4F)
                .texOffs(267, 0).addBox(4.25F, -8.5F, -1F, 2.5F, 3.5F, 3F)
                .texOffs(290, 0).addBox(4.5F, -10F, -0.75F, 2F, 2F, 2.5F)
                .texOffs(309, 0).addBox(-2.85F, -4.25F, -4.15F, 1.7F, 0.75F, 0.15F)
                .texOffs(316, 0).addBox(-3.25F, -6.25F, -4.75F, 2.5F, 1.5F, 1F)
                .texOffs(331, 0).addBox(-3.25F, -3F, -4.65F, 2.5F, 2.5F, 1.15F)
                .texOffs(346, 0).addBox(-7F, -5.5F, -1.5F, 3F, 2.5F, 4F)
                .texOffs(375, 0).addBox(-6.75F, -8.5F, -1F, 2.5F, 3.5F, 3F)
                .texOffs(398, 0).addBox(-6.5F, -10F, -0.75F, 2F, 2F, 2.5F)
                .texOffs(417, 0).addBox(-0.9F, -4F, -5F, 1.8F, 3.5F, 1F)
                .texOffs(430, 0).addBox(-3.5F, -1F, -4.9F, 7F, 1F, 1.3F)
                .texOffs(465, 0).addBox(-1F, -6.5F, 4F, 2F, 5.5F, 1F)
                .texOffs(0, 28).addBox(-4.15F, -2F, 4.1F, 8.3F, 1.5F, 1F), PartPose.offset(0F, -9F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.5F, -14.5F, -2F, 5F, 2.5F, 4.5F)
                .texOffs(39, 28).addBox(-7F, -12.5F, -3F, 14F, 12.5F, 6.5F)
                .texOffs(122, 28).addBox(4.1F, -12.5F, -5F, 4.9F, 12F, 9.5F)
                .texOffs(181, 28).addBox(-9F, -12.5F, -5F, 4.9F, 12F, 9.5F)
                .texOffs(240, 28).addBox(-9.4F, -13F, -5.5F, 18.8F, 2.5F, 2.5F)
                .texOffs(327, 28).addBox(-8.5F, -2.5F, -5.25F, 17F, 3F, 2.25F)
                .texOffs(404, 28).addBox(-4F, -10.5F, -4.5F, 8F, 8F, 1.5F)
                .texOffs(443, 28).addBox(-3F, -9.5F, -4.7F, 6F, 6F, 0.2F)
                .texOffs(468, 28).addBox(-2F, -8.5F, -4.9F, 4F, 4F, 0.2F)
                .texOffs(485, 28).addBox(-1F, -7.5F, -5.1F, 2F, 2F, 0.2F)
                .texOffs(494, 28).addBox(4F, -11F, -6F, 1.5F, 9F, 1.5F)
                .texOffs(0, 72).addBox(-5.5F, -11F, -6F, 1.5F, 9F, 1.5F)
                .texOffs(13, 72).addBox(-5.4F, -11.5F, -6.1F, 10.8F, 1.5F, 1.7F)
                .texOffs(64, 72).addBox(-5.4F, -3.5F, -6.1F, 10.8F, 2F, 1.7F)
                .texOffs(115, 72).addBox(6.25F, -13.5F, -6.5F, 2.5F, 7F, 1.25F)
                .texOffs(130, 72).addBox(5.75F, -11.5F, -7.25F, 3.5F, 2.5F, 1.5F)
                .texOffs(151, 72).addBox(6F, -3F, -6.75F, 3F, 2.5F, 1.5F)
                .texOffs(170, 72).addBox(7F, -10.75F, -7.55F, 1F, 1F, 0.3F)
                .texOffs(177, 72).addBox(7F, -2.25F, -7.05F, 1F, 1F, 0.3F)
                .texOffs(184, 72).addBox(-8.75F, -13.5F, -6.5F, 2.5F, 7F, 1.25F)
                .texOffs(199, 72).addBox(-9.25F, -11.5F, -7.25F, 3.5F, 2.5F, 1.5F)
                .texOffs(220, 72).addBox(-9F, -3F, -6.75F, 3F, 2.5F, 1.5F)
                .texOffs(239, 72).addBox(-8F, -10.75F, -7.55F, 1F, 1F, 0.3F)
                .texOffs(246, 72).addBox(-8F, -2.25F, -7.05F, 1F, 1F, 0.3F)
                .texOffs(253, 72).addBox(-5.5F, 0F, -2.5F, 11F, 3F, 5.5F)
                .texOffs(320, 72).addBox(-7.5F, 0.5F, -4F, 15F, 2F, 8.6F)
                .texOffs(415, 72).addBox(-3F, 2F, -4.5F, 6F, 3.5F, 1.5F)
                .texOffs(446, 72).addBox(-1F, 2F, -5.5F, 2F, 4F, 1F)
                .texOffs(459, 72).addBox(-0.5F, 3F, -5.8F, 1F, 1F, 0.3F)
                .texOffs(466, 72).addBox(1F, -12.5F, 4F, 7.5F, 11.5F, 2F)
                .texOffs(0, 100).addBox(-8.5F, -12.5F, 4F, 7.5F, 11.5F, 2F)
                .texOffs(39, 100).addBox(-1.25F, -13F, 6.1F, 2.5F, 12.5F, 1.4F)
                .texOffs(56, 100).addBox(-8F, -3F, 7.6F, 16F, 1.5F, 0.9F)
                .texOffs(125, 100).addBox(5F, -2.75F, 8.2F, 1F, 1F, 0.3F)
                .texOffs(132, 100).addBox(-0.5F, -2.75F, 8.2F, 1F, 1F, 0.3F)
                .texOffs(139, 100).addBox(-6F, -2.75F, 8.2F, 1F, 1F, 0.3F)
                .texOffs(146, 100).addBox(-8F, -10.5F, 7.6F, 16F, 1.5F, 0.9F)
                .texOffs(215, 100).addBox(5F, -10.25F, 8.2F, 1F, 1F, 0.3F)
                .texOffs(222, 100).addBox(-0.5F, -10.25F, 8.2F, 1F, 1F, 0.3F)
                .texOffs(229, 100).addBox(-6F, -10.25F, 8.2F, 1F, 1F, 0.3F), PartPose.offset(0F, 4.5F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(236, 100).addBox(-1.5F, -1.5F, -2F, 4F, 5.5F, 5F)
                .texOffs(273, 100).addBox(-2.5F, -2.5F, -4F, 6F, 9.9F, 9F)
                .texOffs(334, 100).addBox(-3F, -2.5F, -4.5F, 7F, 5F, 10F)
                .texOffs(403, 100).addBox(-2.25F, -4F, -3.5F, 5.5F, 2F, 8F)
                .texOffs(458, 100).addBox(2.8F, -1F, -3F, 1.4F, 6.5F, 7F)
                .texOffs(493, 100).addBox(-0.5F, -5.5F, 1.5F, 2F, 2F, 2F)
                .texOffs(0, 139).addBox(-2F, -1.5F, -5.5F, 5F, 7F, 1F)
                .texOffs(25, 139).addBox(-3F, 6F, -5F, 7F, 2F, 11F)
                .texOffs(98, 139).addBox(-0.75F, 5.75F, -6F, 2.5F, 2F, 1F)
                .texOffs(113, 139).addBox(0F, 6.25F, -6.3F, 1F, 1F, 0.3F)
                .texOffs(120, 139).addBox(-1F, 7.5F, -2F, 3F, 4F, 5F)
                .texOffs(153, 139).addBox(-0.25F, 8F, -3F, 1.5F, 3.5F, 1F)
                .texOffs(164, 139).addBox(-2F, 11F, -3.5F, 6F, 9.9F, 8.5F)
                .texOffs(223, 139).addBox(-1.5F, 12F, -5F, 5F, 7F, 1.5F)
                .texOffs(250, 139).addBox(2.75F, 12.5F, -3F, 1.5F, 6F, 7F)
                .texOffs(285, 139).addBox(-2.5F, 10F, -5.5F, 7F, 2F, 11F)
                .texOffs(358, 139).addBox(0F, 9.85F, -6.5F, 2F, 2.3F, 1.5F)
                .texOffs(373, 139).addBox(0.5F, 10.5F, -6.8F, 1F, 1F, 0.3F)
                .texOffs(380, 139).addBox(-2.5F, 19F, -5.5F, 7F, 2F, 11F)
                .texOffs(453, 139).addBox(0F, 18.85F, -6.5F, 2F, 2.3F, 1.5F)
                .texOffs(468, 139).addBox(0.5F, 19.5F, -6.8F, 1F, 1F, 0.3F)
                .texOffs(475, 139).addBox(-0.5F, 20.5F, -2F, 3F, 2F, 5F)
                .texOffs(0, 177).addBox(-1.5F, 22F, -3.5F, 5F, 4F, 7F)
                .texOffs(49, 177).addBox(2F, 24.5F, -4F, 1.25F, 2.5F, 1F)
                .texOffs(58, 177).addBox(0.4F, 24.5F, -4F, 1.25F, 2.5F, 1F)
                .texOffs(67, 177).addBox(-1.2F, 24.5F, -4F, 1.25F, 2.5F, 1F), PartPose.offset(13.5F, -6F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(88, 211).addBox(-2.5F, -1.5F, -2F, 4F, 5.5F, 5F)
                .texOffs(125, 211).addBox(-3.5F, -2.5F, -4F, 6F, 9.9F, 9F)
                .texOffs(186, 211).addBox(-4F, -2.5F, -4.5F, 7F, 5F, 10F)
                .texOffs(255, 211).addBox(-3.25F, -4F, -3.5F, 5.5F, 2F, 8F)
                .texOffs(310, 211).addBox(-4.2F, -1F, -3F, 1.4F, 6.5F, 7F)
                .texOffs(345, 211).addBox(-1.5F, -5.5F, 1.5F, 2F, 2F, 2F)
                .texOffs(362, 211).addBox(-3F, -1.5F, -5.5F, 5F, 7F, 1F)
                .texOffs(387, 211).addBox(-4F, 6F, -5F, 7F, 2F, 11F)
                .texOffs(460, 211).addBox(-1.75F, 5.75F, -6F, 2.5F, 2F, 1F)
                .texOffs(475, 211).addBox(-1F, 6.25F, -6.3F, 1F, 1F, 0.3F)
                .texOffs(0, 250).addBox(-2F, 7.5F, -2F, 3F, 4F, 5F)
                .texOffs(33, 250).addBox(-1.25F, 8F, -3F, 1.5F, 3.5F, 1F)
                .texOffs(44, 250).addBox(-4F, 11F, -3.5F, 6F, 9.9F, 8.5F)
                .texOffs(103, 250).addBox(-3.5F, 12F, -5F, 5F, 7F, 1.5F)
                .texOffs(130, 250).addBox(-4.25F, 12.5F, -3F, 1.5F, 6F, 7F)
                .texOffs(165, 250).addBox(-4.5F, 10F, -5.5F, 7F, 2F, 11F)
                .texOffs(238, 250).addBox(-2F, 9.85F, -6.5F, 2F, 2.3F, 1.5F)
                .texOffs(253, 250).addBox(-1.5F, 10.5F, -6.8F, 1F, 1F, 0.3F)
                .texOffs(260, 250).addBox(-4.5F, 19F, -5.5F, 7F, 2F, 11F)
                .texOffs(333, 250).addBox(-2F, 18.85F, -6.5F, 2F, 2.3F, 1.5F)
                .texOffs(348, 250).addBox(-1.5F, 19.5F, -6.8F, 1F, 1F, 0.3F)
                .texOffs(355, 250).addBox(-2.5F, 20.5F, -2F, 3F, 2F, 5F)
                .texOffs(388, 250).addBox(-3.5F, 22F, -3.5F, 5F, 4F, 7F)
                .texOffs(437, 250).addBox(0F, 24.5F, -4F, 1.25F, 2.5F, 1F)
                .texOffs(446, 250).addBox(-1.6F, 24.5F, -4F, 1.25F, 2.5F, 1F)
                .texOffs(455, 250).addBox(-3.2F, 24.5F, -4F, 1.25F, 2.5F, 1F), PartPose.offset(-13.5F, -6F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(76, 177).addBox(-1.4F, -1F, -2F, 2.8F, 4F, 5F)
                .texOffs(109, 177).addBox(-3F, 0F, -3.5F, 6F, 8.4F, 8F)
                .texOffs(166, 177).addBox(-2.5F, 1F, -4.5F, 5F, 5.5F, 1F)
                .texOffs(191, 177).addBox(-3.5F, 7F, -5F, 7F, 2F, 10F)
                .texOffs(260, 177).addBox(-1.25F, 6.5F, -6F, 2.5F, 3F, 1.5F)
                .texOffs(277, 177).addBox(-0.5F, 7.5F, -6.3F, 1F, 1F, 0.3F)
                .texOffs(284, 177).addBox(-2.5F, 8.5F, -3F, 5F, 6.4F, 7F)
                .texOffs(333, 177).addBox(-1.25F, 9.5F, -4F, 2.5F, 4.5F, 1F)
                .texOffs(348, 177).addBox(-3F, 13.5F, -4.5F, 6F, 1.5F, 9F)
                .texOffs(409, 177).addBox(-3.5F, 16F, -6.5F, 7F, 1.5F, 12F)
                .texOffs(0, 211).addBox(-3.25F, 15F, -6F, 6.5F, 1F, 11F)
                .texOffs(71, 211).addBox(-1.5F, 15.5F, -7F, 3F, 1.5F, 1F), PartPose.offset(6F, 6.5F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(464, 250).addBox(-1.4F, -1F, -2F, 2.8F, 4F, 5F)
                .texOffs(0, 288).addBox(-3F, 0F, -3.5F, 6F, 8.4F, 8F)
                .texOffs(57, 288).addBox(-2.5F, 1F, -4.5F, 5F, 5.5F, 1F)
                .texOffs(82, 288).addBox(-3.5F, 7F, -5F, 7F, 2F, 10F)
                .texOffs(151, 288).addBox(-1.25F, 6.5F, -6F, 2.5F, 3F, 1.5F)
                .texOffs(168, 288).addBox(-0.5F, 7.5F, -6.3F, 1F, 1F, 0.3F)
                .texOffs(175, 288).addBox(-2.5F, 8.5F, -3F, 5F, 6.4F, 7F)
                .texOffs(224, 288).addBox(-1.25F, 9.5F, -4F, 2.5F, 4.5F, 1F)
                .texOffs(239, 288).addBox(-3F, 13.5F, -4.5F, 6F, 1.5F, 9F)
                .texOffs(300, 288).addBox(-3.5F, 16F, -6.5F, 7F, 1.5F, 12F)
                .texOffs(377, 288).addBox(-3.25F, 15F, -6F, 6.5F, 1F, 11F)
                .texOffs(448, 288).addBox(-1.5F, 15.5F, -7F, 3F, 1.5F, 1F), PartPose.offset(-6F, 6.5F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                ObsidianGolemModel::createLayer, ObsidianGolemModel::new);
    }
}
