package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/stone_golem_f02.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class StoneGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "stone_golem_f02";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "stone_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "stone_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.STONE;

    public StoneGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(41, 0).addBox(-8F, -16F, -7F, 16F, 14F, 14F)
                .texOffs(102, 0).addBox(-9F, -18F, -8F, 18F, 4F, 16F)
                .texOffs(171, 0).addBox(-8F, -6F, -8F, 16F, 5F, 15F)
                .texOffs(234, 0).addBox(6F, -10F, -8F, 3F, 6F, 2F)
                .texOffs(245, 0).addBox(-9F, -10F, -8F, 3F, 6F, 2F)
                .texOffs(256, 0).addBox(-7F, -13F, -8.5F, 14F, 4F, 0.5F)
                .texOffs(285, 0).addBox(2F, -12F, -8.75F, 3F, 2F, 0.25F)
                .texOffs(292, 0).addBox(5F, -9F, -8.3F, 1F, 2F, 0.3F)
                .texOffs(295, 0).addBox(-5F, -12F, -8.75F, 3F, 2F, 0.25F)
                .texOffs(302, 0).addBox(-2F, -9F, -8.3F, 1F, 2F, 0.3F)
                .texOffs(305, 0).addBox(-2F, -11F, -9F, 4F, 5F, 1.5F)
                .texOffs(318, 0).addBox(-3F, -4F, -8.3F, 6F, 1F, 0.3F)
                .texOffs(331, 0).addBox(2F, -16F, 7F, 4F, 7F, 1F), PartPose.offset(0F, -44F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-5F, -32F, -5F, 10F, 6F, 10F)
                .texOffs(342, 0).addBox(-17F, -28F, -7F, 34F, 28F, 16F)
                .texOffs(443, 0).addBox(13F, -27F, -10F, 7F, 24F, 18F)
                .texOffs(0, 45).addBox(-20F, -27F, -10F, 7F, 24F, 18F)
                .texOffs(51, 45).addBox(-21F, -29F, -13F, 42F, 6F, 7F)
                .texOffs(150, 45).addBox(9F, -23F, -13F, 11F, 11F, 4F)
                .texOffs(181, 45).addBox(-20F, -23F, -13F, 11F, 11F, 4F)
                .texOffs(212, 45).addBox(9F, -12F, -12F, 11F, 8F, 4F)
                .texOffs(243, 45).addBox(-20F, -12F, -12F, 11F, 8F, 4F)
                .texOffs(274, 45).addBox(-9F, -22F, -11F, 18F, 16F, 4F)
                .texOffs(319, 45).addBox(-7F, -20F, -11.3F, 14F, 12F, 0.3F)
                .texOffs(348, 45).addBox(-5F, -18F, -11.55F, 10F, 8F, 0.25F)
                .texOffs(369, 45).addBox(-2F, -16F, -11.75F, 4F, 4F, 0.2F)
                .texOffs(378, 45).addBox(8F, -22F, -13F, 3F, 16F, 3F)
                .texOffs(391, 45).addBox(8F, -17F, -13.3F, 3F, 2F, 0.3F)
                .texOffs(398, 45).addBox(-11F, -22F, -13F, 3F, 16F, 3F)
                .texOffs(411, 45).addBox(-11F, -17F, -13.3F, 3F, 2F, 0.3F)
                .texOffs(418, 45).addBox(-11F, -23F, -13F, 22F, 3F, 3F)
                .texOffs(0, 88).addBox(-11F, -8F, -13F, 22F, 4F, 3F)
                .texOffs(51, 88).addBox(-18F, -4F, -12F, 36F, 6F, 5F)
                .texOffs(134, 88).addBox(-14F, -1F, -9F, 28F, 6F, 18F)
                .texOffs(227, 88).addBox(-7F, 0F, -11F, 14F, 10F, 5F)
                .texOffs(266, 88).addBox(-19F, -27F, 9F, 38F, 24F, 5F)
                .texOffs(353, 88).addBox(-21F, -28F, 10F, 42F, 4F, 5F)
                .texOffs(0, 118).addBox(-18F, -6F, 10F, 36F, 4F, 5F)
                .texOffs(83, 118).addBox(-1F, -24F, 14F, 3F, 16F, 0.3F)
                .texOffs(90, 118).addBox(-2F, -20F, 14.3F, 3F, 9F, 0.25F)
                .texOffs(97, 118).addBox(20F, -42F, 9F, 4F, 18F, 7F)
                .texOffs(120, 118).addBox(20F, -44F, 8F, 4F, 4F, 9F)
                .texOffs(147, 118).addBox(11F, -37F, 10F, 3F, 11F, 5F)
                .texOffs(164, 118).addBox(11F, -37F, 15F, 3F, 4F, 0.5F)
                .texOffs(171, 118).addBox(-24F, -42F, 9F, 4F, 18F, 7F)
                .texOffs(194, 118).addBox(-24F, -44F, 8F, 4F, 4F, 9F)
                .texOffs(221, 118).addBox(-14F, -37F, 10F, 3F, 11F, 5F)
                .texOffs(238, 118).addBox(-14F, -37F, 15F, 3F, 4F, 0.5F)
                .texOffs(41, 340).addBox(15F, -5F, 5F, 5F, 4F, 5F)
                .texOffs(62, 340).addBox(-20F, -5F, 5F, 5F, 4F, 5F), PartPose.offset(0F, -15F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(245, 118).addBox(-3F, -3F, -5F, 8F, 9F, 11F)
                .texOffs(284, 118).addBox(-5F, -1F, -6F, 12F, 23F, 13F)
                .texOffs(335, 118).addBox(-7F, -7F, -11F, 16F, 13F, 22F)
                .texOffs(412, 118).addBox(-8F, -9F, -11F, 18F, 5F, 23F)
                .texOffs(0, 155).addBox(-8F, -3F, -13F, 18F, 9F, 3F)
                .texOffs(43, 155).addBox(-7F, 4F, -13.4F, 16F, 2F, 0.4F)
                .texOffs(76, 155).addBox(-6F, -5F, -13.2F, 14F, 2F, 0.2F)
                .texOffs(105, 155).addBox(2F, -3F, -13.45F, 2F, 6F, 0.25F)
                .texOffs(110, 155).addBox(-4F, 16F, -6F, 10F, 8F, 13F)
                .texOffs(157, 155).addBox(-5F, 19F, -8F, 15F, 21F, 17F)
                .texOffs(222, 155).addBox(-4F, 21F, -11F, 13F, 17F, 3F)
                .texOffs(255, 155).addBox(8F, 21F, -7F, 3F, 16F, 16F)
                .texOffs(294, 155).addBox(3F, 24F, -11.25F, 2F, 10F, 0.25F)
                .texOffs(299, 155).addBox(2F, 24F, -11.5F, 3F, 3F, 0.25F)
                .texOffs(306, 155).addBox(-6F, 37F, -10F, 17F, 5F, 20F)
                .texOffs(381, 155).addBox(-3F, 41F, -7F, 11F, 9F, 15F)
                .texOffs(434, 155).addBox(4F, 48F, -6F, 3F, 4F, 11F)
                .texOffs(463, 155).addBox(0F, 48F, -6F, 3F, 4F, 11F)
                .texOffs(0, 194).addBox(-4F, 48F, -6F, 3F, 4F, 11F), PartPose.offset(27F, -37F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(126, 229).addBox(-5F, -3F, -5F, 8F, 9F, 11F)
                .texOffs(165, 229).addBox(-7F, -1F, -6F, 12F, 23F, 13F)
                .texOffs(216, 229).addBox(-9F, -7F, -11F, 16F, 13F, 22F)
                .texOffs(293, 229).addBox(-10F, -9F, -11F, 18F, 5F, 23F)
                .texOffs(376, 229).addBox(-10F, -3F, -13F, 18F, 9F, 3F)
                .texOffs(419, 229).addBox(-9F, 4F, -13.4F, 16F, 2F, 0.4F)
                .texOffs(452, 229).addBox(-8F, -5F, -13.2F, 14F, 2F, 0.2F)
                .texOffs(481, 229).addBox(0F, -3F, -13.45F, 2F, 6F, 0.25F)
                .texOffs(0, 266).addBox(-6F, 16F, -6F, 10F, 8F, 13F)
                .texOffs(47, 266).addBox(-10F, 19F, -8F, 15F, 21F, 17F)
                .texOffs(112, 266).addBox(-9F, 21F, -11F, 13F, 17F, 3F)
                .texOffs(145, 266).addBox(-12F, 21F, -7F, 3F, 16F, 16F)
                .texOffs(184, 266).addBox(-2F, 24F, -11.25F, 2F, 10F, 0.25F)
                .texOffs(189, 266).addBox(-3F, 24F, -11.5F, 3F, 3F, 0.25F)
                .texOffs(196, 266).addBox(-11F, 37F, -10F, 17F, 5F, 20F)
                .texOffs(271, 266).addBox(-8F, 41F, -7F, 11F, 9F, 15F)
                .texOffs(324, 266).addBox(-1F, 48F, -6F, 3F, 4F, 11F)
                .texOffs(353, 266).addBox(-5F, 48F, -6F, 3F, 4F, 11F)
                .texOffs(382, 266).addBox(-9F, 48F, -6F, 3F, 4F, 11F), PartPose.offset(-27F, -37F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(29, 194).addBox(-5F, -3F, -6F, 10F, 8F, 13F)
                .texOffs(76, 194).addBox(-7F, -1F, -8F, 14F, 17F, 17F)
                .texOffs(139, 194).addBox(-6F, 1F, -11F, 12F, 13F, 3F)
                .texOffs(170, 194).addBox(-5F, -1F, -11.2F, 10F, 3F, 0.2F)
                .texOffs(191, 194).addBox(-5F, 12F, -5F, 10F, 6F, 11F)
                .texOffs(234, 194).addBox(-8F, 13F, -11F, 16F, 5F, 21F)
                .texOffs(309, 194).addBox(-7F, 16F, -8F, 14F, 15F, 17F)
                .texOffs(372, 194).addBox(-6F, 18F, -11F, 12F, 12F, 3F)
                .texOffs(403, 194).addBox(2F, 20F, -11.3F, 2F, 5F, 0.3F)
                .texOffs(408, 194).addBox(-8F, 28F, -10F, 16F, 4F, 20F)
                .texOffs(0, 229).addBox(-9F, 29F, -13F, 18F, 6F, 24F)
                .texOffs(85, 229).addBox(-8F, 31F, -16F, 16F, 4F, 4F), PartPose.offset(12F, -11F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(411, 266).addBox(-5F, -3F, -6F, 10F, 8F, 13F)
                .texOffs(0, 305).addBox(-7F, -1F, -8F, 14F, 17F, 17F)
                .texOffs(63, 305).addBox(-6F, 1F, -11F, 12F, 13F, 3F)
                .texOffs(94, 305).addBox(-5F, -1F, -11.2F, 10F, 3F, 0.2F)
                .texOffs(115, 305).addBox(-5F, 12F, -5F, 10F, 6F, 11F)
                .texOffs(158, 305).addBox(-8F, 13F, -11F, 16F, 5F, 21F)
                .texOffs(233, 305).addBox(-7F, 16F, -8F, 14F, 15F, 17F)
                .texOffs(296, 305).addBox(-6F, 18F, -11F, 12F, 12F, 3F)
                .texOffs(327, 305).addBox(2F, 20F, -11.3F, 2F, 5F, 0.3F)
                .texOffs(332, 305).addBox(-8F, 28F, -10F, 16F, 4F, 20F)
                .texOffs(405, 305).addBox(-9F, 29F, -13F, 18F, 6F, 24F)
                .texOffs(0, 340).addBox(-8F, 31F, -16F, 16F, 4F, 4F), PartPose.offset(-12F, -11F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                StoneGolemModel::createLayer, StoneGolemModel::new);
    }
}
