package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/stone_golem_f02.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class StoneGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "stone_golem_f02";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "stone_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "stone_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.STONE;

    public StoneGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(41, 0).addBox(-4F, -8F, -3.5F, 8F, 7F, 7F)
                .texOffs(102, 0).addBox(-4.5F, -9F, -4F, 9F, 2F, 8F)
                .texOffs(171, 0).addBox(-4F, -3F, -4F, 8F, 2.5F, 7.5F)
                .texOffs(234, 0).addBox(3F, -5F, -4F, 1.5F, 3F, 1F)
                .texOffs(245, 0).addBox(-4.5F, -5F, -4F, 1.5F, 3F, 1F)
                .texOffs(256, 0).addBox(-3.5F, -6.5F, -4.25F, 7F, 2F, 0.25F)
                .texOffs(285, 0).addBox(1F, -6F, -4.375F, 1.5F, 1F, 0.125F)
                .texOffs(292, 0).addBox(2.5F, -4.5F, -4.15F, 0.5F, 1F, 0.15F)
                .texOffs(295, 0).addBox(-2.5F, -6F, -4.375F, 1.5F, 1F, 0.125F)
                .texOffs(302, 0).addBox(-1F, -4.5F, -4.15F, 0.5F, 1F, 0.15F)
                .texOffs(305, 0).addBox(-1F, -5.5F, -4.5F, 2F, 2.5F, 0.75F)
                .texOffs(318, 0).addBox(-1.5F, -2F, -4.15F, 3F, 0.5F, 0.15F)
                .texOffs(331, 0).addBox(1F, -8F, 3.5F, 2F, 3.5F, 0.5F), PartPose.offset(0F, -10F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.5F, -16F, -2.5F, 5F, 3F, 5F)
                .texOffs(342, 0).addBox(-8.5F, -14F, -3.5F, 17F, 14F, 8F)
                .texOffs(443, 0).addBox(6.5F, -13.5F, -5F, 3.5F, 12F, 9F)
                .texOffs(0, 45).addBox(-10F, -13.5F, -5F, 3.5F, 12F, 9F)
                .texOffs(51, 45).addBox(-10.5F, -14.5F, -6.5F, 21F, 3F, 3.5F)
                .texOffs(150, 45).addBox(4.5F, -11.5F, -6.5F, 5.5F, 5.5F, 2F)
                .texOffs(181, 45).addBox(-10F, -11.5F, -6.5F, 5.5F, 5.5F, 2F)
                .texOffs(212, 45).addBox(4.5F, -6F, -6F, 5.5F, 4F, 2F)
                .texOffs(243, 45).addBox(-10F, -6F, -6F, 5.5F, 4F, 2F)
                .texOffs(274, 45).addBox(-4.5F, -11F, -5.5F, 9F, 8F, 2F)
                .texOffs(319, 45).addBox(-3.5F, -10F, -5.65F, 7F, 6F, 0.15F)
                .texOffs(348, 45).addBox(-2.5F, -9F, -5.775F, 5F, 4F, 0.125F)
                .texOffs(369, 45).addBox(-1F, -8F, -5.875F, 2F, 2F, 0.1F)
                .texOffs(378, 45).addBox(4F, -11F, -6.5F, 1.5F, 8F, 1.5F)
                .texOffs(391, 45).addBox(4F, -8.5F, -6.65F, 1.5F, 1F, 0.15F)
                .texOffs(398, 45).addBox(-5.5F, -11F, -6.5F, 1.5F, 8F, 1.5F)
                .texOffs(411, 45).addBox(-5.5F, -8.5F, -6.65F, 1.5F, 1F, 0.15F)
                .texOffs(418, 45).addBox(-5.5F, -11.5F, -6.5F, 11F, 1.5F, 1.5F)
                .texOffs(0, 88).addBox(-5.5F, -4F, -6.5F, 11F, 2F, 1.5F)
                .texOffs(51, 88).addBox(-9F, -2F, -6F, 18F, 3F, 2.5F)
                .texOffs(134, 88).addBox(-7F, -0.5F, -4.5F, 14F, 3F, 9F)
                .texOffs(227, 88).addBox(-3.5F, 0F, -5.5F, 7F, 5F, 2.5F)
                .texOffs(266, 88).addBox(-9.5F, -13.5F, 4.5F, 19F, 12F, 2.5F)
                .texOffs(353, 88).addBox(-10.5F, -14F, 5F, 21F, 2F, 2.5F)
                .texOffs(0, 118).addBox(-9F, -3F, 5F, 18F, 2F, 2.5F)
                .texOffs(83, 118).addBox(-0.5F, -12F, 7F, 1.5F, 8F, 0.15F)
                .texOffs(90, 118).addBox(-1F, -10F, 7.15F, 1.5F, 4.5F, 0.125F)
                .texOffs(97, 118).addBox(10F, -21F, 4.5F, 2F, 9F, 3.5F)
                .texOffs(120, 118).addBox(10F, -22F, 4F, 2F, 2F, 4.5F)
                .texOffs(147, 118).addBox(5.5F, -18.5F, 5F, 1.5F, 5.5F, 2.5F)
                .texOffs(164, 118).addBox(5.5F, -18.5F, 7.5F, 1.5F, 2F, 0.25F)
                .texOffs(171, 118).addBox(-12F, -21F, 4.5F, 2F, 9F, 3.5F)
                .texOffs(194, 118).addBox(-12F, -22F, 4F, 2F, 2F, 4.5F)
                .texOffs(221, 118).addBox(-7F, -18.5F, 5F, 1.5F, 5.5F, 2.5F)
                .texOffs(238, 118).addBox(-7F, -18.5F, 7.5F, 1.5F, 2F, 0.25F)
                .texOffs(41, 340).addBox(7.5F, -2.5F, 2.5F, 2.5F, 2F, 2.5F)
                .texOffs(62, 340).addBox(-10F, -2.5F, 2.5F, 2.5F, 2F, 2.5F), PartPose.offset(0F, 4.5F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(245, 118).addBox(-1.5F, -1.5F, -2.5F, 4F, 4.5F, 5.5F)
                .texOffs(284, 118).addBox(-2.5F, -0.5F, -3F, 6F, 11.5F, 6.5F)
                .texOffs(335, 118).addBox(-3.5F, -3.5F, -5.5F, 8F, 6.5F, 11F)
                .texOffs(412, 118).addBox(-4F, -4.5F, -5.5F, 9F, 2.5F, 11.5F)
                .texOffs(0, 155).addBox(-4F, -1.5F, -6.5F, 9F, 4.5F, 1.5F)
                .texOffs(43, 155).addBox(-3.5F, 2F, -6.7F, 8F, 1F, 0.2F)
                .texOffs(76, 155).addBox(-3F, -2.5F, -6.6F, 7F, 1F, 0.1F)
                .texOffs(105, 155).addBox(1F, -1.5F, -6.725F, 1F, 3F, 0.125F)
                .texOffs(110, 155).addBox(-2F, 8F, -3F, 5F, 4F, 6.5F)
                .texOffs(157, 155).addBox(-2.5F, 9.5F, -4F, 7.5F, 10.5F, 8.5F)
                .texOffs(222, 155).addBox(-2F, 10.5F, -5.5F, 6.5F, 8.5F, 1.5F)
                .texOffs(255, 155).addBox(4F, 10.5F, -3.5F, 1.5F, 8F, 8F)
                .texOffs(294, 155).addBox(1.5F, 12F, -5.625F, 1F, 5F, 0.125F)
                .texOffs(299, 155).addBox(1F, 12F, -5.75F, 1.5F, 1.5F, 0.125F)
                .texOffs(306, 155).addBox(-3F, 18.5F, -5F, 8.5F, 2.5F, 10F)
                .texOffs(381, 155).addBox(-1.5F, 20.5F, -3.5F, 5.5F, 4.5F, 7.5F)
                .texOffs(434, 155).addBox(2F, 24F, -3F, 1.5F, 2F, 5.5F)
                .texOffs(463, 155).addBox(0F, 24F, -3F, 1.5F, 2F, 5.5F)
                .texOffs(0, 194).addBox(-2F, 24F, -3F, 1.5F, 2F, 5.5F), PartPose.offset(13.5F, -6.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(126, 229).addBox(-2.5F, -1.5F, -2.5F, 4F, 4.5F, 5.5F)
                .texOffs(165, 229).addBox(-3.5F, -0.5F, -3F, 6F, 11.5F, 6.5F)
                .texOffs(216, 229).addBox(-4.5F, -3.5F, -5.5F, 8F, 6.5F, 11F)
                .texOffs(293, 229).addBox(-5F, -4.5F, -5.5F, 9F, 2.5F, 11.5F)
                .texOffs(376, 229).addBox(-5F, -1.5F, -6.5F, 9F, 4.5F, 1.5F)
                .texOffs(419, 229).addBox(-4.5F, 2F, -6.7F, 8F, 1F, 0.2F)
                .texOffs(452, 229).addBox(-4F, -2.5F, -6.6F, 7F, 1F, 0.1F)
                .texOffs(481, 229).addBox(0F, -1.5F, -6.725F, 1F, 3F, 0.125F)
                .texOffs(0, 266).addBox(-3F, 8F, -3F, 5F, 4F, 6.5F)
                .texOffs(47, 266).addBox(-5F, 9.5F, -4F, 7.5F, 10.5F, 8.5F)
                .texOffs(112, 266).addBox(-4.5F, 10.5F, -5.5F, 6.5F, 8.5F, 1.5F)
                .texOffs(145, 266).addBox(-6F, 10.5F, -3.5F, 1.5F, 8F, 8F)
                .texOffs(184, 266).addBox(-1F, 12F, -5.625F, 1F, 5F, 0.125F)
                .texOffs(189, 266).addBox(-1.5F, 12F, -5.75F, 1.5F, 1.5F, 0.125F)
                .texOffs(196, 266).addBox(-5.5F, 18.5F, -5F, 8.5F, 2.5F, 10F)
                .texOffs(271, 266).addBox(-4F, 20.5F, -3.5F, 5.5F, 4.5F, 7.5F)
                .texOffs(324, 266).addBox(-0.5F, 24F, -3F, 1.5F, 2F, 5.5F)
                .texOffs(353, 266).addBox(-2.5F, 24F, -3F, 1.5F, 2F, 5.5F)
                .texOffs(382, 266).addBox(-4.5F, 24F, -3F, 1.5F, 2F, 5.5F), PartPose.offset(-13.5F, -6.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(29, 194).addBox(-2.5F, -1.5F, -3F, 5F, 4F, 6.5F)
                .texOffs(76, 194).addBox(-3.5F, -0.5F, -4F, 7F, 8.5F, 8.5F)
                .texOffs(139, 194).addBox(-3F, 0.5F, -5.5F, 6F, 6.5F, 1.5F)
                .texOffs(170, 194).addBox(-2.5F, -0.5F, -5.6F, 5F, 1.5F, 0.1F)
                .texOffs(191, 194).addBox(-2.5F, 6F, -2.5F, 5F, 3F, 5.5F)
                .texOffs(234, 194).addBox(-4F, 6.5F, -5.5F, 8F, 2.5F, 10.5F)
                .texOffs(309, 194).addBox(-3.5F, 8F, -4F, 7F, 7.5F, 8.5F)
                .texOffs(372, 194).addBox(-3F, 9F, -5.5F, 6F, 6F, 1.5F)
                .texOffs(403, 194).addBox(1F, 10F, -5.65F, 1F, 2.5F, 0.15F)
                .texOffs(408, 194).addBox(-4F, 14F, -5F, 8F, 2F, 10F)
                .texOffs(0, 229).addBox(-4.5F, 14.5F, -6.5F, 9F, 3F, 12F)
                .texOffs(85, 229).addBox(-4F, 15.5F, -8F, 8F, 2F, 2F), PartPose.offset(6F, 6.5F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(411, 266).addBox(-2.5F, -1.5F, -3F, 5F, 4F, 6.5F)
                .texOffs(0, 305).addBox(-3.5F, -0.5F, -4F, 7F, 8.5F, 8.5F)
                .texOffs(63, 305).addBox(-3F, 0.5F, -5.5F, 6F, 6.5F, 1.5F)
                .texOffs(94, 305).addBox(-2.5F, -0.5F, -5.6F, 5F, 1.5F, 0.1F)
                .texOffs(115, 305).addBox(-2.5F, 6F, -2.5F, 5F, 3F, 5.5F)
                .texOffs(158, 305).addBox(-4F, 6.5F, -5.5F, 8F, 2.5F, 10.5F)
                .texOffs(233, 305).addBox(-3.5F, 8F, -4F, 7F, 7.5F, 8.5F)
                .texOffs(296, 305).addBox(-3F, 9F, -5.5F, 6F, 6F, 1.5F)
                .texOffs(327, 305).addBox(1F, 10F, -5.65F, 1F, 2.5F, 0.15F)
                .texOffs(332, 305).addBox(-4F, 14F, -5F, 8F, 2F, 10F)
                .texOffs(405, 305).addBox(-4.5F, 14.5F, -6.5F, 9F, 3F, 12F)
                .texOffs(0, 340).addBox(-4F, 15.5F, -8F, 8F, 2F, 2F), PartPose.offset(-6F, 6.5F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                StoneGolemModel::createLayer, StoneGolemModel::new);
    }
}
