package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/wood_golem_f01.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class WoodGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "wood_golem_f01";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "wood_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "wood_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.WOOD;

    public WoodGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(33, 0).addBox(-3.5F, -9F, -3F, 7F, 8.5F, 6F)
                .texOffs(86, 0).addBox(-3F, -7.5F, -3.5F, 6F, 6.5F, 0.5F)
                .texOffs(113, 0).addBox(-4F, -9F, -3.5F, 8F, 1.5F, 7F)
                .texOffs(174, 0).addBox(-1.5F, -8F, 3F, 3F, 6.5F, 1F)
                .texOffs(191, 0).addBox(2F, -7F, -3.625F, 1F, 5F, 0.125F)
                .texOffs(196, 0).addBox(-0.5F, -7F, -3.625F, 1F, 5F, 0.125F)
                .texOffs(201, 0).addBox(-3F, -7F, -3.625F, 1F, 5F, 0.125F)
                .texOffs(206, 0).addBox(0.5F, -6F, -4F, 2F, 2F, 0.5F)
                .texOffs(217, 0).addBox(1F, -5.5F, -4.125F, 1F, 1F, 0.125F)
                .texOffs(222, 0).addBox(0F, -6.5F, -4.25F, 3F, 0.5F, 0.75F)
                .texOffs(239, 0).addBox(-2.5F, -6F, -4F, 2F, 2F, 0.5F)
                .texOffs(250, 0).addBox(-2F, -5.5F, -4.125F, 1F, 1F, 0.125F)
                .texOffs(255, 0).addBox(-3F, -6.5F, -4.25F, 3F, 0.5F, 0.75F)
                .texOffs(272, 0).addBox(-1F, -2.5F, -4F, 2F, 0.5F, 0.5F), PartPose.offset(0F, -10F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2F, -16F, -2F, 4F, 3F, 4F)
                .texOffs(283, 0).addBox(-7F, -14F, -3.5F, 14F, 14F, 7.5F)
                .texOffs(370, 0).addBox(5.5F, -13F, -5F, 3F, 12.5F, 2.5F)
                .texOffs(393, 0).addBox(-8.5F, -13F, -5F, 3F, 12.5F, 2.5F)
                .texOffs(416, 0).addBox(-9F, -14F, -6F, 18F, 2.5F, 3F)
                .texOffs(0, 44).addBox(-8.5F, -3F, -6F, 17F, 3F, 3F)
                .texOffs(81, 44).addBox(4F, -11F, -6F, 4.5F, 7.5F, 1.5F)
                .texOffs(106, 44).addBox(-8.5F, -11F, -6F, 4.5F, 7.5F, 1.5F)
                .texOffs(131, 44).addBox(-4F, -11F, -5F, 8F, 7.5F, 1.5F)
                .texOffs(170, 44).addBox(-3F, -10F, -5.2F, 6F, 5.5F, 0.2F)
                .texOffs(195, 44).addBox(-2F, -9F, -5.325F, 4F, 3.5F, 0.125F)
                .texOffs(212, 44).addBox(-1F, -8F, -5.425F, 2F, 1.5F, 0.1F)
                .texOffs(221, 44).addBox(3.5F, -11F, -6.5F, 1.5F, 7F, 1.5F)
                .texOffs(234, 44).addBox(3.75F, -11F, -6.625F, 1F, 1F, 0.125F)
                .texOffs(239, 44).addBox(3.75F, -5F, -6.625F, 1F, 1F, 0.125F)
                .texOffs(244, 44).addBox(-5F, -11F, -6.5F, 1.5F, 7F, 1.5F)
                .texOffs(257, 44).addBox(-4.75F, -11F, -6.625F, 1F, 1F, 0.125F)
                .texOffs(262, 44).addBox(-4.75F, -5F, -6.625F, 1F, 1F, 0.125F)
                .texOffs(267, 44).addBox(-5F, -11.5F, -6.5F, 10F, 1.5F, 1.5F)
                .texOffs(314, 44).addBox(-5F, -4F, -6.5F, 10F, 1.5F, 1.5F)
                .texOffs(361, 44).addBox(-5F, -0.5F, -2.5F, 10F, 2.5F, 5.5F)
                .texOffs(0, 63).addBox(-7F, -1.5F, -4.5F, 14F, 3F, 9F)
                .texOffs(93, 63).addBox(-2.5F, 0F, -5F, 5F, 4.5F, 2F)
                .texOffs(122, 63).addBox(-7.5F, -13F, 4F, 15F, 11.5F, 1.5F)
                .texOffs(189, 63).addBox(-9.5F, -13.5F, 4.5F, 19F, 2F, 1.5F)
                .texOffs(272, 63).addBox(-8F, -3F, 4.5F, 16F, 2F, 1.5F)
                .texOffs(343, 63).addBox(7F, -12F, 4.5F, 2.5F, 9.5F, 2F)
                .texOffs(362, 63).addBox(-9.5F, -12F, 4.5F, 2.5F, 9.5F, 2F)
                .texOffs(381, 63).addBox(-2F, -12F, 5.5F, 4F, 9.5F, 1F)
                .texOffs(402, 63).addBox(-8F, -7.5F, 6F, 16F, 1.5F, 1F)
                .texOffs(471, 63).addBox(6F, -7.5F, 7F, 1F, 1.5F, 0.25F)
                .texOffs(476, 63).addBox(-7F, -7.5F, 7F, 1F, 1.5F, 0.25F)
                .texOffs(119, 258).addBox(4.5F, -2F, 2.5F, 4.5F, 2F, 2.5F)
                .texOffs(148, 258).addBox(-9F, -2F, 2.5F, 4.5F, 2F, 2.5F)
                .texOffs(177, 258).addBox(8F, -18.5F, 4F, 1.5F, 5.5F, 1.5F)
                .texOffs(190, 258).addBox(7F, -18.5F, 3F, 3.5F, 2F, 3.5F)
                .texOffs(219, 258).addBox(-9.5F, -18.5F, 4F, 1.5F, 5.5F, 1.5F)
                .texOffs(232, 258).addBox(-10.5F, -18.5F, 3F, 3.5F, 2F, 3.5F), PartPose.offset(0F, 4.5F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(0, 90).addBox(-1F, -1.5F, -2.5F, 3.5F, 4F, 5.5F)
                .texOffs(37, 90).addBox(-1F, 0F, -2.5F, 3.5F, 10.5F, 5.5F)
                .texOffs(74, 90).addBox(-3F, -3.5F, -5F, 7.5F, 6.5F, 10F)
                .texOffs(145, 90).addBox(-3F, -1.5F, -6F, 7.5F, 4F, 1.5F)
                .texOffs(182, 90).addBox(-2.5F, -4F, -5F, 6.5F, 1.5F, 10F)
                .texOffs(249, 90).addBox(-2F, -4.5F, -3F, 5.5F, 1F, 5.5F)
                .texOffs(294, 90).addBox(-1F, -5.5F, -1.5F, 3.5F, 1F, 3F)
                .texOffs(321, 90).addBox(-1F, 8F, -2.5F, 3.5F, 3.5F, 5.5F)
                .texOffs(358, 90).addBox(-1.5F, 9.5F, -3F, 5.5F, 10F, 6.5F)
                .texOffs(407, 90).addBox(-1F, 10.5F, -4F, 4.5F, 8.5F, 1F)
                .texOffs(430, 90).addBox(-1F, 9F, -4F, 4.5F, 2F, 7F)
                .texOffs(0, 124).addBox(-2F, 18.5F, -4F, 6.5F, 2F, 8F)
                .texOffs(59, 124).addBox(-1F, 20F, -3F, 4.5F, 4F, 6.5F)
                .texOffs(104, 124).addBox(-0.5F, 21F, -4F, 3.5F, 2.5F, 1F)
                .texOffs(123, 124).addBox(1.6F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(148, 124).addBox(-0.1F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(173, 124).addBox(-1.8F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(198, 124).addBox(1F, 19F, -4.125F, 1F, 1F, 0.125F), PartPose.offset(12F, -6.5F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(278, 157).addBox(-2.5F, -1.5F, -2.5F, 3.5F, 4F, 5.5F)
                .texOffs(315, 157).addBox(-2.5F, 0F, -2.5F, 3.5F, 10.5F, 5.5F)
                .texOffs(352, 157).addBox(-4.5F, -3.5F, -5F, 7.5F, 6.5F, 10F)
                .texOffs(423, 157).addBox(-4.5F, -1.5F, -6F, 7.5F, 4F, 1.5F)
                .texOffs(0, 191).addBox(-4F, -4F, -5F, 6.5F, 1.5F, 10F)
                .texOffs(67, 191).addBox(-3.5F, -4.5F, -3F, 5.5F, 1F, 5.5F)
                .texOffs(112, 191).addBox(-2.5F, -5.5F, -1.5F, 3.5F, 1F, 3F)
                .texOffs(139, 191).addBox(-2.5F, 8F, -2.5F, 3.5F, 3.5F, 5.5F)
                .texOffs(176, 191).addBox(-4F, 9.5F, -3F, 5.5F, 10F, 6.5F)
                .texOffs(225, 191).addBox(-3.5F, 10.5F, -4F, 4.5F, 8.5F, 1F)
                .texOffs(248, 191).addBox(-3.5F, 9F, -4F, 4.5F, 2F, 7F)
                .texOffs(295, 191).addBox(-4.5F, 18.5F, -4F, 6.5F, 2F, 8F)
                .texOffs(354, 191).addBox(-3.5F, 20F, -3F, 4.5F, 4F, 6.5F)
                .texOffs(399, 191).addBox(-3F, 21F, -4F, 3.5F, 2.5F, 1F)
                .texOffs(418, 191).addBox(-0.9F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(443, 191).addBox(-2.6F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(468, 191).addBox(-4.3F, 23F, -2.5F, 1.4F, 2F, 4.5F)
                .texOffs(493, 191).addBox(-1.5F, 19F, -4.125F, 1F, 1F, 0.125F), PartPose.offset(-12F, -6.5F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(203, 124).addBox(-2F, -1.5F, -2.5F, 4.5F, 4F, 5.5F)
                .texOffs(244, 124).addBox(-2.5F, -0.5F, -3F, 5.5F, 9.5F, 6.5F)
                .texOffs(293, 124).addBox(-3F, 0.5F, -4.5F, 6.5F, 7F, 8.5F)
                .texOffs(354, 124).addBox(-3F, -0.5F, -4.5F, 6.5F, 2F, 8.5F)
                .texOffs(415, 124).addBox(-2F, 6.5F, -2.5F, 4.5F, 3F, 5.5F)
                .texOffs(456, 124).addBox(-2.5F, 7.5F, -3F, 5.5F, 8.5F, 6.5F)
                .texOffs(0, 157).addBox(-2F, 8.5F, -4.5F, 4.5F, 6.5F, 1.5F)
                .texOffs(25, 157).addBox(-3.5F, 7F, -4.5F, 7.5F, 2F, 9F)
                .texOffs(92, 157).addBox(-3.5F, 13.5F, -4.5F, 7.5F, 2F, 9F)
                .texOffs(159, 157).addBox(-4F, 14.5F, -5.5F, 8.5F, 3F, 10F)
                .texOffs(234, 157).addBox(-3.5F, 16F, -7F, 7.5F, 1.5F, 2F)
                .texOffs(273, 157).addBox(0F, 7.5F, -4.625F, 1F, 1F, 0.125F), PartPose.offset(5.5F, 6.5F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 225).addBox(-2.5F, -1.5F, -2.5F, 4.5F, 4F, 5.5F)
                .texOffs(41, 225).addBox(-3F, -0.5F, -3F, 5.5F, 9.5F, 6.5F)
                .texOffs(90, 225).addBox(-3.5F, 0.5F, -4.5F, 6.5F, 7F, 8.5F)
                .texOffs(151, 225).addBox(-3.5F, -0.5F, -4.5F, 6.5F, 2F, 8.5F)
                .texOffs(212, 225).addBox(-2.5F, 6.5F, -2.5F, 4.5F, 3F, 5.5F)
                .texOffs(253, 225).addBox(-3F, 7.5F, -3F, 5.5F, 8.5F, 6.5F)
                .texOffs(302, 225).addBox(-2.5F, 8.5F, -4.5F, 4.5F, 6.5F, 1.5F)
                .texOffs(327, 225).addBox(-4F, 7F, -4.5F, 7.5F, 2F, 9F)
                .texOffs(394, 225).addBox(-4F, 13.5F, -4.5F, 7.5F, 2F, 9F)
                .texOffs(0, 258).addBox(-4.5F, 14.5F, -5.5F, 8.5F, 3F, 10F)
                .texOffs(75, 258).addBox(-4F, 16F, -7F, 7.5F, 1.5F, 2F)
                .texOffs(114, 258).addBox(-0.5F, 7.5F, -4.625F, 1F, 1F, 0.125F), PartPose.offset(-5.5F, 6.5F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                WoodGolemModel::createLayer, WoodGolemModel::new);
    }
}
