package dev.local.goblinsettlement.client.model;

import dev.local.goblinsettlement.defense.GolemTier;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/generate_models.py from tools/models_golem/wood_golem_f01.json -- do not hand-edit;
 * re-run the generator instead. See ART_INTEGRATION_DESIGN.md section 3.
 */
public final class WoodGolemModel extends GoblinBodyModel {
    /** The crop this mesh was generated from. Rows in GolemBodies name it instead of retyping it. */
    public static final String CROP = "wood_golem_f01";
    /** The texture this golem samples. Rows in GolemBodies name the class instead of retyping it. */
    public static final String TEXTURE = "wood_golem";
    /** The emissive mask drawn over the texture. Rows in GolemBodies name the class, not this. */
    public static final String EMISSIVE = "wood_golem_emissive_mask";
    /** The tier this mesh is the art for. Rows in GolemBodies name the class instead of retyping it. */
    public static final GolemTier TIER = GolemTier.WOOD;

    public WoodGolemModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(33, 0).addBox(-7F, -18F, -6F, 14F, 17F, 12F)
                .texOffs(86, 0).addBox(-6F, -15F, -7F, 12F, 13F, 1F)
                .texOffs(113, 0).addBox(-8F, -18F, -7F, 16F, 3F, 14F)
                .texOffs(174, 0).addBox(-3F, -16F, 6F, 6F, 13F, 2F)
                .texOffs(191, 0).addBox(4F, -14F, -7.25F, 2F, 10F, 0.25F)
                .texOffs(196, 0).addBox(-1F, -14F, -7.25F, 2F, 10F, 0.25F)
                .texOffs(201, 0).addBox(-6F, -14F, -7.25F, 2F, 10F, 0.25F)
                .texOffs(206, 0).addBox(1F, -12F, -8F, 4F, 4F, 1F)
                .texOffs(217, 0).addBox(2F, -11F, -8.25F, 2F, 2F, 0.25F)
                .texOffs(222, 0).addBox(0F, -13F, -8.5F, 6F, 1F, 1.5F)
                .texOffs(239, 0).addBox(-5F, -12F, -8F, 4F, 4F, 1F)
                .texOffs(250, 0).addBox(-4F, -11F, -8.25F, 2F, 2F, 0.25F)
                .texOffs(255, 0).addBox(-6F, -13F, -8.5F, 6F, 1F, 1.5F)
                .texOffs(272, 0).addBox(-2F, -5F, -8F, 4F, 1F, 1F), PartPose.offset(0F, -44F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4F, -32F, -4F, 8F, 6F, 8F)
                .texOffs(283, 0).addBox(-14F, -28F, -7F, 28F, 28F, 15F)
                .texOffs(370, 0).addBox(11F, -26F, -10F, 6F, 25F, 5F)
                .texOffs(393, 0).addBox(-17F, -26F, -10F, 6F, 25F, 5F)
                .texOffs(416, 0).addBox(-18F, -28F, -12F, 36F, 5F, 6F)
                .texOffs(0, 44).addBox(-17F, -6F, -12F, 34F, 6F, 6F)
                .texOffs(81, 44).addBox(8F, -22F, -12F, 9F, 15F, 3F)
                .texOffs(106, 44).addBox(-17F, -22F, -12F, 9F, 15F, 3F)
                .texOffs(131, 44).addBox(-8F, -22F, -10F, 16F, 15F, 3F)
                .texOffs(170, 44).addBox(-6F, -20F, -10.4F, 12F, 11F, 0.4F)
                .texOffs(195, 44).addBox(-4F, -18F, -10.65F, 8F, 7F, 0.25F)
                .texOffs(212, 44).addBox(-2F, -16F, -10.85F, 4F, 3F, 0.2F)
                .texOffs(221, 44).addBox(7F, -22F, -13F, 3F, 14F, 3F)
                .texOffs(234, 44).addBox(7.5F, -22F, -13.25F, 2F, 2F, 0.25F)
                .texOffs(239, 44).addBox(7.5F, -10F, -13.25F, 2F, 2F, 0.25F)
                .texOffs(244, 44).addBox(-10F, -22F, -13F, 3F, 14F, 3F)
                .texOffs(257, 44).addBox(-9.5F, -22F, -13.25F, 2F, 2F, 0.25F)
                .texOffs(262, 44).addBox(-9.5F, -10F, -13.25F, 2F, 2F, 0.25F)
                .texOffs(267, 44).addBox(-10F, -23F, -13F, 20F, 3F, 3F)
                .texOffs(314, 44).addBox(-10F, -8F, -13F, 20F, 3F, 3F)
                .texOffs(361, 44).addBox(-10F, -1F, -5F, 20F, 5F, 11F)
                .texOffs(0, 63).addBox(-14F, -3F, -9F, 28F, 6F, 18F)
                .texOffs(93, 63).addBox(-5F, 0F, -10F, 10F, 9F, 4F)
                .texOffs(122, 63).addBox(-15F, -26F, 8F, 30F, 23F, 3F)
                .texOffs(189, 63).addBox(-19F, -27F, 9F, 38F, 4F, 3F)
                .texOffs(272, 63).addBox(-16F, -6F, 9F, 32F, 4F, 3F)
                .texOffs(343, 63).addBox(14F, -24F, 9F, 5F, 19F, 4F)
                .texOffs(362, 63).addBox(-19F, -24F, 9F, 5F, 19F, 4F)
                .texOffs(381, 63).addBox(-4F, -24F, 11F, 8F, 19F, 2F)
                .texOffs(402, 63).addBox(-16F, -15F, 12F, 32F, 3F, 2F)
                .texOffs(471, 63).addBox(12F, -15F, 14F, 2F, 3F, 0.5F)
                .texOffs(476, 63).addBox(-14F, -15F, 14F, 2F, 3F, 0.5F)
                .texOffs(119, 258).addBox(9F, -4F, 5F, 9F, 4F, 5F)
                .texOffs(148, 258).addBox(-18F, -4F, 5F, 9F, 4F, 5F)
                .texOffs(177, 258).addBox(16F, -37F, 8F, 3F, 11F, 3F)
                .texOffs(190, 258).addBox(14F, -37F, 6F, 7F, 4F, 7F)
                .texOffs(219, 258).addBox(-19F, -37F, 8F, 3F, 11F, 3F)
                .texOffs(232, 258).addBox(-21F, -37F, 6F, 7F, 4F, 7F), PartPose.offset(0F, -15F, 0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(0, 90).addBox(-2F, -3F, -5F, 7F, 8F, 11F)
                .texOffs(37, 90).addBox(-2F, 0F, -5F, 7F, 21F, 11F)
                .texOffs(74, 90).addBox(-6F, -7F, -10F, 15F, 13F, 20F)
                .texOffs(145, 90).addBox(-6F, -3F, -12F, 15F, 8F, 3F)
                .texOffs(182, 90).addBox(-5F, -8F, -10F, 13F, 3F, 20F)
                .texOffs(249, 90).addBox(-4F, -9F, -6F, 11F, 2F, 11F)
                .texOffs(294, 90).addBox(-2F, -11F, -3F, 7F, 2F, 6F)
                .texOffs(321, 90).addBox(-2F, 16F, -5F, 7F, 7F, 11F)
                .texOffs(358, 90).addBox(-3F, 19F, -6F, 11F, 20F, 13F)
                .texOffs(407, 90).addBox(-2F, 21F, -8F, 9F, 17F, 2F)
                .texOffs(430, 90).addBox(-2F, 18F, -8F, 9F, 4F, 14F)
                .texOffs(0, 124).addBox(-4F, 37F, -8F, 13F, 4F, 16F)
                .texOffs(59, 124).addBox(-2F, 40F, -6F, 9F, 8F, 13F)
                .texOffs(104, 124).addBox(-1F, 42F, -8F, 7F, 5F, 2F)
                .texOffs(123, 124).addBox(3.2F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(148, 124).addBox(-0.2F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(173, 124).addBox(-3.6F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(198, 124).addBox(2F, 38F, -8.25F, 2F, 2F, 0.25F), PartPose.offset(24F, -37F, 0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(278, 157).addBox(-5F, -3F, -5F, 7F, 8F, 11F)
                .texOffs(315, 157).addBox(-5F, 0F, -5F, 7F, 21F, 11F)
                .texOffs(352, 157).addBox(-9F, -7F, -10F, 15F, 13F, 20F)
                .texOffs(423, 157).addBox(-9F, -3F, -12F, 15F, 8F, 3F)
                .texOffs(0, 191).addBox(-8F, -8F, -10F, 13F, 3F, 20F)
                .texOffs(67, 191).addBox(-7F, -9F, -6F, 11F, 2F, 11F)
                .texOffs(112, 191).addBox(-5F, -11F, -3F, 7F, 2F, 6F)
                .texOffs(139, 191).addBox(-5F, 16F, -5F, 7F, 7F, 11F)
                .texOffs(176, 191).addBox(-8F, 19F, -6F, 11F, 20F, 13F)
                .texOffs(225, 191).addBox(-7F, 21F, -8F, 9F, 17F, 2F)
                .texOffs(248, 191).addBox(-7F, 18F, -8F, 9F, 4F, 14F)
                .texOffs(295, 191).addBox(-9F, 37F, -8F, 13F, 4F, 16F)
                .texOffs(354, 191).addBox(-7F, 40F, -6F, 9F, 8F, 13F)
                .texOffs(399, 191).addBox(-6F, 42F, -8F, 7F, 5F, 2F)
                .texOffs(418, 191).addBox(-1.8F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(443, 191).addBox(-5.2F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(468, 191).addBox(-8.6F, 46F, -5F, 2.8F, 4F, 9F)
                .texOffs(493, 191).addBox(-3F, 38F, -8.25F, 2F, 2F, 0.25F), PartPose.offset(-24F, -37F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(203, 124).addBox(-4F, -3F, -5F, 9F, 8F, 11F)
                .texOffs(244, 124).addBox(-5F, -1F, -6F, 11F, 19F, 13F)
                .texOffs(293, 124).addBox(-6F, 1F, -9F, 13F, 14F, 17F)
                .texOffs(354, 124).addBox(-6F, -1F, -9F, 13F, 4F, 17F)
                .texOffs(415, 124).addBox(-4F, 13F, -5F, 9F, 6F, 11F)
                .texOffs(456, 124).addBox(-5F, 15F, -6F, 11F, 17F, 13F)
                .texOffs(0, 157).addBox(-4F, 17F, -9F, 9F, 13F, 3F)
                .texOffs(25, 157).addBox(-7F, 14F, -9F, 15F, 4F, 18F)
                .texOffs(92, 157).addBox(-7F, 27F, -9F, 15F, 4F, 18F)
                .texOffs(159, 157).addBox(-8F, 29F, -11F, 17F, 6F, 20F)
                .texOffs(234, 157).addBox(-7F, 32F, -14F, 15F, 3F, 4F)
                .texOffs(273, 157).addBox(0F, 15F, -9.25F, 2F, 2F, 0.25F), PartPose.offset(11F, -11F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 225).addBox(-5F, -3F, -5F, 9F, 8F, 11F)
                .texOffs(41, 225).addBox(-6F, -1F, -6F, 11F, 19F, 13F)
                .texOffs(90, 225).addBox(-7F, 1F, -9F, 13F, 14F, 17F)
                .texOffs(151, 225).addBox(-7F, -1F, -9F, 13F, 4F, 17F)
                .texOffs(212, 225).addBox(-5F, 13F, -5F, 9F, 6F, 11F)
                .texOffs(253, 225).addBox(-6F, 15F, -6F, 11F, 17F, 13F)
                .texOffs(302, 225).addBox(-5F, 17F, -9F, 9F, 13F, 3F)
                .texOffs(327, 225).addBox(-8F, 14F, -9F, 15F, 4F, 18F)
                .texOffs(394, 225).addBox(-8F, 27F, -9F, 15F, 4F, 18F)
                .texOffs(0, 258).addBox(-9F, 29F, -11F, 17F, 6F, 20F)
                .texOffs(75, 258).addBox(-8F, 32F, -14F, 15F, 3F, 4F)
                .texOffs(114, 258).addBox(-1F, 15F, -9.25F, 2F, 2F, 0.25F), PartPose.offset(-11F, -11F, 0F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * This mesh's row in GolemBodies. Naming the class once is what keeps the crop, the layer and the
     * model in step, and the tier the row is keyed on comes from the class's own TIER constant -- so a
     * row can no longer pair one tier's name with another tier's geometry, skin or glow mask.
     * ArtModelCheck holds all four together against the crop's own name.
     */
    public static GolemBodies.Body body() {
        return new GolemBodies.Body(TIER, CROP, TEXTURE, EMISSIVE,
                WoodGolemModel::createLayer, WoodGolemModel::new);
    }
}
